/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface EllipseWindow : UIWindow
{
    BOOL showEcho;	// 72 = 0x48
    BOOL inUse;	// 73 = 0x49
    BOOL isAnimating;	// 74 = 0x4a
    struct CGPoint startLoc;	// 76 = 0x4c
    double startTime;	// 84 = 0x54
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0005bbc4
+ (void)initialize;	// IMP=0x0005ba90
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;	// IMP=0x0005be98
- (void)finishHide;	// IMP=0x0005be70
- (void)fixupOrdering;	// IMP=0x0005bb98
- (BOOL)isHidden;	// IMP=0x0005be0c
- (void)playTouchAnimation;	// IMP=0x0005bbe8
- (void)setHidden:(BOOL)fp8;	// IMP=0x0005be30
- (void)showTouchImage:(BOOL)fp8;	// IMP=0x0005bec0

@end

