/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (CTHelpers)
- (id)callBarringFacility;	// IMP=0x0005da44
- (id)callClass;	// IMP=0x0005d5ac
- (id)callForwardingReason;	// IMP=0x0005d840
- (id)callingLineIDRestrictionValue;	// IMP=0x0005dd20
- (id)callingLinePresentationValue;	// IMP=0x0005df0c
- (id)connectedLineIDRestrictionValue;	// IMP=0x0005e080
- (id)connectedLinePresentationValue;	// IMP=0x0005e1ac
- (id)enabledString;	// IMP=0x0005e320
- (id)mmiProcedure;	// IMP=0x0005e584
- (id)serviceCenterAddress;	// IMP=0x0005e3f0
- (struct __CFString *)settingType;	// IMP=0x0005e740
- (id)ssServiceType;	// IMP=0x0005e474
@end

