/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (PrefsNotifications)
- (id)_alertStringForPref:(id)fp8;	// IMP=0x0005f0dc
- (id)_callBarringString:(id)fp8;	// IMP=0x0005ea40
- (id)_callForwardingString:(id)fp8;	// IMP=0x0005e7dc
- (id)_callWaitingString:(id)fp8;	// IMP=0x0005e978
- (id)_callingLineIDRestrictionString:(id)fp8;	// IMP=0x0005ee2c
- (id)_callingLinePresentationString:(id)fp8;	// IMP=0x0005ecd4
- (id)_connectedLineIDRestrictionString:(id)fp8;	// IMP=0x0005ed80
- (id)_connectedLinePresentationString:(id)fp8;	// IMP=0x0005ec28
- (id)_fixedDialingString:(id)fp8;	// IMP=0x0005eb24
- (id)_serviceCenterAddressString:(id)fp8;	// IMP=0x0005ef84
- (id)_simLockString:(id)fp8;	// IMP=0x0005eed8
- (id)_ssPasswordString:(id)fp8;	// IMP=0x0005f030
- (void)addPrefNotification:(id)fp8 withUserInfo:(id)fp12;	// IMP=0x0005e76c
- (id)prefsNotificationsAlertString;	// IMP=0x0005f528
@end

