/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDisplay.h"

@class NSMutableArray, NSMutableSet, NSString, UIRemoteApplication;

@interface SBApplication : SBDisplay
{
    NSString *_roleID;	// 36 = 0x24
    NSString *_path;	// 40 = 0x28
    NSString *_bundleID;	// 44 = 0x2c
    BOOL _isLaunching;	// 48 = 0x30
    int _failedLaunchCount;	// 52 = 0x34
    int _memoryWarningCount;	// 56 = 0x38
    BOOL _enabled;	// 60 = 0x3c
    BOOL _useDemoRole;	// 61 = 0x3d
    unsigned int _dataUsage:4;	// 62 = 0x3e
    unsigned int _relauchesOnAbnormalExit:1;	// 62 = 0x3e
    unsigned int _isDefaultRole:1;	// 62 = 0x3e
    NSString *_demoRole;	// 64 = 0x40
    NSMutableSet *_statusBarItemSet;	// 68 = 0x44
    NSMutableArray *_tags;	// 72 = 0x48
    UIRemoteApplication *_remoteApplication;	// 76 = 0x4c
    struct __CFSet *_launchAlerts;	// 80 = 0x50
    int _pid;	// 84 = 0x54
    NSString *_displayName;	// 88 = 0x58
    unsigned int _doingBackgroundNetworking;	// 92 = 0x5c
}

+ (id)applicationWithDisplayIdentifier:(id)fp8;	// IMP=0x0001e350
+ (id)applicationWithPath:(id)fp8;	// IMP=0x0001de8c
+ (id)applicationWithPath:(id)fp8 roleID:(id)fp12;	// IMP=0x0001deac
+ (id)applicationWithPath:(id)fp8 roleID:(id)fp12 plist:(id)fp16;	// IMP=0x0001def8
+ (id)applicationsByRoleWithPath:(id)fp8;	// IMP=0x0001dd1c
+ (void)flushLaunchAlertsOfType:(int)fp8;	// IMP=0x000212a8
+ (void)flushSnapshotsForIdentifier:(id)fp8;	// IMP=0x0001f0e8
+ (id)iPod;	// IMP=0x0001e51c
+ (void)setUseDemoRole:(BOOL)fp8;	// IMP=0x0001e5a0
+ (id)springBoard;	// IMP=0x0001e49c
- (int)PID;	// IMP=0x00020fb0
- (id)_additionalDisplayQualification;	// IMP=0x0001eea4
- (void)_autoLaunchMailIfNeeded;	// IMP=0x00020884
- (void)_cancelWatchdogTimer;	// IMP=0x0001eb20
- (void)_relaunchAfterAbnormalExit;	// IMP=0x00020898
- (void)_sendCurrentDeviceOrientation;	// IMP=0x0001f5c0
- (void)_startDeactivationWatchdogTimer;	// IMP=0x0001e9a4
- (void)_startLaunchWatchdogTimer;	// IMP=0x0001e6ac
- (void)_startResumeWatchdogTimer;	// IMP=0x0001e828
- (BOOL)activate;	// IMP=0x0001f6a8
- (id)arguments;	// IMP=0x0001ed98
- (id)bundle;	// IMP=0x0001ed50
- (id)bundleForLaunching;	// IMP=0x0001ed7c
- (id)bundleID;	// IMP=0x0001ed48
- (unsigned int)dataUsage;	// IMP=0x0001ee08
- (BOOL)deactivate;	// IMP=0x00020138
- (void)deactivated;	// IMP=0x0002081c
- (void)dealloc;	// IMP=0x0001eb80
- (id)demoRole;	// IMP=0x0001ecdc
- (id)description;	// IMP=0x0001e650
- (id)displayIdentifier;	// IMP=0x0001efac
- (id)displayName;	// IMP=0x0001f480
- (BOOL)enabled;	// IMP=0x0001ecb4
- (void)exitedAbnormally;	// IMP=0x000208c8
- (void)exitedNormally;	// IMP=0x00020c08
- (int)failedLaunchCount;	// IMP=0x00020d3c
- (id)init;	// IMP=0x0001e60c
- (BOOL)isDefaultRole;	// IMP=0x0001eca4
- (BOOL)isRunning;	// IMP=0x00021314
- (BOOL)isWidget;	// IMP=0x0001ee9c
- (BOOL)kill;	// IMP=0x00020870
- (void)launchFailed;	// IMP=0x00020e08
- (void)launchSucceeded;	// IMP=0x00020e60
- (id)launchURLArgument;	// IMP=0x0001f57c
- (int)memoryWarningCount;	// IMP=0x00021010
- (void)noteAddedStatusBarItem:(id)fp8;	// IMP=0x00021068
- (void)noteRemovedStatusBarItem:(id)fp8;	// IMP=0x000210cc
- (id)path;	// IMP=0x0001ed40
- (id)pathForDefaultImage:(char *)fp8;	// IMP=0x0001f25c
- (id)pathForIcon;	// IMP=0x0001f058
- (unsigned int)priority;	// IMP=0x00020ce8
- (BOOL)relaunchesAfterAbnormalExit;	// IMP=0x00021058
- (id)remoteApplication;	// IMP=0x000210ec
- (void)removeAppPrefs;	// IMP=0x00020d44
- (void)resetLaunchAlertForType:(int)fp8;	// IMP=0x00021288
- (id)roleID;	// IMP=0x0001ec84
- (void)setDemoRole:(id)fp8;	// IMP=0x0001ecf0
- (void)setDisplayName:(id)fp8;	// IMP=0x0001f534
- (void)setEnabled:(BOOL)fp8;	// IMP=0x0001ecd4
- (void)setIsDefaultRole:(BOOL)fp8;	// IMP=0x0001ec8c
- (void)setMemoryWarningCount:(id)fp8;	// IMP=0x00021018
- (void)setPID:(int)fp8;	// IMP=0x00020fe0
- (void)setRelaunchesAfterAbnormalExit:(BOOL)fp8;	// IMP=0x00021040
- (void)setRoleID:(id)fp8;	// IMP=0x0001ec3c
- (void)setTags:(id)fp8;	// IMP=0x0001edb8
- (void)setUseDemoRole:(BOOL)fp8;	// IMP=0x0001ed38
- (void)setUsesBackgroundNetwork:(BOOL)fp8;	// IMP=0x0001ee14
- (BOOL)shouldLaunchPNGless;	// IMP=0x0001f1e4
- (BOOL)showLaunchAlertForType:(int)fp8;	// IMP=0x0002115c
- (id)tags;	// IMP=0x0001ee00
- (void)watchdogForDeactivate;	// IMP=0x000206f0
- (void)watchdogForLaunch;	// IMP=0x000207b8
- (void)watchdogForResume;	// IMP=0x00020754

@end

