/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, NSTimer, SBAwayMediaControlsView, TPLCDTextView;

@interface SBAwayDateView : UIView
{
    NSTimer *_dateTimer;	// 28 = 0x1c
    TPLCDTextView *_timeLabel;	// 32 = 0x20
    TPLCDTextView *_titleLabel;	// 36 = 0x24
    NSString *_title;	// 40 = 0x28
    SBAwayMediaControlsView *_controlsView;	// 44 = 0x2c
}

- (id)controlsView;	// IMP=0x000262b4
- (void)dealloc;	// IMP=0x00025910
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00026370
- (BOOL)isShowingControls;	// IMP=0x000260ec
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12;	// IMP=0x00025b60
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12 fontName:(const char *)fp20;	// IMP=0x0002599c
- (void)movedToSuperview:(id)fp8;	// IMP=0x00026090
- (void)removeFromSuperview;	// IMP=0x00026020
- (void)setIsShowingControls:(BOOL)fp8;	// IMP=0x00026124
- (void)setTitle:(id)fp8;	// IMP=0x00025fc4
- (void)updateClock;	// IMP=0x00025eb8
- (void)updateClockFormat;	// IMP=0x00025e54
- (void)updateLabels;	// IMP=0x00025ba8

@end

