/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSDate, NSDictionary, NSMutableArray, NSTimeZone, NSTimer, SBAlertItem, SBAwayItem, SBAwayModel, SBAwayView, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;	// 48 = 0x30
    SBAwayModel *_model;	// 52 = 0x34
    SBAwayView *_awayView;	// 56 = 0x38
    NSTimer *_dimTimer;	// 60 = 0x3c
    NSDate *_lockDate;	// 64 = 0x40
    SBAwayItem *_clickedItem;	// 68 = 0x44
    unsigned int _isLocked:1;	// 72 = 0x48
    unsigned int _isDimmed:1;	// 72 = 0x48
    unsigned int _isDimming:1;	// 72 = 0x48
    unsigned int _orderedOutDimmed:1;	// 72 = 0x48
    unsigned int _frontDimmed:1;	// 72 = 0x48
    unsigned int _isBlocked:1;	// 72 = 0x48
    unsigned int _makingEmergencyCall:1;	// 72 = 0x48
    unsigned int _appRequestedPasscodeEntry:1;	// 72 = 0x48
    unsigned int _needToMakeEmergencyCall:1;	// 73 = 0x49
    unsigned int _isSyncing:1;	// 73 = 0x49
    unsigned int _relockAfterUnlock:1;	// 73 = 0x49
    unsigned int _wasLockedBeforeSync:1;	// 73 = 0x49
    unsigned int _wasDeviceLockedBeforeSync:1;	// 73 = 0x49
    NSDictionary *_nowPlayingInfo;	// 76 = 0x4c
    double _sleepDelay;	// 80 = 0x50
    SBSlidingAlertDisplay *_deviceUnlockDisplay;	// 88 = 0x58
    double _deviceLockBlockTime;	// 92 = 0x5c
    double _deviceLockGracePeriodEndTimeInterval;	// 100 = 0x64
    NSTimeZone *_deviceLockGraceTimeZone;	// 108 = 0x6c
    NSMutableArray *_pendingAlertItems;	// 112 = 0x70
    SBAlertItem *_currentAlertItem;	// 116 = 0x74
    int _notifyLockStateToken;	// 120 = 0x78
}

+ (void)registerForAlerts;	// IMP=0x00021a78
+ (id)sharedAwayController;	// IMP=0x000219a8
- (void)_activateEmergencyCall;	// IMP=0x00024d9c
- (void)_clearBlockedState;	// IMP=0x00022b14
- (BOOL)_disableShowingMediaControls;	// IMP=0x00025724
- (void)_finishedUnlockAttemptWithStatus:(BOOL)fp8;	// IMP=0x00023898
- (void)_frontForSuspendedLockAfterDelay;	// IMP=0x00023190
- (void)_resetGracePeriod;	// IMP=0x00022500
- (void)_sendLockStateChangedNotification;	// IMP=0x00021ff4
- (void)_setupDeviceLockGracePeriod;	// IMP=0x000225f0
- (void)_timeChanged;	// IMP=0x00022588
- (void)_undimScreen;	// IMP=0x0002447c
- (void)_unlockWithSound:(BOOL)fp8;	// IMP=0x0002211c
- (void)activate;	// IMP=0x000245a4
- (BOOL)activateAlertItem:(id)fp8;	// IMP=0x00025210
- (void)activationChanged:(id)fp8;	// IMP=0x0002275c
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00021c00
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00021c1c
- (struct CGRect)alertWindowRect;	// IMP=0x00021a7c
- (BOOL)allowsInCallStatusBar;	// IMP=0x000248a8
- (BOOL)allowsStackingOfAlert:(id)fp8;	// IMP=0x0002485c
- (double)animateInDuration;	// IMP=0x00021e88
- (BOOL)animatesDismissal;	// IMP=0x0002496c
- (void)animator:(id)fp8 stopAnimation:(id)fp12;	// IMP=0x00024bc4
- (void)applicationDidFinishLaunching:(id)fp8;	// IMP=0x00021a2c
- (void)applicationRequestedDeviceUnlock;	// IMP=0x00022a74
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 alertDisplay:(id)fp12;	// IMP=0x000238c8
- (BOOL)attemptSnoozeRingingAlertItem;	// IMP=0x000250a4
- (void)attemptUnlock;	// IMP=0x000237ec
- (id)awayModel;	// IMP=0x00021a24
- (id)awayView;	// IMP=0x00021aec
- (void)cancelApplicationRequestedDeviceLockEntry;	// IMP=0x00022adc
- (void)cancelDimTimer;	// IMP=0x00023d1c
- (void)cleansePendingQueueOfAwayItems;	// IMP=0x00023f6c
- (void)clickItem:(id)fp8;	// IMP=0x00024c7c
- (id)currentAlertItem;	// IMP=0x00024f50
- (BOOL)deactivate;	// IMP=0x000246dc
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00025534
- (void)dealloc;	// IMP=0x00021c84
- (void)delaySleepByNumberOfSeconds:(float)fp8;	// IMP=0x000242b4
- (void)didAnimateLockKeypadIn;	// IMP=0x00024ec0
- (void)didAnimateLockKeypadOut;	// IMP=0x00024ec4
- (void)didFinishAnimatingOut;	// IMP=0x00024b48
- (void)dimScreen:(BOOL)fp8;	// IMP=0x00024348
- (void)dimTimerFired;	// IMP=0x000240e4
- (void)emergencyCallWasDisplayed;	// IMP=0x00024e0c
- (void)emergencyCallWasRemoved;	// IMP=0x00024e84
- (float)finalAlpha;	// IMP=0x00021adc
- (void)frontForSuspendedLockAfterDelay:(float)fp8;	// IMP=0x000231c0
- (void)frontLocked:(BOOL)fp8 animate:(BOOL)fp12 automatically:(BOOL)fp16;	// IMP=0x000232c4
- (void)frontLockedAnimationFinished;	// IMP=0x00023170
- (void)handleClickedItem:(id)fp8;	// IMP=0x00021d5c
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;	// IMP=0x00024ce0
- (void)hideMediaControls;	// IMP=0x00025704
- (id)initWithUIController:(id)fp8;	// IMP=0x00021738
- (BOOL)isAttemptingUnlock;	// IMP=0x00023880
- (BOOL)isBlocked;	// IMP=0x00022bd0
- (BOOL)isCurrentAlertItemRinging;	// IMP=0x00025020
- (BOOL)isDeviceLocked;	// IMP=0x0002277c
- (BOOL)isDimmed;	// IMP=0x00023e68
- (BOOL)isLocked;	// IMP=0x000230e8
- (BOOL)isMakingEmergencyCall;	// IMP=0x00024eb0
- (BOOL)isPasswordProtected;	// IMP=0x000226d0
- (BOOL)isPermanentlyBlocked:(double *)fp8;	// IMP=0x00022c64
- (BOOL)isShowingMediaControls;	// IMP=0x000256e0
- (BOOL)isSyncing;	// IMP=0x00022fcc
- (void)lock;	// IMP=0x00022050
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x000230f4
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00023118
- (void)makeEmergencyCall;	// IMP=0x00024d30
- (BOOL)moveAlertItemToAwayView:(id)fp8;	// IMP=0x00023f20
- (void)noteResetRestoreStateChanged;	// IMP=0x00022fdc
- (void)noteSyncStateChanged;	// IMP=0x00022cec
- (void)orderOut;	// IMP=0x00024998
- (void)pendOrDeactivateCurrentAlertItem;	// IMP=0x00024f58
- (void)playLockSound;	// IMP=0x00021fdc
- (void)preventIdleSleep;	// IMP=0x00023c3c
- (void)printLockLog;	// IMP=0x000232a0
- (void)reactivatePendingAlertItems;	// IMP=0x00021e94
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12;	// IMP=0x00024108
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12 dimmed:(BOOL)fp16;	// IMP=0x000241dc
- (void)resetAwayItems;	// IMP=0x00023138
- (void)restartDimTimer:(float)fp8;	// IMP=0x00023d78
- (void)setDeviceLocked:(BOOL)fp8;	// IMP=0x000228fc
- (BOOL)shouldAnimateOthersSuspension;	// IMP=0x00023204
- (void)sleep;	// IMP=0x00023c00
- (double)sleepDelay;	// IMP=0x00024218
- (void)snoozeOrStopRingingAlertItem;	// IMP=0x000251d4
- (int)statusBarMode;	// IMP=0x000248b0
- (void)stopRingingAlertItem;	// IMP=0x00025140
- (BOOL)toggleMediaControls;	// IMP=0x000257b4
- (void)toggleShowsIMEIandICCID:(id)fp8;	// IMP=0x00025838
- (void)undimScreen;	// IMP=0x000244ac
- (BOOL)undimsDisplay;	// IMP=0x00021ae4
- (void)unlockWithSound:(BOOL)fp8;	// IMP=0x00022270
- (void)unlockWithSound:(BOOL)fp8 alertDisplay:(id)fp12;	// IMP=0x000222c4
- (void)updateClockFormat;	// IMP=0x00024d00
- (void)updateInCallUI;	// IMP=0x0002569c
- (void)updateNowPlayingInfo:(id)fp8;	// IMP=0x00024c80
- (void)wake;	// IMP=0x00023c5c
- (BOOL)wantsToHandleAlert:(id)fp8;	// IMP=0x000254c4

@end

