/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSDictionary, NSString, NSTimer, SBActivationView, SBAwayChargingView, SBAwayDateView, SBAwayInCallController, SBAwayItemsView, SBNowPlayingArtView, TPBottomButtonBar, TPBottomLockBar, UIAlertSheet, UIImage, UIPushButton;

@interface SBAwayView : SBSlidingAlertDisplay
{
    BOOL _isDimmed;	// 74 = 0x4a
    BOOL _deferAwayItemFetching;	// 75 = 0x4b
    BOOL _showingBlockedIndicator;	// 76 = 0x4c
    SBAwayChargingView *_chargingView;	// 80 = 0x50
    SBAwayDateView *_dateView;	// 84 = 0x54
    SBNowPlayingArtView *_albumArtView;	// 88 = 0x58
    SBAwayItemsView *_awayItemsView;	// 92 = 0x5c
    SBActivationView *_activationView;	// 96 = 0x60
    NSTimer *_mediaControlsTimer;	// 100 = 0x64
    UIImage *_controlsLCDBG;	// 104 = 0x68
    UIImage *_priorLCDBG;	// 108 = 0x6c
    NSDictionary *_nowPlayingInfo;	// 112 = 0x70
    UIImage *_nowPlayingArt;	// 116 = 0x74
    NSString *_lastTrackArtPath;	// 120 = 0x78
    NSTimer *_blockedStatusUpdateTimer;	// 124 = 0x7c
    UIAlertSheet *_alertSheet;	// 128 = 0x80
    SBAwayInCallController *_inCallController;	// 132 = 0x84
    TPBottomLockBar *_lockBar;	// 136 = 0x88
    TPBottomButtonBar *_cancelSyncBar;	// 140 = 0x8c
    UIPushButton *_infoButton;	// 144 = 0x90
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00034330
+ (id)lockLabels:(BOOL)fp8 fontSize:(float *)fp12;	// IMP=0x00034558
- (void)_batteryStatusChanged:(id)fp8;	// IMP=0x00036e30
- (void)_clearBlockedStatusUpdateTimer;	// IMP=0x00034680
- (void)_positionAwayItemsView;	// IMP=0x00036750
- (void)_postLockCompletedNotification;	// IMP=0x00034a24
- (void)_updateBlockedStatus;	// IMP=0x000364a4
- (void)_updateBlockedStatusLabel;	// IMP=0x00035f54
- (void)addChargingView;	// IMP=0x00036fdc
- (void)addDateView;	// IMP=0x000365f0
- (void)animateToShowingDeviceLock:(BOOL)fp8;	// IMP=0x00037ac4
- (id)chargingView;	// IMP=0x00036e7c
- (void)clearMediaControlsTimer;	// IMP=0x00037040
- (id)dateView;	// IMP=0x0003652c
- (void)dealloc;	// IMP=0x000348a4
- (void)dismiss;	// IMP=0x00034ab4
- (void)finishedAnimatingIn;	// IMP=0x00034a44
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;	// IMP=0x000378f4
- (BOOL)hasAwayItems;	// IMP=0x000369e4
- (void)hideAwayItems;	// IMP=0x000368c4
- (void)hideChargingView;	// IMP=0x0003701c
- (void)hideInfoButton;	// IMP=0x00034ec8
- (void)hideMediaControls;	// IMP=0x0003710c
- (void)hideNowPlaying;	// IMP=0x00037474
- (void)hideSyncingBottomBar:(BOOL)fp8;	// IMP=0x000373fc
- (id)inCallController;	// IMP=0x00036680
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000346c0
- (BOOL)isShowingMediaControls;	// IMP=0x00037298
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00035bc8
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00035c08
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x00035b3c
- (void)musicPlayerDied:(id)fp8;	// IMP=0x000375b4
- (id)nowPlayingArtView;	// IMP=0x00037498
- (void)postLockCompletedNotification:(BOOL)fp8;	// IMP=0x00034840
- (void)removeAlertSheet;	// IMP=0x00036c6c
- (void)removeBlockedStatus;	// IMP=0x0003639c
- (void)removeDateView;	// IMP=0x000365cc
- (void)restartMediaControlsTimer;	// IMP=0x00037088
- (void)setBottomLockBar:(id)fp8;	// IMP=0x00034b38
- (void)setDimmed:(BOOL)fp8;	// IMP=0x000359c0
- (void)setDrawsBlackBackground:(BOOL)fp8;	// IMP=0x00035aec
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00035944
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;	// IMP=0x00036a08
- (BOOL)shouldAnimateIn;	// IMP=0x00034b80
- (BOOL)shouldShowBlockedRedStatus;	// IMP=0x00035ed8
- (BOOL)shouldShowInCallInfo;	// IMP=0x000366f0
- (void)showAlertSheet:(id)fp8;	// IMP=0x00036b0c
- (void)showAwayItems;	// IMP=0x000368f4
- (void)showBlockedStatus;	// IMP=0x00036338
- (void)showInfoButton;	// IMP=0x00034c60
- (void)showMediaControls;	// IMP=0x00037b1c
- (void)showSyncingBottomBar:(BOOL)fp8;	// IMP=0x000372bc
- (void)slideAlertSheetOut:(BOOL)fp8 direction:(BOOL)fp12 duration:(float)fp16;	// IMP=0x00036cc0
- (void)startAnimations;	// IMP=0x00034b88
- (void)stopAnimations;	// IMP=0x00034bcc
- (void)toggleMediaControls;	// IMP=0x00037250
- (void)updateInCallInfo;	// IMP=0x00036734
- (void)updateInterface;	// IMP=0x00034ee8
- (void)updateLockBarLabel;	// IMP=0x00035c44
- (BOOL)updateNowPlayingArt;	// IMP=0x00037760
- (void)updateNowPlayingInfo:(id)fp8;	// IMP=0x000375d4

@end

