/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBBluetoothController : NSObject
{
    NSMutableArray *_devices;	// 4 = 0x4
}

+ (id)sharedInstance;	// IMP=0x000861bc
- (void)addDeviceNotification:(id)fp8;	// IMP=0x000866e0
- (void)batteryChanged:(id)fp8;	// IMP=0x0008685c
- (float)batteryLevel;	// IMP=0x00086360
- (BOOL)canReportBatteryLevel;	// IMP=0x000862f8
- (void)connectionChanged:(id)fp8;	// IMP=0x000867ac
- (void)dealloc;	// IMP=0x0008620c
- (id)firstBTDeviceToReportBatteryLevel;	// IMP=0x0008625c
- (void)iapDeviceChanged:(id)fp8;	// IMP=0x000866c4
- (void)noteDevicesChanged;	// IMP=0x00086414
- (void)removeDeviceNotification:(id)fp8;	// IMP=0x00086758
- (void)startWatchingForDevices;	// IMP=0x0008645c
- (void)stopWatchingForDevices;	// IMP=0x00086668

@end

