/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCallFailureAlertItem : SBAlertItem
{
    int _causeCode;	// 12 = 0xc
    NSString *_address;	// 16 = 0x10
    struct __CTCall *_call;	// 20 = 0x14
}

- (void)_callback;	// IMP=0x00062cd8
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00063090
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00062df8
- (void)dealloc;	// IMP=0x00062c74
- (id)initWithCauseCode:(long)fp8 call:(struct __CTCall *)fp12;	// IMP=0x00062be8
- (id)lockLabel;	// IMP=0x00062d50
- (void)performUnlockAction;	// IMP=0x00063074

@end

