/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class SBCalendarIconContentsView;

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
    SBCalendarIconContentsView *_dateContents;	// 112 = 0x70
}

- (void)dealloc;	// IMP=0x0004c264
- (id)initWithApplication:(id)fp8;	// IMP=0x0004c138
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x0004c2b8

@end

