/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBCallAlert : SBAlert
{
    BOOL _causedSuspension;	// 48 = 0x30
}

+ (void)registerForAlerts;	// IMP=0x0001c018
- (void)_handleCallEvent:(struct __CTCall *)fp8;	// IMP=0x0001c4b0
- (void)_handleCallerIDEvent:(struct __CTCall *)fp8;	// IMP=0x0001c514
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0001c7fc
- (BOOL)allowsInCallStatusBar;	// IMP=0x0001ca38
- (double)animateInDuration;	// IMP=0x0001c914
- (BOOL)animatesDismissal;	// IMP=0x0001c928
- (void)dealloc;	// IMP=0x0001c464
- (BOOL)displaysAboveLock;	// IMP=0x0001c90c
- (id)initWithCall:(struct __CTCall *)fp8;	// IMP=0x0001c040
- (BOOL)useUIAlertSheetWhenUnlocked;	// IMP=0x0001c920

@end

