/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TPPhonePad.h"

@class SBEmergencyCallButton, UIImage, UIPushButton;

@interface SBDeviceLockKeypad : TPPhonePad
{
    UIImage *_deleteIcon;	// 104 = 0x68
    UIPushButton *_deleteButton;	// 108 = 0x6c
    SBEmergencyCallButton *_emergencyCallButton;	// 112 = 0x70
    BOOL _showDeleteIcon;	// 116 = 0x74
    BOOL _playKeyboardClicks;	// 117 = 0x75
}

- (id)_keypadImage;	// IMP=0x00064fa0
- (id)_pressedImage;	// IMP=0x00064e44
- (float)_yFudge;	// IMP=0x0006508c
- (void)dealloc;	// IMP=0x00064c70
- (void)hiddenFromView;	// IMP=0x00064f1c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000647d4
- (void)setPlaysKeyboardClicks:(BOOL)fp8;	// IMP=0x00064a0c
- (void)setShowsDeleteIcon:(BOOL)fp8;	// IMP=0x00064cf0
- (void)setShowsEmergencyCallButton:(BOOL)fp8;	// IMP=0x00064a9c
- (BOOL)showsEmergencyCallButton;	// IMP=0x00064a8c
- (void)willBecomeVisible;	// IMP=0x00064f84

@end

