/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, SBButtonBar, SBEditIcon;

@interface SBIconModel : NSObject
{
    NSDictionary *_iconState;	// 4 = 0x4
    NSMutableArray *_iconLists;	// 8 = 0x8
    SBButtonBar *_buttonBar;	// 12 = 0xc
    SBEditIcon *_editIcon;	// 16 = 0x10
    NSMutableDictionary *_allAppIcons;	// 20 = 0x14
    NSMutableArray *_displayedIcons;	// 24 = 0x18
    NSMutableDictionary *_accessoryIcons;	// 28 = 0x1c
    NSMutableArray *_buttonBarIcons;	// 32 = 0x20
    NSMutableArray *_hiddenIconTags;	// 36 = 0x24
    NSMutableArray *_visibleIconTags;	// 40 = 0x28
    NSMutableArray *_duplicateIcons;	// 44 = 0x2c
    NSMutableDictionary *_displayDefinitions;	// 48 = 0x30
    NSMutableArray *_displayModel;	// 52 = 0x34
}

+ (id)sharedInstance;	// IMP=0x0008367c
- (void)_addApplicationsToBucket:(id)fp8 fromPath:(id)fp12 withTags:(id)fp16;	// IMP=0x00083da0
- (void)_addBookmarks;	// IMP=0x000845a8
- (id)_rolesForInfoPlist:(id)fp8;	// IMP=0x00083b1c
- (id)_rolesForRoleDefinitions:(id)fp8;	// IMP=0x00083a48
- (void)_updateSchemesForRoleDefinition:(id)fp8 displayIdentifier:(id)fp12;	// IMP=0x00083cb0
- (id)addEmptyIconList;	// IMP=0x0008525c
- (void)addIconToFirstAvailableList:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16;	// IMP=0x0008559c
- (id)allAppDisplayIdentifiers;	// IMP=0x0008489c
- (id)bookmarkIconForDisplayIdentifier:(id)fp8;	// IMP=0x0008467c
- (id)buttonBar;	// IMP=0x00084da0
- (id)buttonBarIcons;	// IMP=0x00084bac
- (void)changeVisibilityOfIconsWithVisibleTags:(id)fp8 hiddenTags:(id)fp12;	// IMP=0x000838a4
- (void)compactIconLists;	// IMP=0x0008537c
- (void)dealloc;	// IMP=0x000837f0
- (id)displayNameForRoleDefinition:(id)fp8 inBundle:(id)fp12;	// IMP=0x00083bb8
- (id)editIcon;	// IMP=0x00084ba4
- (id)firstAvailableIconListX:(int *)fp8 Y:(int *)fp12;	// IMP=0x00085470
- (id)iconForDisplayIdentifier:(id)fp8;	// IMP=0x00084bb4
- (BOOL)iconIsVisible:(id)fp8;	// IMP=0x00083980
- (id)iconListContainingIcon:(id)fp8;	// IMP=0x000851a4
- (id)iconLists;	// IMP=0x00084e30
- (BOOL)iconListsAreDirty;	// IMP=0x0008563c
- (id)iconState;	// IMP=0x00084bf4
- (id)init;	// IMP=0x000836cc
- (void)loadAccessoryIcons;	// IMP=0x0008479c
- (void)loadAllIcons;	// IMP=0x00084984
- (void)noteIconStateChangedExternally;	// IMP=0x00084d2c
- (void)relayout;	// IMP=0x000858a4
- (void)reloadAllIcons;	// IMP=0x00084868
- (void)removeEmptyIconList:(id)fp8;	// IMP=0x000852f8
- (void)saveIconState;	// IMP=0x000856b8
- (void)uninstallBookmarkIcon:(id)fp8;	// IMP=0x000850bc

@end

