/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBLowPowerAlertItem : SBAlertItem
{
    unsigned int _talkMinutesLeft;	// 12 = 0xc
    unsigned int _talkLevel;	// 16 = 0x10
}

+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)fp8;	// IMP=0x0006e6bc
+ (unsigned int)_thresholdForLevel:(unsigned int)fp8;	// IMP=0x0006e684
+ (void)saveLowBatteryLog;	// IMP=0x0006dc98
+ (void)savePowerDiagnosisLogWithCurrentCapacity:(int)fp8 startCapacity:(int)fp12;	// IMP=0x0006e1b8
+ (void)setBatteryLevel:(unsigned int)fp8;	// IMP=0x0006e754
+ (id)systemVersionDescription;	// IMP=0x0006db30
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006eb3c
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006e9b8
- (id)initWithTalkTimeLeft:(unsigned int)fp8 level:(unsigned int)fp12;	// IMP=0x0006e634
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x0006eb68
- (BOOL)shouldShowInLockScreen;	// IMP=0x0006eb60
- (BOOL)undimsScreen;	// IMP=0x0006eb70
- (void)willPresentAlertSheet:(id)fp8;	// IMP=0x0006e9a0

@end

