/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface SBMediaController : NSObject
{
    int _manualVolumeChangeCount;	// 4 = 0x4
    NSDictionary *_nowPlayingInfo;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00087430
- (BOOL)_performIAPCommand:(int)fp8 status:(int)fp12;	// IMP=0x00087cdc
- (void)_registerForAVSystemControllerNotifications;	// IMP=0x000878f0
- (void)_serverConnectionDied:(id)fp8;	// IMP=0x00087b28
- (void)_systemVolumeChanged:(id)fp8;	// IMP=0x00087b64
- (void)_unregisterForAVSystemControllerNotifications;	// IMP=0x00087a68
- (BOOL)beginSeek:(int)fp8;	// IMP=0x0008773c
- (BOOL)changeTrack:(int)fp8;	// IMP=0x0008770c
- (void)dealloc;	// IMP=0x000873c4
- (BOOL)endSeek:(int)fp8;	// IMP=0x0008776c
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x00087878
- (BOOL)hasTrack;	// IMP=0x00087500
- (id)init;	// IMP=0x0008736c
- (BOOL)isFirstTrack;	// IMP=0x00087530
- (BOOL)isLastTrack;	// IMP=0x00087598
- (BOOL)isMovie;	// IMP=0x00087650
- (BOOL)isPlaying;	// IMP=0x00087600
- (void)musicPlayerDied:(id)fp8;	// IMP=0x00087b44
- (id)nowPlayingAlbum;	// IMP=0x000876e4
- (id)nowPlayingArtist;	// IMP=0x00087694
- (id)nowPlayingTitle;	// IMP=0x000876bc
- (void)setNowPlayingInfo:(id)fp8;	// IMP=0x00087480
- (void)setVolume:(float)fp8;	// IMP=0x0008781c
- (BOOL)togglePlayPause;	// IMP=0x0008779c
- (float)volume;	// IMP=0x000877c4

@end

