/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIAlertSheet.h"

@interface SBNowPlayingAlertSheet : UIAlertSheet
{
    unsigned int _layoutAsLocked:1;	// 104 = 0x68
}

- (void)_positionControlButton:(int)fp8 withFloor:(float)fp12;	// IMP=0x0007d334
- (void)layout;	// IMP=0x0007d4c4
- (void)setLayoutAsLocked:(BOOL)fp8;	// IMP=0x0007d8c0

@end

