/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SBPlatformController : NSObject
{
    NSString *_currentConfigurationName;	// 4 = 0x4
    NSMutableDictionary *_currentConfiguration;	// 8 = 0x8
    NSMutableDictionary *_currentCapabilities;	// 12 = 0xc
    void *_shmem;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x0007b664
- (void)dealloc;	// IMP=0x0007b740
- (id)disallowedDisplayIdentifiers;	// IMP=0x0007b93c
- (BOOL)hasCapability:(id)fp8;	// IMP=0x0007b860
- (id)iconState;	// IMP=0x0007b88c
- (id)infoForCapability:(id)fp8;	// IMP=0x0007b800
- (id)init;	// IMP=0x0007b6b4
- (id)localizedPlatformName;	// IMP=0x0007b9e0
- (BOOL)matchesPlatforms:(id)fp8;	// IMP=0x0007b8b4
- (id)platformName;	// IMP=0x0007b884
- (void)setInfo:(id)fp8 forCapability:(id)fp12;	// IMP=0x0007b820
- (id)systemVersion;	// IMP=0x0007b7a0

@end

