/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPlatformController.h"

@interface SBPlatformController (private)
- (void)_addConfigurationNamed:(id)fp8 toCompositeDictionary:(id)fp12;	// IMP=0x0007bc00
- (BOOL)allowSensitiveUI;	// IMP=0x0007bd68
- (id)currentConfigurationName;	// IMP=0x0007ba64
- (void)discoverCurrentConfiguration;	// IMP=0x0007be00
- (void)loadBundlesForCurrentConfiguration;	// IMP=0x0007c068
- (void)noteConfigurationChanged:(id)fp8;	// IMP=0x0007c180
- (void)postCurrentConfiguration;	// IMP=0x0007badc
- (void)runPrefUpdateToolIfNeeded;	// IMP=0x0007c218
@end

