/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBRestoreFailureAlertItem : SBAlertItem
{
}

- (void)_rebootNow;	// IMP=0x0007b2e8
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0007b374
- (BOOL)allowMenuButtonDismissal;	// IMP=0x0007b3a8
- (double)autoDismissInterval;	// IMP=0x0007b2d8
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0007b13c
- (void)performUnlockAction;	// IMP=0x0007b340
- (void)restartSystemEvent;	// IMP=0x0007b2fc
- (BOOL)shouldShowInLockScreen;	// IMP=0x0007b3b0

@end

