/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBSIMLockAlertItem : SBAlertItem
{
    int _status;	// 12 = 0xc
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006a690
- (id)alertText;	// IMP=0x0006a49c
- (id)alertTitle;	// IMP=0x0006a32c
- (BOOL)canUnlock;	// IMP=0x0006a314
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006a748
- (void)didDeactivateForReason:(int)fp8;	// IMP=0x0006a5dc
- (id)lockLabel;	// IMP=0x0006a9bc
- (void)performUnlockAction;	// IMP=0x0006a6e8
- (int)status;	// IMP=0x0006a5d4
- (void)unlock;	// IMP=0x0006a648

@end

