/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitGetInputDisplay.h"

@interface SBSIMToolkitGetYesNoInputDisplay : SBSIMToolkitGetInputDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x000584dc
- (void)noPressed:(id)fp8;	// IMP=0x00057098
- (void)yesPressed:(id)fp8;	// IMP=0x00057040

@end

