/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMLockEntryAlertDisplay.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertDisplay : SBSIMLockEntryAlertDisplay
{
    int _state;	// 76 = 0x4c
    NSString *_enteredPUKCode;	// 80 = 0x50
    NSString *_newPIN;	// 84 = 0x54
}

- (void)_attemptPUKUnlock;	// IMP=0x0006d8b8
- (id)_pukAttemptsRemainingLabel;	// IMP=0x0006d41c
- (void)dealloc;	// IMP=0x0006d3bc
- (id)label;	// IMP=0x0006d7f8
- (void)setupFailureState;	// IMP=0x0006d6d4
- (void)setupSuccess;	// IMP=0x0006d51c
- (id)titleText;	// IMP=0x0006d5f8
- (void)unlock;	// IMP=0x0006d8d0

@end

