/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertInputView.h"

@interface SBSIMToolkitGetInputDisplay : SBAlertInputView
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x00056c70
- (void)displayDidTimeout;	// IMP=0x00056f00
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00056bec
- (void)sbAlertInputViewCancelClicked:(id)fp8;	// IMP=0x00056fec
- (void)sbAlertInputViewSendClicked:(id)fp8;	// IMP=0x00056f54

@end

