/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSArray, UITable;

@interface SBSIMToolkitListDisplay : SBSlidingAlertDisplay
{
    UITable *_table;	// 76 = 0x4c
    NSArray *_items;	// 80 = 0x50
}

+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00057fe8
- (void)_selectListItem:(unsigned long)fp8;	// IMP=0x00057208
- (id)_simToolkitListItems;	// IMP=0x00057150
- (void)alertDisplayWillBecomeVisible;	// IMP=0x000575fc
- (void)dealloc;	// IMP=0x000570f0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000572b4
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x000577b4
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x00057838
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x000575a0
- (BOOL)showsDesktopImage;	// IMP=0x00057598
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x00057864
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x00057a6c

@end

