/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBSIMLockEntryAlert : SBAlert
{
    int _status;	// 48 = 0x30
}

- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0006aa18
- (BOOL)deactivate;	// IMP=0x0006ac10
- (int)status;	// IMP=0x0006abc4

@end

