/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBDeviceLockKeypad, SBEmergencyCallView, TPLCDView, UIImageView, UIPasscodeField, UIView;

@interface SBSlidingAlertDisplay : SBAlertDisplay
{
    UIImageView *_backgroundView;	// 36 = 0x24
    UIView *_topBar;	// 40 = 0x28
    UIView *_bottomBar;	// 44 = 0x2c
    TPLCDView *_deviceLockStatusView;	// 48 = 0x30
    SBDeviceLockKeypad *_deviceLockKeypad;	// 52 = 0x34
    UIImageView *_deviceLockEntryBackground;	// 56 = 0x38
    UIPasscodeField *_deviceLockEntryField;	// 60 = 0x3c
    SBEmergencyCallView *_emergencyCallView;	// 64 = 0x40
    UIView *_emergencyCallTopBar;	// 68 = 0x44
    BOOL _playKeyboardClicks;	// 72 = 0x48
    unsigned int _animatingEmergencyCall:1;	// 73 = 0x49
    unsigned int _animatingIn:1;	// 73 = 0x49
    unsigned int _animatingOut:1;	// 73 = 0x49
    unsigned int _shouldFenceAnimations:1;	// 73 = 0x49
    unsigned int _showingDeviceLock:1;	// 73 = 0x49
    unsigned int _attemptingUnlock:1;	// 73 = 0x49
    unsigned int _showingDeviceUnlockFailure:1;	// 73 = 0x49
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00050a88
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00050a14
+ (void)setDisplayPropertiesForActivationOfAlert:(id)fp8;	// IMP=0x00050a90
- (void)_animateToHidingDeviceLockFinished;	// IMP=0x00052964
- (void)_animateToHidingOrShowingDeviceLockFinished;	// IMP=0x000528cc
- (void)_animateToShowingDeviceLockFinished;	// IMP=0x00052920
- (void)_animateView:(id)fp8 direction:(int)fp12;	// IMP=0x00053020
- (void)_clearUnlockFailedIndicator;	// IMP=0x00050ddc
- (void)_enableEntry;	// IMP=0x00052c10
- (void)_entryFinishedWithPassword:(id)fp8;	// IMP=0x00052d38
- (struct CGRect)_entryFrame;	// IMP=0x000523bc
- (void)_fadeOutCompleted:(id)fp8;	// IMP=0x00051664
- (void)_resetStatusTextView;	// IMP=0x00050d20
- (void)_setTopBarImage:(id)fp8 shadowColor:(struct CGColor *)fp12;	// IMP=0x00050bc0
- (void)_showUnlockFailedIndicator;	// IMP=0x00050e3c
- (float)_startingKeypadXOrigin;	// IMP=0x0005245c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x000521fc
- (void)animateDisplayIn:(float)fp8 middleDelay:(float)fp12 animateStatusBar:(BOOL)fp16;	// IMP=0x00051ef4
- (void)animateFromEmergencyCallWithDuration:(float)fp8;	// IMP=0x000535d0
- (void)animateToEmergencyCall;	// IMP=0x000530a4
- (void)animateToShowingDeviceLock:(BOOL)fp8;	// IMP=0x00052514
- (void)beginAnimatingDisplayIn:(BOOL)fp8;	// IMP=0x00051c48
- (id)bottomBar;	// IMP=0x000539b8
- (void)dealloc;	// IMP=0x0005108c
- (void)deviceUnlockCanceled;	// IMP=0x00052bd0
- (void)deviceUnlockFailed;	// IMP=0x000529dc
- (void)deviceUnlockSucceeded;	// IMP=0x000529a8
- (void)dismiss;	// IMP=0x00051780
- (float)durationForOthersActivation;	// IMP=0x00051778
- (void)emergencyCallWasDisplayed;	// IMP=0x000534f0
- (void)emergencyCallWasRemoved;	// IMP=0x000538c0
- (void)finishedAnimatingIn;	// IMP=0x00051588
- (void)getFrameForTopButton:(struct CGRect *)fp8 bottomButton:(struct CGRect *)fp12;	// IMP=0x0005124c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00050eec
- (BOOL)isAnimatingOut;	// IMP=0x00051654
- (BOOL)isDisplayingErrorStatus;	// IMP=0x00052cd8
- (BOOL)isReadyToBeRemovedFromView;	// IMP=0x00051764
- (BOOL)isShowingDeviceLock;	// IMP=0x000523ac
- (id)lockBar;	// IMP=0x00051134
- (struct CGRect)middleFrame;	// IMP=0x0005118c
- (void)passcodeFieldDidAcceptEntry:(id)fp8;	// IMP=0x0005301c
- (void)performAnimateDisplayIn;	// IMP=0x00051e5c
- (void)phonePad:(id)fp8 keyDown:(BOOL)fp12;	// IMP=0x00052d8c
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;	// IMP=0x00052dbc
- (void)removeBlockedStatus;	// IMP=0x00052ca4
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00051744
- (void)setShouldFenceAnimations:(BOOL)fp8;	// IMP=0x00052394
- (void)setShowingDeviceLock:(BOOL)fp8;	// IMP=0x000524f0
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;	// IMP=0x000539c8
- (BOOL)shouldAnimateIconsIn;	// IMP=0x00051604
- (BOOL)shouldAnimateIconsOut;	// IMP=0x0005164c
- (BOOL)shouldShowBlockedRedStatus;	// IMP=0x00052c60
- (void)showBlockedStatus;	// IMP=0x00052c68
- (BOOL)showsDesktopImage;	// IMP=0x000513ec
- (id)topBar;	// IMP=0x000539c0
- (void)updateDesktopImage:(id)fp8;	// IMP=0x000513f4

@end

