/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSoundPreferences : NSObject
{
}

+ (id)calendarAlarmPath;	// IMP=0x0004fbc4
+ (BOOL)playLockSound;	// IMP=0x0004fc98
+ (id)ringtonePath;	// IMP=0x0004fc14
+ (BOOL)shouldVibrateForCurrentRingerState;	// IMP=0x0004fee8
+ (void)userDefaultsDidChanged:(id)fp8;	// IMP=0x0004fae4
+ (id)vibratePattern;	// IMP=0x0004fcfc
+ (BOOL)vibrateWhenRinging;	// IMP=0x0004fe20
+ (BOOL)vibrateWhenSilent;	// IMP=0x0004fe84

@end

