/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString;

@interface SBStatusBarNoServiceView : SBStatusBarContentView
{
    NSString *_errorString;	// 36 = 0x24
}

+ (id)displayStringForRegistrationStatus:(int)fp8;	// IMP=0x0005f790
+ (id)displayStringForSIMStatus:(id)fp8;	// IMP=0x0005f62c
- (void)dealloc;	// IMP=0x0005f908
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0005f95c
- (id)initWithErrorString:(id)fp8;	// IMP=0x0005f830
- (struct __GSFont *)textFont;	// IMP=0x0005f9fc

@end

