/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class SBStatusBarOperatorNameView, UIImage;

@interface SBStatusBarCarrierView : SBStatusBarContentView
{
    UIImage *_operatorIcon;	// 36 = 0x24
    SBStatusBarOperatorNameView *_operatorNameView;	// 40 = 0x28
    BOOL _operatorNameIsLooping;	// 44 = 0x2c
}

- (id)_imageForOperatorName:(id)fp8 statusBarIsFullScreenOpaque:(BOOL)fp12;	// IMP=0x0003ec0c
- (void)clearLastOperatorNameLooped;	// IMP=0x0003df94
- (void)dealloc;	// IMP=0x0003dd78
- (struct CGSize)defaultSize;	// IMP=0x0003e6d4
- (void)finishedLoopingOperatorName:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003e208
- (id)init;	// IMP=0x0003ec4c
- (void)loopIfNecessary;	// IMP=0x0003e350
- (void)loopOperatorNameToBeginning:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003dff0
- (void)loopOperatorNameToEnd;	// IMP=0x0003e0cc
- (id)operatorIconForName:(id)fp8;	// IMP=0x0003e970
- (void)operatorNameChanged;	// IMP=0x0003e70c
- (void)setOperatorName:(id)fp8;	// IMP=0x0003e3cc
- (void)start;	// IMP=0x0003ddd8
- (void)startOperatorNameLooping:(id)fp8;	// IMP=0x0003e2e4
- (void)stop;	// IMP=0x0003df00

@end

