/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class UIView;

@interface SBStatusWindow : UIWindow
{
    int _orientation;	// 72 = 0x48
    UIView *_holderView;	// 76 = 0x4c
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0001a5c8
- (id)holderView;	// IMP=0x0001a700
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0001a5f4
- (BOOL)isOpaque;	// IMP=0x0001a5ec
- (int)orientation;	// IMP=0x0001a6f0
- (void)setOrientation:(int)fp8;	// IMP=0x0001a6f8

@end

