/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBTVOutController : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00085a0c
- (void)dealloc;	// IMP=0x00085ab4
- (id)init;	// IMP=0x00085a5c
- (void)mergeSetting:(struct __CFString *)fp8 iapSettings:(id)fp12 finalSettings:(id)fp16 settingMergeSelector:(SEL)fp20;	// IMP=0x00085b04
- (id)mergedTVOutSettingForUserSetting:(id)fp8 iapSetting:(id)fp12;	// IMP=0x00085bd0
- (void)setIntialTVModeIfNeeded;	// IMP=0x00085c7c
- (void)updateLayerKitSettings:(id)fp8;	// IMP=0x00085e0c
- (void)updateSettings;	// IMP=0x00085f04

@end

