/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBTVOutController.h"

@interface SBTVOutController (private)
- (void)startListeningForSettingsChanges;	// IMP=0x00086154
- (void)stopListeningForSettingsChanges;	// IMP=0x00086198
@end

