/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBApplication, SBContentLayer, SBZoomView, UIView, UIWindow;

@interface SBUIController : NSObject
{
    UIWindow *_window;	// 4 = 0x4
    UIView *_iconsView;	// 8 = 0x8
    SBContentLayer *_contentLayer;	// 12 = 0xc
    SBZoomView *_zoomLayer;	// 16 = 0x10
    SBApplication *_launchedApp;	// 20 = 0x14
    int _launchState;	// 24 = 0x18
    BOOL _lastVolumeDownToControl;	// 28 = 0x1c
    BOOL _shouldAutoLock;	// 29 = 0x1d
    int _batteryCapacity;	// 32 = 0x20
    BOOL _isBatteryCharging;	// 36 = 0x24
    BOOL _isOnAC;	// 37 = 0x25
    BOOL _cancelingLaunch;	// 38 = 0x26
    int _batteryLoggingStartCapacity;	// 40 = 0x28
    unsigned char _headsetBatteryCapacity;	// 44 = 0x2c
    BOOL _isHeadsetCharging;	// 45 = 0x2d
    BOOL _isHeadsetDocked;	// 46 = 0x2e
}

+ (int)displayedLevelForBatteryLevel:(int)fp8;	// IMP=0x0000bf3c
+ (int)displayedLevelForBatteryStatusBarLevel:(int)fp8;	// IMP=0x0000c1d8
+ (id)sharedInstance;	// IMP=0x0000ca18
- (void)ACPowerChanged;	// IMP=0x0000fcec
- (void)_indicateConnectedToPower;	// IMP=0x0000bf24
- (struct CGAffineTransform)_initialStatusBarTransformForScale:(float)fp8;	// IMP=0x0000eaec
- (void)animateAppleDown:(BOOL)fp8;	// IMP=0x0000cae0
- (void)animateLaunchApplication:(id)fp8;	// IMP=0x0000f398
- (double)animateLaunchForReturnToLastApp:(id)fp8;	// IMP=0x0000f484
- (void)animateLaunchOfApplication:(id)fp8;	// IMP=0x0000f330
- (void)animateLaunchOfApplication:(id)fp8 afterDelay:(double)fp12 startingAtTime:(double)fp20 forDuration:(double)fp28 includingIconsAndButtonBar:(BOOL)fp36 initialZoomScale:(float)fp40 fadeInZoom:(BOOL)fp44;	// IMP=0x0000eb5c
- (void)applicationExited:(id)fp8;	// IMP=0x0000fccc
- (void)applicationSuspended:(id)fp8;	// IMP=0x0000fcd0
- (int)batteryCapacity;	// IMP=0x0000fcd4
- (float)calculateStartupTime;	// IMP=0x0000cf8c
- (void)cancelLaunchAnimationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x0000f700
- (void)cancelLaunchOfApplication:(id)fp8 duration:(double)fp12;	// IMP=0x0000f124
- (void)clearLaunchedAfterLanguageRestart;	// IMP=0x0000cf50
- (void)clearZoomLayer;	// IMP=0x0000df1c
- (void)clickedMenuButton;	// IMP=0x0000f75c
- (void)completeAlertDisplay;	// IMP=0x0000f950
- (id)contentView;	// IMP=0x0000dfe0
- (void)dealloc;	// IMP=0x0000ca68
- (void)finishLaunching;	// IMP=0x0000d8d8
- (void)finishedFadingInButtonBar;	// IMP=0x0000f538
- (id)getVMstats;	// IMP=0x0000d084
- (void)handleAccessoryAvailabilityChange:(struct __GSEvent *)fp8 removal:(BOOL)fp12;	// IMP=0x0000fe70
- (void)handleAccessoryEvent:(struct __GSEvent *)fp8;	// IMP=0x0000fed8
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x0000faec
- (unsigned char)headsetBatteryCapacity;	// IMP=0x0000fe68
- (void)hideIconListAndBar:(BOOL)fp8;	// IMP=0x0000e398
- (id)init;	// IMP=0x00010014
- (BOOL)isBatteryCharging;	// IMP=0x0000fcdc
- (BOOL)isHeadsetBatteryCharging;	// IMP=0x0000fe60
- (BOOL)isHeadsetDocked;	// IMP=0x0000fe58
- (BOOL)isOnAC;	// IMP=0x0000fce4
- (void)languageChanged;	// IMP=0x0000d534
- (int)launchState;	// IMP=0x0000df14
- (BOOL)launchedAfterLanguageRestart;	// IMP=0x0000cf28
- (void)lock;	// IMP=0x0000def4
- (void)lock:(BOOL)fp8;	// IMP=0x0000db84
- (void)logStartupData;	// IMP=0x0000d330
- (void)noteStatusBarHeightChanged:(float)fp8 duration:(double)fp12;	// IMP=0x0000fd58
- (void)quitTopApplication;	// IMP=0x0000eac4
- (void)restoreIconList:(BOOL)fp8 force:(BOOL)fp12;	// IMP=0x0000e400
- (void)setState:(int)fp8;	// IMP=0x0000df5c
- (BOOL)shouldDisconnectCallsOnLockPress;	// IMP=0x0000db7c
- (void)showButtonBar:(BOOL)fp8 animate:(BOOL)fp12 action:(SEL)fp16 delegate:(id)fp20;	// IMP=0x0000e8f4
- (void)showZoomLayerAnimationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x0000f618
- (void)showZoomLayerForApp:(id)fp8;	// IMP=0x0000e028
- (id)statusBarWindow;	// IMP=0x0000dfe8
- (void)stopAllAnimations;	// IMP=0x0000e394
- (void)stopRestoringIconList;	// IMP=0x0000e804
- (void)systemControllerRouteChanged:(id)fp8;	// IMP=0x0000db48
- (void)wakeUp:(id)fp8;	// IMP=0x0000f9f0
- (id)window;	// IMP=0x0000e020

@end

