/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBVoicemailManager : NSObject
{
    CDAnonymousStruct1 _alertMark;	// 4 = 0x4
    CDAnonymousStruct1 _awayItemMark;	// 20 = 0x14
    BOOL _hasVisualVoicemail;	// 36 = 0x24
    int _visualVoicemailSubscriptionToken;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x000788f4
- (void)_handleVoicemailAvailableNotification:(id)fp8;	// IMP=0x00078dd0
- (void)_handleVoicemailStoreChangedNotification;	// IMP=0x00078f98
- (BOOL)_hasVisualVoicemail;	// IMP=0x00078a8c
- (void)_mark:(CDAnonymousStruct1 *)fp8;	// IMP=0x00078a94
- (void)_presentAlertForRecord:(void *)fp8 visualVoicemail:(BOOL)fp12;	// IMP=0x00078bd8
- (void)_updateVisualVoicemailState;	// IMP=0x00078a48
- (id)copyVisualVoicemailRecordsForAwayItems;	// IMP=0x00078b98
- (void)dealloc;	// IMP=0x00078854
- (id)init;	// IMP=0x0007876c
- (void)mark;	// IMP=0x00078b64
- (void)markForAlerts;	// IMP=0x00078b24
- (void)markForAwayItems;	// IMP=0x00078b44
- (void)setHasVisualVoicemail:(BOOL)fp8;	// IMP=0x00078958

@end

