/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplication.h"

@interface SBWidgetApplication : SBApplication
{
}

- (id)arguments;	// IMP=0x00021554
- (id)bundleForLaunching;	// IMP=0x000214ec
- (BOOL)isWidget;	// IMP=0x0002154c
- (id)pathForDefaultImage:(char *)fp8;	// IMP=0x00021384
- (id)pathForIcon;	// IMP=0x000214c4

@end

