/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSDictionary, NSMutableArray, NSString, NSTimer, UITable;

@interface SBWiFiAlertItem : SBAlertItem
{
    NSMutableArray *_networks;	// 12 = 0xc
    NSTimer *_scanTimer;	// 16 = 0x10
    UITable *_table;	// 20 = 0x14
    struct CGSize _size;	// 24 = 0x18
    int _joinRow;	// 32 = 0x20
    NSString *_password;	// 36 = 0x24
    NSDictionary *_joinDict;	// 40 = 0x28
    SBAlertItem *_childAlert;	// 44 = 0x2c
    BOOL _selectingRow;	// 48 = 0x30
    BOOL _storedPassword;	// 49 = 0x31
    BOOL _passwordFailed;	// 50 = 0x32
}

- (void)_enableTable;	// IMP=0x00070938
- (int)_joinRow;	// IMP=0x0006fd28
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x000711fc
- (BOOL)allowMenuButtonDismissal;	// IMP=0x00071388
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x000717f8
- (void)dealloc;	// IMP=0x00071108
- (id)deletionSetForLostNetworks:(id)fp8 originalNetworks:(id)fp12;	// IMP=0x0007005c
- (void)didDeactivateForReason:(int)fp8;	// IMP=0x00071a48
- (void)didPresentAlertSheet:(id)fp8;	// IMP=0x00070e8c
- (void)dismiss;	// IMP=0x0007095c
- (BOOL)dismissOnLock;	// IMP=0x00071a40
- (id)init;	// IMP=0x0006fbd4
- (id)insertionsForNewNetworks:(id)fp8;	// IMP=0x0006ff14
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x000713ac
- (void)passwordEntered:(id)fp8;	// IMP=0x00070f94
- (void)performUnlockAction;	// IMP=0x00071390
- (void)scan;	// IMP=0x0006fb78
- (void)setChildAlert:(id)fp8;	// IMP=0x0006ff0c
- (void)setNetworks:(id)fp8;	// IMP=0x0006fde4
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x000713cc
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x00071488
- (void)wifiManager:(id)fp8 joinCompleted:(int)fp12;	// IMP=0x00070b3c
- (void)wifiManager:(id)fp8 scanCompleted:(id)fp12;	// IMP=0x00070208
- (void)willActivate;	// IMP=0x00070acc
- (void)willDeactivateForReason:(int)fp8;	// IMP=0x00070a54

@end

