/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ABRingtoneManager, NSMutableArray, NSString, NSTimer;

@interface AlarmController : NSObject
{
    ABRingtoneManager *_ringtoneManager;	// 4 = 0x4
    NSMutableArray *_alarmList;	// 8 = 0x8
    NSTimer *_alarmTimer;	// 12 = 0xc
    NSMutableArray *_alarmsToFire;	// 16 = 0x10
    unsigned int _readingAlarms:1;	// 20 = 0x14
    NSTimer *_countDownTimer;	// 24 = 0x18
    double _countDownTime;	// 28 = 0x1c
    NSString *_countDownTimerSoundIdentifier;	// 36 = 0x24
    struct __CFDate *_alarmWakeupDate;	// 40 = 0x28
    struct __CFDate *_countdownWakeupDate;	// 44 = 0x2c
}

+ (id)sharedAlarmController;	// IMP=0x00060de8
- (void)_alarmChanged:(id)fp8;	// IMP=0x00061088
- (void)_alarmTimeReached:(id)fp8;	// IMP=0x0006194c
- (void)_countDownTimerFired:(id)fp8;	// IMP=0x00061c7c
- (void)_readAlarms;	// IMP=0x00060e38
- (void)_resetCountDownTime;	// IMP=0x00061108
- (void)_saveAlarms;	// IMP=0x00060f4c
- (void)_scheduleAlarms;	// IMP=0x0006155c
- (void)_sleepTimerFired:(id)fp8;	// IMP=0x00061d3c
- (void)_wokeFromSleep;	// IMP=0x00061e8c
- (unsigned int)addAlarm:(id)fp8;	// IMP=0x00061458
- (id)alarms;	// IMP=0x00061554
- (double)countDownTime;	// IMP=0x00061e78
- (id)countDownTimerSoundIdentifier;	// IMP=0x00061e84
- (void)dealloc;	// IMP=0x00061358
- (id)init;	// IMP=0x00061140
- (void)removeAlarmAtIndex:(unsigned int)fp8;	// IMP=0x00061508
- (id)ringtoneManager;	// IMP=0x00061ed8
- (void)setCountDownTime:(double)fp8 withSoundIdentifier:(id)fp16;	// IMP=0x000619f8

@end

