/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCalendarDate, NSString;

@interface Alarm : NSObject
{
    unsigned int _alarmHour;	// 4 = 0x4
    unsigned int _alarmMinute;	// 8 = 0x8
    int _alarmSetting;	// 12 = 0xc
    NSString *_alarmSoundIdentifier;	// 16 = 0x10
    NSString *_alarmTitle;	// 20 = 0x14
    NSCalendarDate *_snoozeUntilDate;	// 24 = 0x18
    unsigned int _isActive:1;	// 28 = 0x1c
    unsigned int _repeats:1;	// 28 = 0x1c
    unsigned int _allowsSnooze:1;	// 28 = 0x1c
    unsigned int _dontSendUpdate:1;	// 28 = 0x1c
    unsigned int _dontStopSnoozing:1;	// 28 = 0x1c
    unsigned int _reserved:27;	// 28 = 0x1c
}

- (void)_activateAlertItem;	// IMP=0x00060ca4
- (id)_fireDateAfterDate:(id)fp8;	// IMP=0x000606c0
- (id)_initWithDictionary:(id)fp8;	// IMP=0x00060150
- (id)_prefsDictionary;	// IMP=0x00060370
- (id)_snoozeUntilDate;	// IMP=0x00060b34
- (void)_update;	// IMP=0x00060080
- (id)alarmSoundIdentifier;	// IMP=0x00060bb0
- (BOOL)alarmTimesEqualTo:(id)fp8;	// IMP=0x00060614
- (id)alarmTitle;	// IMP=0x00060c9c
- (BOOL)allowsSnooze;	// IMP=0x000609f8
- (int)daySetting;	// IMP=0x000609a8
- (void)dealloc;	// IMP=0x000605a8
- (id)description;	// IMP=0x0005ff8c
- (void)fireAlarm;	// IMP=0x00060d2c
- (void)getAlarmHour:(unsigned int *)fp8 minute:(unsigned int *)fp12;	// IMP=0x000606ac
- (id)init;	// IMP=0x00060104
- (BOOL)isActive;	// IMP=0x00060910
- (BOOL)isSnoozing;	// IMP=0x00060a08
- (BOOL)repeats;	// IMP=0x00060964
- (void)setActive:(BOOL)fp8;	// IMP=0x000608cc
- (void)setAlarmHour:(unsigned int)fp8 minute:(unsigned int)fp12;	// IMP=0x00060670
- (void)setAlarmSoundIdentifier:(id)fp8;	// IMP=0x00060b3c
- (void)setAlarmTitle:(id)fp8;	// IMP=0x00060bb8
- (void)setAllowsSnooze:(BOOL)fp8;	// IMP=0x000609b0
- (void)setDaySetting:(int)fp8;	// IMP=0x00060974
- (void)setRepeats:(BOOL)fp8;	// IMP=0x0006091c
- (void)startSnoozingFromDate:(id)fp8;	// IMP=0x00060a18
- (void)stopSnoozing;	// IMP=0x00060adc

@end

