/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (id)pop;	// IMP=0x0003d7e0
- (id)popObject:(id)fp8;	// IMP=0x0003d868
- (void)push:(id)fp8;	// IMP=0x0003d774
- (id)top;	// IMP=0x0003d8dc
@end

