/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface SBAlertItemsController : NSObject
{
    NSMutableArray *_lockedAlertItems;	// 4 = 0x4
    NSMutableArray *_unlockedAlertItems;	// 8 = 0x8
    NSTimer *_autoDismissTimer;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x00067a5c
- (void)_deactivateAlertItem:(id)fp8 reason:(int)fp12;	// IMP=0x000680b0
- (void)activateAlertItem:(id)fp8;	// IMP=0x00067e2c
- (void)autoDismissAlertItem:(id)fp8;	// IMP=0x0006825c
- (void)convertAnimatingUnlockedAlertsToLockedAlerts;	// IMP=0x00067b9c
- (BOOL)deactivateAlertForMenuClick;	// IMP=0x00068350
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00068220
- (void)deactivateAlertItem:(id)fp8 reason:(int)fp12;	// IMP=0x00068240
- (void)deactivateAlertItemsForLock;	// IMP=0x000683d8
- (void)deactivateAllAlertItems;	// IMP=0x00067c98
- (void)dealloc;	// IMP=0x00067b3c
- (id)init;	// IMP=0x00067aac
- (BOOL)isShowingAlerts;	// IMP=0x000682a0
- (void)resetAutoDismissTimer;	// IMP=0x00067d38
- (id)visibleAlertItem;	// IMP=0x000682e8

@end

