/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface SBAppWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0000b9f0
- (void)dealloc;	// IMP=0x0000b8c0
- (id)initWithContentRect:(struct CGRect)fp8;	// IMP=0x0000b85c
- (void)sendEvent:(struct __GSEvent *)fp8;	// IMP=0x0000b920
- (BOOL)shouldRespondToStatusBarHeightChange;	// IMP=0x0000b9e8

@end

