/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBBatteryChargingView;

@interface SBAwayChargingView : UIView
{
    SBBatteryChargingView *_chargingView;	// 28 = 0x1c
    SBBatteryChargingView *_headsetChargingView;	// 32 = 0x20
    unsigned int _animatingBatteries:1;	// 36 = 0x24
    unsigned int _updateAfterAnimation:1;	// 36 = 0x24
    unsigned int _showingDeviceBattery:1;	// 36 = 0x24
    unsigned int _showingHeadsetBattery:1;	// 36 = 0x24
}

+ (struct CGSize)defaultSize;	// IMP=0x00079b68
+ (BOOL)shouldShowDeviceBattery;	// IMP=0x00079c38
+ (BOOL)shouldShowHeadsetBattery;	// IMP=0x00079c98
- (void)_batteryAnimationFinished:(id)fp8;	// IMP=0x0007ab5c
- (struct CGPoint)_dualBatteryPositionForBattery:(id)fp8;	// IMP=0x0007adf4
- (void)_finishedFadeForSwitch:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x0007a870
- (void)_finishedHideForHideToSlide:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x0007aa40
- (void)_finishedSlideForSlideToReveal:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x0007a958
- (struct CGPoint)_singleBatteryPositionForBattery:(id)fp8;	// IMP=0x0007acbc
- (void)_slideBattery:(id)fp8 toHideBattery:(id)fp12 animate:(BOOL)fp16;	// IMP=0x0007a6d0
- (void)_slideBattery:(id)fp8 toShowBattery:(id)fp12 animate:(BOOL)fp16;	// IMP=0x0007a520
- (void)_switchFromBattery:(id)fp8 toView:(id)fp12 animate:(BOOL)fp16;	// IMP=0x0007a37c
- (void)_test:(id)fp8;	// IMP=0x0007aba0
- (void)addChargingView;	// IMP=0x0007a10c
- (void)addHeadsetChargingView;	// IMP=0x0007a2e0
- (id)chargingView;	// IMP=0x00079fb0
- (void)dealloc;	// IMP=0x00079ad8
- (id)headsetChargingView;	// IMP=0x0007a1a8
- (void)hideChargingView;	// IMP=0x0007a184
- (void)hideHeadsetChargingView;	// IMP=0x0007a358
- (id)initWithFrame:(struct CGRect)fp8 awayView:(id)fp24;	// IMP=0x000799cc
- (void)updateInterface:(BOOL)fp8;	// IMP=0x00079cf8

@end

