/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

@class NSBundle, NSString;

@interface SBBookmarkIcon : SBIcon
{
    NSBundle *_bundle;	// 108 = 0x6c
    NSString *_displayName;	// 112 = 0x70
}

- (BOOL)allowsCloseBox;	// IMP=0x0008a170
- (id)bundle;	// IMP=0x0008a178
- (void)completeUninstall;	// IMP=0x0008a384
- (void)dealloc;	// IMP=0x0008a110
- (id)displayIdentifier;	// IMP=0x0008a200
- (id)displayName;	// IMP=0x0008a1f8
- (id)icon;	// IMP=0x0008a180
- (id)initWithBookmarkBundle:(id)fp8;	// IMP=0x0008a098
- (void)launch;	// IMP=0x0008a270
- (id)tags;	// IMP=0x0008a240

@end

