/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallAlertDisplay : SBSlidingAlertDisplay
{
    BOOL _wasToldToStopRinging;	// 74 = 0x4a
    BOOL _answered;	// 75 = 0x4b
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0001db7c
+ (id)createBottomLockBarForDisplay:(id)fp8;	// IMP=0x0001cac4
- (void)_ringIfNecessary;	// IMP=0x0001d248
- (id)additionalURLParameter;	// IMP=0x0001d44c
- (void)alertDisplayBecameVisible;	// IMP=0x0001d3dc
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0001d2f8
- (void)answer:(id)fp8;	// IMP=0x0001d52c
- (void)answerAndRelease;	// IMP=0x0001d4e4
- (void)answerCall:(struct __CTCall *)fp8;	// IMP=0x0001d458
- (void)checkForStatusChange;	// IMP=0x0001d140
- (void)dealloc;	// IMP=0x0001cc2c
- (void)dismiss;	// IMP=0x0001d8e8
- (void)finishedAnimatingIn;	// IMP=0x0001d3f8
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x0001db38
- (void)ignore;	// IMP=0x0001d9c4
- (void)ignoreAndRelease;	// IMP=0x0001d980
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x0001d8cc
- (void)ringOrVibrate;	// IMP=0x0001cc7c
- (void)ringerChanged;	// IMP=0x0001cd90
- (void)setAlert:(id)fp8;	// IMP=0x0001cf40
- (void)stopRingingOrVibrating;	// IMP=0x0001ccf8
- (void)updateImageFromPerson:(struct CPRecord *)fp8;	// IMP=0x0001cecc
- (void)updateLCDWithName:(id)fp8 label:(id)fp12 breakPoint:(unsigned int)fp16;	// IMP=0x0001cdbc
- (BOOL)wasToldToStopRinging;	// IMP=0x0001cd88

@end

