/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0006260c
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x000623dc
- (void)callBack:(id)fp8;	// IMP=0x000629d0
- (void)ignore:(id)fp8;	// IMP=0x0006295c
- (void)setAlert:(id)fp8;	// IMP=0x00062ae8

@end

