/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x000798a8
- (float)delayForOthersActivation;	// IMP=0x000799bc
- (void)deviceUnlockCanceled;	// IMP=0x00079860
- (void)deviceUnlockSucceeded;	// IMP=0x00079818
- (void)dismiss;	// IMP=0x00079960
- (float)durationForOthersActivation;	// IMP=0x000799c4
- (void)useEmergencyCallButton;	// IMP=0x00079814

@end

