/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBDisplayStack : NSObject
{
    NSMutableArray *_displayStack;	// 4 = 0x4
    void *_pushCallback;	// 8 = 0x8
    void *_popCallback;	// 12 = 0xc
}

- (void)_setDisplayStack:(id)fp8;	// IMP=0x0003b670
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x0003b6b8
- (void)dealloc;	// IMP=0x0003b740
- (id)description;	// IMP=0x0003bb08
- (id)displays;	// IMP=0x0003b9a0
- (void)flushWithoutCallbackSparingDisplay:(id)fp8;	// IMP=0x0003b860
- (id)init;	// IMP=0x0003b600
- (BOOL)isEmpty;	// IMP=0x0003b7b0
- (id)pop;	// IMP=0x0003b81c
- (id)popDisplay:(id)fp8;	// IMP=0x0003b938
- (void)pushDisplay:(id)fp8;	// IMP=0x0003b7d8
- (void)setPopCallBack:(void *)fp8;	// IMP=0x0003b7a8
- (void)setPushCallBack:(void *)fp8;	// IMP=0x0003b7a0
- (id)topAlert;	// IMP=0x0003ba68
- (id)topApplication;	// IMP=0x0003b9c8
- (id)topDisplay;	// IMP=0x0003b9a8

@end

