/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBEditIcon : SBApplicationIcon
{
}

- (id)_automationID;	// IMP=0x0008a514
- (BOOL)allowsCloseBox;	// IMP=0x0008a4a4
- (void)completeUninstall;	// IMP=0x0008a4ac
- (id)displayIdentifier;	// IMP=0x0008a540
- (float)grabDuration;	// IMP=0x0008a750
- (id)icon;	// IMP=0x0008a414
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x0008a6cc
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x0008a708
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0008a75c
- (void)noteEditingStateChanged;	// IMP=0x0008a3c4
- (void)showAlertIfNeeded;	// IMP=0x0008a57c
- (id)tags;	// IMP=0x0008a54c

@end

