/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@interface SBEmergencyCallView : UIView
{
    UIView *_topBar;	// 28 = 0x1c
}

- (void)dealloc;	// IMP=0x000670a4
- (id)initWithFrame:(struct CGRect)fp8 topBarFrame:(struct CGRect)fp24 bottomBarFrame:(struct CGRect)fp40;	// IMP=0x00066d50
- (void)setTopBar:(id)fp8;	// IMP=0x00067040
- (id)topBar;	// IMP=0x00067038

@end

