/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer, SBApplicationIcon, SBBookmarkIcon, SBIcon, SBIconList, SBIconModel, SBReorderInfoAlert, SBTouchPageIndicator, TPLCDTextView, UIScroller, UIView;

@interface SBIconController : NSObject
{
    SBIconModel *_iconModel;	// 4 = 0x4
    UIView *_contentView;	// 8 = 0x8
    UIScroller *_scroller;	// 12 = 0xc
    SBTouchPageIndicator *_pageIndicator;	// 16 = 0x10
    int _currentIconListIndex;	// 20 = 0x14
    TPLCDTextView *_idleText;	// 24 = 0x18
    SBApplicationIcon *_pendingIcon;	// 28 = 0x1c
    SBIcon *_lastClickedIcon;	// 32 = 0x20
    double _lastClickedTime;	// 36 = 0x24
    SBIcon *_grabbedIcon;	// 44 = 0x2c
    SBIconList *_grabbedIconList;	// 48 = 0x30
    int _grabbedX;	// 52 = 0x34
    int _grabbedY;	// 56 = 0x38
    SBIcon *_swappedIcon;	// 60 = 0x3c
    SBIconList *_swappedIconList;	// 64 = 0x40
    int _swappedX;	// 68 = 0x44
    int _swappedY;	// 72 = 0x48
    SBIconList *_destinationIconList;	// 76 = 0x4c
    int _destinationX;	// 80 = 0x50
    int _destinationY;	// 84 = 0x54
    NSTimer *_scrollPageTimer;	// 88 = 0x58
    unsigned int _didScroll:1;	// 92 = 0x5c
    unsigned int _isScrolling:1;	// 92 = 0x5c
    unsigned int _isEditing:1;	// 92 = 0x5c
    unsigned int _compacted:1;	// 92 = 0x5c
    unsigned int _willSwap:1;	// 92 = 0x5c
    unsigned int _animatingToNewState:1;	// 92 = 0x5c
    unsigned int _animateToNewStateAfterDelay:1;	// 92 = 0x5c
    unsigned int _showSpreadHole:1;	// 92 = 0x5c
    SBBookmarkIcon *_bookmarkIconToInstall;	// 96 = 0x60
    struct CGPoint _lastDragLoc;	// 100 = 0x64
    SBReorderInfoAlert *_reorderInfoAlert;	// 108 = 0x6c
}

+ (id)sharedInstance;	// IMP=0x0007f058
- (void)_addEmptyListIfNecessary;	// IMP=0x00081a34
- (void)_jitterOptionsChanged;	// IMP=0x0007f8d8
- (id)addIcon:(id)fp8 toIconList:(id)fp12 x:(int)fp16 y:(int)fp20 animate:(BOOL)fp24 moveNow:(BOOL)fp28 scrollToList:(BOOL)fp32;	// IMP=0x00080234
- (BOOL)allowsIconReordering;	// IMP=0x0007f680
- (void)animateToNewState:(float)fp8 domino:(BOOL)fp12;	// IMP=0x000831c8
- (void)appendIconList:(id)fp8;	// IMP=0x0007fddc
- (void)attemptPendingLaunch;	// IMP=0x000817ec
- (id)bookmarkIconToInstall;	// IMP=0x000800f4
- (void)cancelScrollTimer;	// IMP=0x000826cc
- (void)clickedIcon:(id)fp8;	// IMP=0x00081644
- (void)compactIconsInIconLists:(BOOL)fp8 limitToIconList:(id)fp12;	// IMP=0x00082fa0
- (id)contentView;	// IMP=0x0007f244
- (id)currentIconList;	// IMP=0x0007faf8
- (void)dealloc;	// IMP=0x0007f17c
- (id)destinationIconList;	// IMP=0x000826c4
- (void)doubleClickedIcon:(id)fp8;	// IMP=0x000815f8
- (void)finishInstallingBookmarkIcon;	// IMP=0x00080144
- (id)grabbedIcon;	// IMP=0x00082694
- (BOOL)hasIdleModeText;	// IMP=0x00080adc
- (BOOL)hasLaunchPending;	// IMP=0x000818a8
- (void)hideSpreadHole;	// IMP=0x00082f04
- (id)iconAnimationView;	// IMP=0x00081c80
- (float)idleModeTextHeight;	// IMP=0x00080780
- (void)idleTextDidAnimate:(id)fp8 finished:(id)fp12 toText:(id)fp16;	// IMP=0x000807c4
- (void)incrementReorderCount;	// IMP=0x00081944
- (id)init;	// IMP=0x0007f0a8
- (id)insertIcon:(id)fp8 intoIconList:(id)fp12 X:(int)fp16 Y:(int)fp20 moveNow:(BOOL)fp24 duration:(float)fp28;	// IMP=0x00080368
- (BOOL)isEditing;	// IMP=0x00081c70
- (void)jitterOptionsChanged;	// IMP=0x0007f978
- (void)launchIcon:(id)fp8;	// IMP=0x0008157c
- (void)lcdTextViewCompletedScroll:(id)fp8;	// IMP=0x00080744
- (int)lowestVisibleIconListIndex;	// IMP=0x0007f6cc
- (void)moveAnimation:(id)fp8 didFinish:(id)fp12 movePlan:(id)fp16;	// IMP=0x000832bc
- (void)moveIcon:(id)fp8 fromIconList:(id)fp12 toX:(int)fp16 Y:(int)fp20 toIconList:(id)fp24;	// IMP=0x00083414
- (void)moveIconFromWindow:(id)fp8 toIconList:(id)fp12;	// IMP=0x00081dcc
- (void)moveIconToWindow:(id)fp8;	// IMP=0x00081cdc
- (void)noteGrabbedIconLocationChangedWithEvent:(struct __GSEvent *)fp8;	// IMP=0x00082884
- (void)noteNumberOfIconListsChanged;	// IMP=0x0007feb4
- (void)pendLaunchOfIcon:(id)fp8;	// IMP=0x000818b8
- (void)relayoutIcons;	// IMP=0x00080088
- (void)removeAccessory:(id)fp8;	// IMP=0x000814d4
- (void)removeEmptyIconList:(id)fp8 animate:(BOOL)fp12;	// IMP=0x00080008
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x00080494
- (int)reorderCount;	// IMP=0x00081920
- (void)scatter:(BOOL)fp8;	// IMP=0x00080f64
- (void)scrollLeft;	// IMP=0x0008270c
- (void)scrollRight;	// IMP=0x000827c8
- (void)scrollToBookmarkIconDestination;	// IMP=0x00080198
- (void)scrollToIconListAtIndex:(int)fp8 animate:(BOOL)fp12;	// IMP=0x0007fbe8
- (void)scrollToIconListContainingIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0007fb54
- (void)scrollerDidEndAnimatedScrolling:(id)fp8;	// IMP=0x000813b4
- (void)scrollerDidEndDragging:(id)fp8 willSmoothScroll:(BOOL)fp12;	// IMP=0x00081360
- (void)scrollerDidEndSmoothScrolling:(id)fp8;	// IMP=0x00081388
- (void)scrollerDidScroll:(id)fp8;	// IMP=0x00081310
- (void)scrollerWillStartSmoothScrolling:(id)fp8;	// IMP=0x000812e8
- (void)setBookmarkIconToInstall:(id)fp8;	// IMP=0x000800fc
- (void)setGrabbedIcon:(id)fp8;	// IMP=0x00082018
- (void)setIdleModeText:(id)fp8;	// IMP=0x00080b14
- (void)setIsEditing:(BOOL)fp8;	// IMP=0x00081ad4
- (void)showAccessory:(id)fp8;	// IMP=0x00081404
- (void)showInfoAlertIfNeeded;	// IMP=0x0007f4ec
- (void)showSpreadHole;	// IMP=0x00082f38
- (int)spreadHoleX;	// IMP=0x0008269c
- (int)spreadHoleY;	// IMP=0x000826b0
- (void)startDraggingIcon:(id)fp8 fromIconList:(id)fp12;	// IMP=0x00081e84
- (void)startJitteringCurrentIconLists;	// IMP=0x0007f7b0
- (void)stopJitteringCurrentIconLists;	// IMP=0x0007f844
- (void)touchPageIndicator:(id)fp8 didRecieveTouchInDirection:(int)fp12;	// IMP=0x0007f9ec
- (void)ungrabAnimation:(id)fp8 didFinish:(id)fp12 grabbedIcon:(id)fp16;	// IMP=0x00081f54
- (void)uninstallIcon:(id)fp8;	// IMP=0x000805c8
- (void)uninstallIconDidAnimate:(id)fp8 finished:(id)fp12 icon:(id)fp16;	// IMP=0x00080518
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;	// IMP=0x00081148
- (void)updateContentSizeAndPageCount;	// IMP=0x0007fcc8
- (void)updateCurrentIconListIndexUpdatingPageIndicator:(BOOL)fp8;	// IMP=0x0007fa70
- (void)updateNumberOfRowsWithDuration:(float)fp8;	// IMP=0x00080834

@end

