/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPhoneAlertItem.h"

@interface SBNetworkReselectionAlertItem : SBPhoneAlertItem
{
}

+ (id)currentInstance;	// IMP=0x0006ee08
+ (BOOL)hasCurrentInstance;	// IMP=0x0006ee58
- (void)_showPrefs;	// IMP=0x0006ee70
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006f058
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006ef60
- (id)init;	// IMP=0x0006ed54
- (id)lockLabel;	// IMP=0x0006eed0
- (void)performUnlockAction;	// IMP=0x0006ef2c
- (void)willDeactivateForReason:(int)fp8;	// IMP=0x0006f094

@end

