/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class NSTimer, SBPowerDownController, TPBottomButtonBar, TPTopLockBar, UIView;

@interface SBPowerDownView : SBAlertDisplay
{
    UIView *_dimView;	// 36 = 0x24
    TPTopLockBar *_lockView;	// 40 = 0x28
    TPBottomButtonBar *_cancelView;	// 44 = 0x2c
    SBPowerDownController *_powerDownController;	// 48 = 0x30
    NSTimer *_autoDismissTimer;	// 52 = 0x34
}

- (void)animateDark;	// IMP=0x00046b14
- (void)animateIn;	// IMP=0x000466f8
- (void)animateOut;	// IMP=0x0004692c
- (void)cancel:(id)fp8;	// IMP=0x000465bc
- (void)cancelAutoDismissTimer;	// IMP=0x000464f8
- (void)dealloc;	// IMP=0x0004647c
- (void)finishedAnimatingIn;	// IMP=0x00046684
- (void)finishedAnimatingOut;	// IMP=0x000466bc
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0004602c
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00046624
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00046640
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x000465f0
- (void)notifyDelegateOfPowerDown;	// IMP=0x000466d8
- (void)powerDown:(id)fp8;	// IMP=0x0004665c
- (void)resetAutoDismissTimer;	// IMP=0x00046538
- (void)setPowerDownController:(id)fp8;	// IMP=0x0004667c

@end

