/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class AVController, NSTimer;

@interface SBRingingAlertItem : SBAlertItem
{
    AVController *_avController;	// 12 = 0xc
    NSTimer *_autoMuteTimer;	// 16 = 0x10
}

- (void)_autoMute:(id)fp8;	// IMP=0x0007861c
- (void)_stopAutoMuteTimer;	// IMP=0x000785d4
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00078638
- (id)avAudioCategory;	// IMP=0x000783d0
- (id)avClientName;	// IMP=0x000783c4
- (id)avClientPriority;	// IMP=0x000783dc
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0007817c
- (void)dealloc;	// IMP=0x00078700
- (BOOL)dismissOnLock;	// IMP=0x00078410
- (float)lockLabelFontSize;	// IMP=0x00078418
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00078408
- (id)soundIdentifier;	// IMP=0x000783b8
- (void)startRingingAndVibrating;	// IMP=0x00078440
- (void)stopRingingAndVibrating;	// IMP=0x00078678
- (void)willDeactivateForReason:(int)fp8;	// IMP=0x00078654
- (void)willPresentAlertSheet:(id)fp8;	// IMP=0x00078424

@end

