/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject
{
    BOOL _isInitialUpdate;	// 4 = 0x4
    int _status;	// 8 = 0x8
    SBSIMLockAlertItem *_currentAlert;	// 12 = 0xc
    SBSIMLockEntryAlert *_lockEntryAlert;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00069784
- (int)_CTToSBSIMStatus:(struct __CFString *)fp8;	// IMP=0x000698b0
- (BOOL)_hopelesslyPUKLocked;	// IMP=0x00069888
- (void)_initialUpdate;	// IMP=0x0006a190
- (int)_statusFromCT;	// IMP=0x00069a0c
- (void)_tearDownAlertAndUpdateStatus;	// IMP=0x00069e64
- (void)_tryToUpdateStatus;	// IMP=0x00069de8
- (void)_updateSIMStatus:(struct __CFString *)fp8 withOptions:(struct __CFDictionary *)fp12;	// IMP=0x00069ee4
- (void)_updateToStatus:(int)fp8;	// IMP=0x00069b94
- (void)alertItemDismissed:(id)fp8;	// IMP=0x00069a6c
- (void)attemptUnlock;	// IMP=0x00069b44
- (void)dealloc;	// IMP=0x000697d4
- (void)lockEntryAlertDismissed:(id)fp8;	// IMP=0x00069a38
- (int)pinLockAttemptsRemaining;	// IMP=0x0006a054
- (int)pukLockAttemptsRemaining;	// IMP=0x0006a064
- (void)registerForAlerts;	// IMP=0x0006a1dc
- (void)repopAlert;	// IMP=0x00069aa0
- (int)status;	// IMP=0x0006a30c

@end

