/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBStatusBar, SBStatusBarAirPortView, SBStatusBarBatteryView, SBStatusBarBluetoothBatteryView, SBStatusBarBluetoothView, SBStatusBarCarrierView, SBStatusBarIndicatorsView, SBStatusBarNoServiceView, SBStatusBarProgressView, SBStatusBarSignalView, SBStatusBarTimeView;

@interface SBStatusBarContentsView : UIView
{
    SBStatusBar *_statusBar;	// 28 = 0x1c
    int _mode;	// 32 = 0x20
    BOOL _dimmed;	// 36 = 0x24
    UIView *_lockIconView;	// 40 = 0x28
    SBStatusBarTimeView *_timeView;	// 44 = 0x2c
    SBStatusBarBatteryView *_batteryView;	// 48 = 0x30
    SBStatusBarSignalView *_signalView;	// 52 = 0x34
    SBStatusBarCarrierView *_carrierView;	// 56 = 0x38
    SBStatusBarIndicatorsView *_indicatorsView;	// 60 = 0x3c
    SBStatusBarAirPortView *_airPortView;	// 64 = 0x40
    SBStatusBarNoServiceView *_noServiceView;	// 68 = 0x44
    SBStatusBarBluetoothView *_bluetoothView;	// 72 = 0x48
    SBStatusBarProgressView *_progressView;	// 76 = 0x4c
    SBStatusBarBluetoothBatteryView *_bluetoothBatteryView;	// 80 = 0x50
}

+ (float)contentAlphaForMode:(int)fp8;	// IMP=0x0002bdec
- (void)bluetoothBatteryAvailabilityChanged;	// IMP=0x0002ca4c
- (void)buildContentViews;	// IMP=0x0002bbc8
- (void)cloakChanged;	// IMP=0x0002ce30
- (void)customTextChanged;	// IMP=0x0002cdf0
- (void)dealloc;	// IMP=0x0002bae4
- (void)indicatorsChanged;	// IMP=0x0002cef0
- (id)initWithStatusBar:(id)fp8 mode:(int)fp12;	// IMP=0x0002b9d4
- (void)loopCarrierNameIfNecessary;	// IMP=0x0002d0e8
- (void)progressChanged;	// IMP=0x0002ce10
- (void)reflowContentViews;	// IMP=0x0002c7d8
- (void)reflowContentViewsNow;	// IMP=0x0002be10
- (void)setAirPortStrength:(int)fp8;	// IMP=0x0002ce90
- (void)setIsInAirplaneMode:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x0002cfc0
- (void)setShowsAirPort:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x0002ceb0
- (void)setShowsService:(BOOL)fp8 SIMStatus:(id)fp12;	// IMP=0x0002cae0
- (void)signalFormatChanged;	// IMP=0x0002cdd0
- (void)significantTimeChange;	// IMP=0x0002cd98
- (void)start;	// IMP=0x0002c95c
- (void)startClock;	// IMP=0x0002ca88
- (id)statusBar;	// IMP=0x0002bbc0
- (void)stop;	// IMP=0x0002c84c
- (void)stopClock;	// IMP=0x0002ca68
- (void)updateClockFormat;	// IMP=0x0002caa8
- (void)updateContentViewsAlpha;	// IMP=0x0002d108

@end

