/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSyncController : NSObject
{
    int _syncState;	// 4 = 0x4
    int _restoreState;	// 8 = 0x8
    int _resetState;	// 12 = 0xc
    int _sofwareUpdateState;	// 16 = 0x10
    struct __CFMachPort *_backupAgentCFPort;	// 20 = 0x14
}

+ (id)sharedInstance;	// IMP=0x00075800
- (void)_delayedTurnOffRadio;	// IMP=0x000762e4
- (void)_invalidateBackupAgentCFPort;	// IMP=0x00076538
- (void)_notifyAppsSyncWillBegin;	// IMP=0x00075cec
- (void)_notifyRestoreCanProceed;	// IMP=0x00075efc
- (void)_rebootNow;	// IMP=0x00076114
- (BOOL)_setupBackupAgentPort;	// IMP=0x000765a8
- (void)beginResetting;	// IMP=0x0007635c
- (void)beginRestoring;	// IMP=0x00075f2c
- (void)beginSyncing;	// IMP=0x00075dd8
- (void)cancelRestoring;	// IMP=0x00076108
- (void)cancelSyncing;	// IMP=0x00075c8c
- (void)dealloc;	// IMP=0x00075850
- (void)didEndResetting;	// IMP=0x000763f0
- (void)didEndRestoring:(int)fp8;	// IMP=0x00076144
- (void)didEndSyncing;	// IMP=0x00075acc
- (void)didShowSyncPanel;	// IMP=0x00075d1c
- (void)finishEndRestoring;	// IMP=0x00076128
- (void)finishedTerminatingApplications;	// IMP=0x00076040
- (void)frontLockedWhenPossible;	// IMP=0x00075d38
- (void)iTunesSyncHasCompleted:(int)fp8;	// IMP=0x00075e9c
- (void)iTunesSyncRequestedStart;	// IMP=0x00075e78
- (BOOL)isInUse;	// IMP=0x000766f4
- (BOOL)isResetting;	// IMP=0x000762c4
- (BOOL)isRestoring;	// IMP=0x00075edc
- (BOOL)isSoftwareUpdating;	// IMP=0x0007664c
- (BOOL)isSyncing;	// IMP=0x00075a98
- (int)resetState;	// IMP=0x000762dc
- (int)restoreState;	// IMP=0x00075ef4
- (void)resumeSyncing;	// IMP=0x00075be4
- (void)setSoftwareUpdateState:(int)fp8;	// IMP=0x00076644
- (void)showPreSoftwareUpdateScreen;	// IMP=0x0007677c
- (void)startObserving;	// IMP=0x000758a0
- (void)stopObserving;	// IMP=0x000759c8
- (void)suspendSyncing;	// IMP=0x00075b90
- (int)syncState;	// IMP=0x00075ac4

@end

