/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBTelephonyManager : NSObject
{
    NSString *_operatorName;	// 4 = 0x4
    unsigned int _usingWifi:1;	// 8 = 0x8
    unsigned int _iTunesNeedsToRecheckActivation:1;	// 8 = 0x8
}

+ (id)sharedTelephonyManager;	// IMP=0x000279d4
- (BOOL)EDGEIsOn;	// IMP=0x0002a0a4
- (BOOL)MALoggingEnabled;	// IMP=0x00029ad8
- (id)SIMStatus;	// IMP=0x0002ace0
- (void)_cancelFakeService;	// IMP=0x0002a6ac
- (void)_delayedAudioResume;	// IMP=0x0002891c
- (id)_fetchOperatorName;	// IMP=0x0002a880
- (void)_headphoneChanged:(id)fp8;	// IMP=0x0002a480
- (void)_mainThreadDaemonRestart:(struct __CFDictionary *)fp8;	// IMP=0x00028840
- (void)_reallySetOperatorName:(id)fp8;	// IMP=0x0002a8a4
- (void)_resetCTMMode;	// IMP=0x0002a444
- (struct __CTServerConnection *)_serverConnection;	// IMP=0x00027a28
- (void)_setRegistrationStatus:(int)fp8;	// IMP=0x0002a5d4
- (void)_startFakeServiceIfNecessary;	// IMP=0x0002a6f0
- (void)_stopFakeService;	// IMP=0x0002a780
- (void)_updateRegistrationNow;	// IMP=0x0002a670
- (void)_updateState;	// IMP=0x00027d88
- (void)_whackGain:(id)fp8;	// IMP=0x00028040
- (BOOL)activeCallExists;	// IMP=0x000295b8
- (id)allMissedCallsAfterRowID:(long long)fp8;	// IMP=0x0002945c
- (id)allUnreadSMSAfterRowID:(long long)fp8;	// IMP=0x00029494
- (void)answerIncomingCall;	// IMP=0x00029704
- (void)answerIncomingCallEndingOthers;	// IMP=0x00029794
- (int)callCount;	// IMP=0x000295a8
- (void)checkForRegistrationSoon;	// IMP=0x0002abb4
- (void)configureForTTY:(BOOL)fp8;	// IMP=0x0002a1f4
- (void)copyICCID:(id *)fp8 IMEI:(id *)fp12;	// IMP=0x0002a168
- (int)dataConnectionType;	// IMP=0x0002ad9c
- (void)disconnectAllCalls;	// IMP=0x000298b0
- (void)disconnectCall;	// IMP=0x000298d8
- (void)disconnectCallAndActivateHeld;	// IMP=0x000299e0
- (void)disconnectIncomingCall;	// IMP=0x000296e0
- (id)displayForOutgoingCallURL:(id)fp8;	// IMP=0x00028208
- (void)dumpBasebandState:(id)fp8;	// IMP=0x00029a64
- (long long)getRowIDOfLastCallInsert;	// IMP=0x0002944c
- (long long)getRowIDOfLastSMSInsert;	// IMP=0x00029484
- (void)handleSIMReady;	// IMP=0x00027ef4
- (BOOL)heldCallExists;	// IMP=0x000295d0
- (BOOL)inCall;	// IMP=0x000296a0
- (double)inCallDuration;	// IMP=0x00027be8
- (BOOL)inCallUsingReceiver;	// IMP=0x00029618
- (BOOL)incomingCallExists;	// IMP=0x000295e8
- (id)init;	// IMP=0x0002b110
- (BOOL)isUsingDataConnection;	// IMP=0x0002a11c
- (BOOL)isUsingWiFiConnection;	// IMP=0x0002a144
- (void)kickStartSearching;	// IMP=0x0002acc0
- (void)markMessageAsRead:(struct __CTSMSMessage *)fp8;	// IMP=0x000294bc
- (void)noteSIMUnlockAttempt;	// IMP=0x0002ad4c
- (id)operatorName;	// IMP=0x0002a9f0
- (BOOL)outgoingCallExists;	// IMP=0x00029600
- (void)powerOffRadio;	// IMP=0x00029b58
- (int)registrationStatus;	// IMP=0x0002aba4
- (void)setIsUsingWiFiConnection:(BOOL)fp8;	// IMP=0x0002a150
- (void)setOperatorName:(id)fp8;	// IMP=0x0002a948
- (BOOL)shouldPromptForTTY;	// IMP=0x0002a25c
- (void)swapCalls;	// IMP=0x00029878
- (id)ttyTitle;	// IMP=0x0002a334
- (void)unmute;	// IMP=0x000299f0
- (void)updateAirplaneMode;	// IMP=0x00027cd0
- (void)updateCalls;	// IMP=0x000291b8
- (void)updateLocale;	// IMP=0x00027ebc
- (void)updateNetworkLocale;	// IMP=0x00027ed8
- (void)updatePhoneNumberPrefs;	// IMP=0x00027a94
- (void)updateSMSBadges;	// IMP=0x000294f0
- (void)updateSpringBoard;	// IMP=0x0002b760
- (void)updateTTYIndicator;	// IMP=0x00027b60
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20;	// IMP=0x000280bc

@end

