/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPageIndicator.h"

@interface SBTouchPageIndicator : UIPageIndicator
{
    id _delegate;	// 60 = 0x3c
}

- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0008fa0c
- (void)setDelegate:(id)fp8;	// IMP=0x0008fa04

@end

