/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBUserNotificationAlert : SBAlertItem
{
    unsigned int _replyPort;	// 12 = 0xc
    int _token;	// 16 = 0x10
    int _timeout;	// 20 = 0x14
    unsigned int _requestFlags;	// 24 = 0x18
    NSString *_alertHeader;	// 28 = 0x1c
    NSString *_alertMessage;	// 32 = 0x20
    NSString *_defaultButtonTitle;	// 36 = 0x24
    NSString *_alternateButtonTitle;	// 40 = 0x28
    id _textFieldTitles;	// 44 = 0x2c
    id _textFieldValues;	// 48 = 0x30
    id _keyboardTypes;	// 52 = 0x34
    double _creationTime;	// 56 = 0x38
    unsigned int _replyFlags;	// 64 = 0x40
    unsigned int _cancel:1;	// 68 = 0x44
    unsigned int _isActivated:1;	// 68 = 0x44
    unsigned int _aboveLock:1;	// 68 = 0x44
    unsigned int _reserved:29;	// 68 = 0x44
}

- (id)_localizedValue:(id)fp8 withBundle:(id)fp12;	// IMP=0x00063654
- (void)_sendResponse:(int)fp8;	// IMP=0x0006444c
- (id)alertSheet;	// IMP=0x00063bd0
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00064724
- (void)cancel;	// IMP=0x0006443c
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00063cb8
- (void)dealloc;	// IMP=0x00063b34
- (void)didDeactivateForReason:(int)fp8;	// IMP=0x0006476c
- (id)initWithMessage:(id)fp8 replyPort:(unsigned int)fp12 requestFlags:(int)fp16;	// IMP=0x00063830
- (BOOL)shouldShowInLockScreen;	// IMP=0x00063ca8
- (int)token;	// IMP=0x00063ca0
- (void)wakeup;	// IMP=0x000642b0

@end

