/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class SBVODAlarm;

@interface SBVODAlertItem : SBAlertItem
{
    SBVODAlarm *_alarm;	// 12 = 0xc
}

+ (id)activeAlertForAlarm:(id)fp8;	// IMP=0x00089a40
- (void)_updateText;	// IMP=0x00089ccc
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00089bc8
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00089ab0
- (void)dealloc;	// IMP=0x000899e4
- (void)screenWillUndim;	// IMP=0x00089c08
- (void)setAlarm:(id)fp8;	// IMP=0x00089a68
- (BOOL)unlocksScreen;	// IMP=0x00089bc0
- (void)willActivate;	// IMP=0x00089c24
- (void)willDeactivateForReason:(int)fp8;	// IMP=0x00089c68

@end

