/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIAlertSheetTableCell.h"

@interface SBWiFiCell : UIAlertSheetTableCell
{
    id _userInfo;	// 52 = 0x34
}

- (id)initWithFrame:(struct CGRect)fp8 networkDictionary:(id)fp24;	// IMP=0x0006f724
- (void)layoutSubviews;	// IMP=0x0006f9e0
- (void)setUserInfo:(id)fp8;	// IMP=0x0006f9d0
- (void)updateHighlightColors;	// IMP=0x0006fad0
- (id)userInfo;	// IMP=0x0006f9d8

@end

