/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock;

@interface SBWiFiManager : NSObject
{
    struct _Apple80211 *_wireless;	// 4 = 0x4
    BOOL _busy;	// 8 = 0x8
    BOOL _joining;	// 9 = 0x9
    BOOL _cancel;	// 10 = 0xa
    NSLock *_lock;	// 12 = 0xc
    id _delegate;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00071da8
- (void)_SBAirPortConfigurationChanged;	// IMP=0x0007276c
- (void)_SBAirPortPowerChanged;	// IMP=0x00072718
- (void)_SBAirPortUpdateTimer;	// IMP=0x00072708
- (void)_joinComplete:(id)fp8;	// IMP=0x00072668
- (void)_joinNetwork:(id)fp8;	// IMP=0x000725b4
- (void)_joinNetworkThread:(id)fp8;	// IMP=0x00072480
- (void)_scanComplete:(id)fp8;	// IMP=0x00072318
- (void)_scanThread;	// IMP=0x000720d4
- (BOOL)busy;	// IMP=0x00072078
- (void)cancel;	// IMP=0x00071ff0
- (void)dealloc;	// IMP=0x00071df8
- (void)dismissAlerts;	// IMP=0x00072088
- (id)init;	// IMP=0x00071e9c
- (void)joinNetwork:(id)fp8;	// IMP=0x00072818
- (void)joinSecureNetwork:(id)fp8 password:(id)fp12;	// IMP=0x000727c0
- (BOOL)joining;	// IMP=0x00072080
- (void)scan;	// IMP=0x00072004
- (void)setDelegate:(id)fp8;	// IMP=0x00071fe8

@end

