/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString, NSTimer;

@interface AlarmController : NSObject
{
    NSMutableArray *_alarmList;	// 4 = 0x4
    NSTimer *_alarmTimer;	// 8 = 0x8
    NSMutableArray *_alarmsToFire;	// 12 = 0xc
    unsigned int _readingPrefs:1;	// 16 = 0x10
    NSTimer *_countDownTimer;	// 20 = 0x14
    double _countDownTime;	// 24 = 0x18
    NSString *_countDownTimerSoundIdentifier;	// 32 = 0x20
    struct __CFDate *_alarmWakeupDate;	// 36 = 0x24
    struct __CFDate *_countdownWakeupDate;	// 40 = 0x28
}

+ (id)sharedAlarmController;	// IMP=0x0005ea70
- (void)_alarmChanged:(id)fp8;	// IMP=0x0005ed10
- (void)_alarmTimeReached:(id)fp8;	// IMP=0x0005f508
- (void)_countDownTimerFired:(id)fp8;	// IMP=0x0005f800
- (void)_readPreferences;	// IMP=0x0005eac0
- (void)_resetCountDownTime;	// IMP=0x0005ed90
- (void)_savePreferences;	// IMP=0x0005ebd4
- (void)_scheduleAlarms;	// IMP=0x0005f118
- (void)_sleepTimerFired:(id)fp8;	// IMP=0x0005f8c0
- (void)_wokeFromSleep;	// IMP=0x0005fa10
- (unsigned int)addAlarm:(id)fp8;	// IMP=0x0005f014
- (id)alarms;	// IMP=0x0005f110
- (double)countDownTime;	// IMP=0x0005f9fc
- (id)countDownTimerSoundIdentifier;	// IMP=0x0005fa08
- (void)dealloc;	// IMP=0x0005ef20
- (id)init;	// IMP=0x0005edc8
- (void)removeAlarmAtIndex:(unsigned int)fp8;	// IMP=0x0005f0c4
- (void)setCountDownTime:(double)fp8 withSoundIdentifier:(id)fp16;	// IMP=0x0005f5b4

@end

