/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (CTHelpers)
- (id)callBarringFacility;	// IMP=0x0005b6cc
- (id)callClass;	// IMP=0x0005b234
- (id)callForwardingReason;	// IMP=0x0005b4c8
- (id)callingLineIDRestrictionValue;	// IMP=0x0005b9a8
- (id)callingLinePresentationValue;	// IMP=0x0005bb94
- (id)connectedLineIDRestrictionValue;	// IMP=0x0005bd08
- (id)connectedLinePresentationValue;	// IMP=0x0005be34
- (id)enabledString;	// IMP=0x0005bfa8
- (id)mmiProcedure;	// IMP=0x0005c20c
- (id)serviceCenterAddress;	// IMP=0x0005c078
- (struct __CFString *)settingType;	// IMP=0x0005c3c8
- (id)ssServiceType;	// IMP=0x0005c0fc
@end

