/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (id)pop;	// IMP=0x0003d748
- (id)popObject:(id)fp8;	// IMP=0x0003d7d0
- (void)push:(id)fp8;	// IMP=0x0003d6dc
- (id)top;	// IMP=0x0003d844
@end

