/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (PrefsNotifications)
- (id)_alertStringForPref:(id)fp8;	// IMP=0x0005cd64
- (id)_callBarringString:(id)fp8;	// IMP=0x0005c6c8
- (id)_callForwardingString:(id)fp8;	// IMP=0x0005c464
- (id)_callWaitingString:(id)fp8;	// IMP=0x0005c600
- (id)_callingLineIDRestrictionString:(id)fp8;	// IMP=0x0005cab4
- (id)_callingLinePresentationString:(id)fp8;	// IMP=0x0005c95c
- (id)_connectedLineIDRestrictionString:(id)fp8;	// IMP=0x0005ca08
- (id)_connectedLinePresentationString:(id)fp8;	// IMP=0x0005c8b0
- (id)_fixedDialingString:(id)fp8;	// IMP=0x0005c7ac
- (id)_serviceCenterAddressString:(id)fp8;	// IMP=0x0005cc0c
- (id)_simLockString:(id)fp8;	// IMP=0x0005cb60
- (id)_ssPasswordString:(id)fp8;	// IMP=0x0005ccb8
- (void)addPrefNotification:(id)fp8 withUserInfo:(id)fp12;	// IMP=0x0005c3f4
- (id)prefsNotificationsAlertString;	// IMP=0x0005d1b0
@end

