/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class NSMutableArray, NSMutableDictionary, SBAlertDisplay, UIView;

@interface SBAlertWindow : UIWindow
{
    UIView *_contentLayer;	// 72 = 0x48
    unsigned int _isAnimating:1;	// 76 = 0x4c
    unsigned int _isInvalid:1;	// 76 = 0x4c
    unsigned int _handlerActive:1;	// 76 = 0x4c
    float _finalAlpha;	// 80 = 0x50
    SBAlertDisplay *_currentDisplay;	// 84 = 0x54
    NSMutableArray *_stackedAlertDisplays;	// 88 = 0x58
    NSMutableDictionary *_alertToDisplayMap;	// 92 = 0x5c
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0001b4a8
- (void)_backgroundFadedIn;	// IMP=0x0001b5e8
- (void)alertDisplayWillDismiss;	// IMP=0x0001bc3c
- (id)currentDisplay;	// IMP=0x0001bc94
- (BOOL)deactivateAlert:(id)fp8;	// IMP=0x0001baa8
- (void)dealloc;	// IMP=0x0001b610
- (void)dismissWindow:(id)fp8;	// IMP=0x0001bc28
- (void)displayAlert:(id)fp8;	// IMP=0x0001b734
- (int)displayCount;	// IMP=0x0001bc08
- (BOOL)handlerAlreadyActive;	// IMP=0x0001bcb4
- (id)initWithContentRect:(struct CGRect)fp8;	// IMP=0x0001b4cc
- (BOOL)isOpaque;	// IMP=0x0001b6a8
- (void)popInCurrentDisplay;	// IMP=0x0001bc40
- (void)setHandlerAlreadyActive:(BOOL)fp8;	// IMP=0x0001bc9c
- (id)stackedDisplayForAlert:(id)fp8;	// IMP=0x0001b6b0

@end

