/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIKeyboard, UINavigationBar, UIScroller, UITextField;

@interface SBAlertInputView : SBSlidingAlertDisplay
{
    UITextField *_inputTextField;	// 76 = 0x4c
    UIKeyboard *_keyboard;	// 80 = 0x50
    SBTextDisplayView *_textDisplay;	// 84 = 0x54
    UIScroller *_scroller;	// 88 = 0x58
    UINavigationBar *_bar;	// 92 = 0x5c
    BOOL _digitsOnly;	// 96 = 0x60
    id _delegate;	// 100 = 0x64
    int _minLength;	// 104 = 0x68
    int _maxLength;	// 108 = 0x6c
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x000579c4
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00057460
- (void)_sendClicked:(id)fp8;	// IMP=0x000578f8
- (void)_setInputTextField:(id)fp8;	// IMP=0x000576f4
- (void)_setKeyboard:(id)fp8;	// IMP=0x00057750
- (void)_setNavigationBar:(id)fp8;	// IMP=0x000576ac
- (void)alertDisplayWillBecomeVisible;	// IMP=0x000573e4
- (void)dealloc;	// IMP=0x00056ff4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00057078
- (void)sbAlertInputViewCancelClicked:(id)fp8;	// IMP=0x000578d0
- (void)sbAlertInputViewSendClicked:(id)fp8;	// IMP=0x000578b0
- (void)setDelegate:(id)fp8;	// IMP=0x00056fec
- (void)setDigitsOnly:(BOOL)fp8;	// IMP=0x0005786c
- (void)setMaxLength:(int)fp8;	// IMP=0x00057458
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00057350
- (void)setMinLength:(int)fp8;	// IMP=0x00057450
- (void)setText:(id)fp8;	// IMP=0x000573ac
- (BOOL)showsDesktopImage;	// IMP=0x00057348
- (id)textField;	// IMP=0x000578f0
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;	// IMP=0x00057798

@end

