/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class UIAlertSheet;

@interface SBAlertItem : NSObject
{
    UIAlertSheet *_alertSheet;	// 4 = 0x4
    BOOL _disallowUnlockAction;	// 8 = 0x8
    BOOL _orderOverSBAlert;	// 9 = 0x9
}

- (id)alertSheet;	// IMP=0x000652d0
- (BOOL)allowMenuButtonDismissal;	// IMP=0x00065424
- (double)autoDismissInterval;	// IMP=0x000654b0
- (id)awayItem;	// IMP=0x000655c4
- (void)cleanPreviousConfiguration;	// IMP=0x00065454
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00065498
- (void)dealloc;	// IMP=0x000653b8
- (void)didActivate;	// IMP=0x000655b8
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x000655c0
- (BOOL)disallowsUnlockAction;	// IMP=0x000654c4
- (BOOL)dismissOnLock;	// IMP=0x00065444
- (id)lockLabel;	// IMP=0x0006549c
- (float)lockLabelFontSize;	// IMP=0x000654a4
- (void)performUnlockAction;	// IMP=0x00065588
- (void)setDisallowsUnlockAction:(BOOL)fp8;	// IMP=0x000654bc
- (void)setOrderOverSBAlert:(BOOL)fp8;	// IMP=0x0006558c
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00065434
- (BOOL)shouldShowInLockScreen;	// IMP=0x0006542c
- (BOOL)undimsScreen;	// IMP=0x0006543c
- (void)willActivate;	// IMP=0x000655b4
- (void)willDeactivate:(BOOL)fp8;	// IMP=0x000655bc
- (BOOL)willShowInAwayItems;	// IMP=0x0006544c

@end

