/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface SBAlertItemsController : NSObject
{
    NSMutableArray *_lockedAlertItems;	// 4 = 0x4
    NSMutableArray *_unlockedAlertItems;	// 8 = 0x8
    NSTimer *_autoDismissTimer;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x000655cc
- (void)_deactivateAlertItem:(id)fp8 forLock:(BOOL)fp12;	// IMP=0x00065c20
- (void)activateAlertItem:(id)fp8;	// IMP=0x0006599c
- (void)autoDismissAlertItem:(id)fp8;	// IMP=0x00065db4
- (void)convertAnimatingUnlockedAlertsToLockedAlerts;	// IMP=0x0006570c
- (BOOL)deactivateAlertForMenuClick;	// IMP=0x00065ea4
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00065d94
- (void)deactivateAlertItemsForLock;	// IMP=0x00065f28
- (void)deactivateAllAlertItems;	// IMP=0x00065808
- (void)dealloc;	// IMP=0x000656ac
- (id)init;	// IMP=0x0006561c
- (BOOL)isShowingAlerts;	// IMP=0x00065df4
- (void)resetAutoDismissTimer;	// IMP=0x000658a8
- (id)visibleAlertItem;	// IMP=0x00065e3c

@end

