/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSDate, NSDictionary, NSMutableArray, NSTimeZone, NSTimer, SBAlertItem, SBAwayItem, SBAwayModel, SBAwayView, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;	// 48 = 0x30
    SBAwayModel *_model;	// 52 = 0x34
    SBAwayView *_awayView;	// 56 = 0x38
    NSTimer *_dimTimer;	// 60 = 0x3c
    NSDate *_lockDate;	// 64 = 0x40
    SBAwayItem *_clickedItem;	// 68 = 0x44
    unsigned int _isLocked:1;	// 72 = 0x48
    unsigned int _isDimmed:1;	// 72 = 0x48
    unsigned int _isDimming:1;	// 72 = 0x48
    unsigned int _orderedOutDimmed:1;	// 72 = 0x48
    unsigned int _frontDimmed:1;	// 72 = 0x48
    unsigned int _isBlocked:1;	// 72 = 0x48
    unsigned int _makingEmergencyCall:1;	// 72 = 0x48
    unsigned int _appRequestedPasscodeEntry:1;	// 72 = 0x48
    unsigned int _needToMakeEmergencyCall:1;	// 73 = 0x49
    unsigned int _isSyncing:1;	// 73 = 0x49
    unsigned int _relockAfterUnlock:1;	// 73 = 0x49
    unsigned int _wasLockedBeforeSync:1;	// 73 = 0x49
    unsigned int _wasDeviceLockedBeforeSync:1;	// 73 = 0x49
    NSDictionary *_nowPlayingInfo;	// 76 = 0x4c
    double _sleepDelay;	// 80 = 0x50
    SBSlidingAlertDisplay *_deviceUnlockDisplay;	// 88 = 0x58
    double _deviceLockBlockTime;	// 92 = 0x5c
    double _deviceLockGracePeriodEndTimeInterval;	// 100 = 0x64
    NSTimeZone *_deviceLockGraceTimeZone;	// 108 = 0x6c
    NSMutableArray *_pendingAlertItems;	// 112 = 0x70
    SBAlertItem *_currentAlertItem;	// 116 = 0x74
    int _notifyLockStateToken;	// 120 = 0x78
}

+ (void)registerForAlerts;	// IMP=0x00022488
+ (id)sharedAwayController;	// IMP=0x000223b8
- (void)_activateEmergencyCall;	// IMP=0x000256b8
- (void)_clearBlockedState;	// IMP=0x000234f8
- (BOOL)_disableShowingMediaControls;	// IMP=0x000260bc
- (void)_finishedUnlockAttemptWithStatus:(BOOL)fp8;	// IMP=0x00024258
- (void)_frontForSuspendedLockAfterDelay;	// IMP=0x00023b74
- (void)_resetGracePeriod;	// IMP=0x00022ee4
- (void)_sendLockStateChangedNotification;	// IMP=0x00022a00
- (void)_setupDeviceLockGracePeriod;	// IMP=0x00022fd4
- (void)_timeChanged;	// IMP=0x00022f6c
- (void)_undimScreen;	// IMP=0x00024dc0
- (void)_unlockWithSound:(BOOL)fp8;	// IMP=0x00022b28
- (void)activate;	// IMP=0x00024ec0
- (BOOL)activateAlertItem:(id)fp8;	// IMP=0x00025be0
- (void)activationChanged:(id)fp8;	// IMP=0x00023140
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00022610
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0002262c
- (struct CGRect)alertWindowRect;	// IMP=0x0002248c
- (BOOL)allowsInCallStatusBar;	// IMP=0x000251c4
- (BOOL)allowsStackingOfAlert:(id)fp8;	// IMP=0x00025178
- (double)animateInDuration;	// IMP=0x00022898
- (BOOL)animatesDismissal;	// IMP=0x00025288
- (void)animator:(id)fp8 stopAnimation:(id)fp12;	// IMP=0x000254e0
- (void)applicationDidFinishLaunching:(id)fp8;	// IMP=0x0002243c
- (void)applicationRequestedDeviceUnlock;	// IMP=0x00023458
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 alertDisplay:(id)fp12;	// IMP=0x00024288
- (BOOL)attemptSnoozeRingingAlertItem;	// IMP=0x000259bc
- (void)attemptUnlock;	// IMP=0x000241ac
- (id)awayModel;	// IMP=0x00022434
- (id)awayView;	// IMP=0x000224fc
- (void)cancelApplicationRequestedDeviceLockEntry;	// IMP=0x000234c0
- (void)cancelDimTimer;	// IMP=0x000246dc
- (void)clensePendingQueueOfAwayItems;	// IMP=0x0002492c
- (void)clickItem:(id)fp8;	// IMP=0x00025598
- (id)currentAlertItem;	// IMP=0x0002586c
- (BOOL)deactivate;	// IMP=0x00024ff8
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00025ecc
- (void)dealloc;	// IMP=0x00022694
- (void)delaySleepByNumberOfSeconds:(float)fp8;	// IMP=0x00024bf8
- (void)didAnimateLockKeypadIn;	// IMP=0x000257dc
- (void)didAnimateLockKeypadOut;	// IMP=0x000257e0
- (void)didFinishAnimatingOut;	// IMP=0x00025464
- (void)dimScreen:(BOOL)fp8;	// IMP=0x00024c8c
- (void)emergencyCallWasDisplayed;	// IMP=0x00025728
- (void)emergencyCallWasRemoved;	// IMP=0x000257a0
- (float)finalAlpha;	// IMP=0x000224ec
- (void)frontForSuspendedLockAfterDelay:(float)fp8;	// IMP=0x00023ba4
- (void)frontLocked:(BOOL)fp8 animate:(BOOL)fp12 automatically:(BOOL)fp16;	// IMP=0x00023c84
- (void)frontLockedAnimationFinished;	// IMP=0x00023b54
- (void)handleClickedItem:(id)fp8;	// IMP=0x0002276c
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;	// IMP=0x000255fc
- (void)hideMediaControls;	// IMP=0x0002609c
- (id)initWithUIController:(id)fp8;	// IMP=0x00022148
- (BOOL)isAttemptingUnlock;	// IMP=0x00024240
- (BOOL)isBlocked;	// IMP=0x000235b4
- (BOOL)isCurrentAlertItemRinging;	// IMP=0x00025938
- (BOOL)isDeviceLocked;	// IMP=0x00023160
- (BOOL)isDimmed;	// IMP=0x00024828
- (BOOL)isLocked;	// IMP=0x00023acc
- (BOOL)isMakingEmergencyCall;	// IMP=0x000257cc
- (BOOL)isPasswordProtected;	// IMP=0x000230b4
- (BOOL)isPermanentlyBlocked:(double *)fp8;	// IMP=0x00023648
- (BOOL)isShowingMediaControls;	// IMP=0x00026078
- (BOOL)isSyncing;	// IMP=0x000239b0
- (void)lock;	// IMP=0x00022a5c
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00023ad8
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00023afc
- (void)makeEmergencyCall;	// IMP=0x0002564c
- (BOOL)moveAlertItemToAwayView:(id)fp8;	// IMP=0x000248e0
- (void)noteResetRestoreStateChanged;	// IMP=0x000239c0
- (void)noteSyncStateChanged;	// IMP=0x000236d0
- (void)orderOut;	// IMP=0x000252b4
- (void)pendOrDeactivateCurrentAlertItem;	// IMP=0x00025874
- (void)playLockSound;	// IMP=0x000229e8
- (void)preventIdleSleep;	// IMP=0x000245fc
- (void)reactivatePendingAlertItems;	// IMP=0x000228a4
- (void)relock;	// IMP=0x00024a88
- (void)relockDimmed:(BOOL)fp8;	// IMP=0x00024b2c
- (void)resetAwayItems;	// IMP=0x00023b1c
- (void)restartDimTimer:(float)fp8;	// IMP=0x00024738
- (void)setDeviceLocked:(BOOL)fp8;	// IMP=0x000232e0
- (BOOL)shouldAnimateOthersSuspension;	// IMP=0x00023be8
- (void)sleep;	// IMP=0x000245c0
- (double)sleepDelay;	// IMP=0x00024b5c
- (void)snoozeOrStopRingingAlertItem;	// IMP=0x00025ae8
- (int)statusBarMode;	// IMP=0x000251cc
- (void)stopRingingAlertItem;	// IMP=0x00025a58
- (BOOL)toggleMediaControls;	// IMP=0x0002614c
- (void)toggleShowsIMEIandICCID:(id)fp8;	// IMP=0x000261d0
- (BOOL)trySnoozingAlarmAlertItem;	// IMP=0x00025b24
- (void)undimScreen;	// IMP=0x00024df0
- (BOOL)undimsDisplay;	// IMP=0x000224f4
- (void)unlockWithSound:(BOOL)fp8;	// IMP=0x00022c54
- (void)unlockWithSound:(BOOL)fp8 alertDisplay:(id)fp12;	// IMP=0x00022ca8
- (void)updateClockFormat;	// IMP=0x0002561c
- (void)updateInCallUI;	// IMP=0x00026034
- (void)updateNowPlayingInfo:(id)fp8;	// IMP=0x0002559c
- (void)wake;	// IMP=0x0002461c
- (BOOL)wantsToHandleAlert:(id)fp8;	// IMP=0x00025e5c

@end

