/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBBluetoothController : NSObject
{
    NSMutableArray *_devices;	// 4 = 0x4
}

+ (id)sharedInstance;	// IMP=0x000801f4
- (void)addDeviceNotification:(id)fp8;	// IMP=0x00080718
- (void)batteryChanged:(id)fp8;	// IMP=0x00080894
- (float)batteryLevel;	// IMP=0x00080398
- (BOOL)canReportBatteryLevel;	// IMP=0x00080330
- (void)connectionChanged:(id)fp8;	// IMP=0x000807e4
- (void)dealloc;	// IMP=0x00080244
- (id)firstBTDeviceToReportBatteryLevel;	// IMP=0x00080294
- (void)iapDeviceChanged:(id)fp8;	// IMP=0x000806fc
- (void)noteDevicesChanged;	// IMP=0x0008044c
- (void)removeDeviceNotification:(id)fp8;	// IMP=0x00080790
- (void)startWatchingForDevices;	// IMP=0x00080494
- (void)stopWatchingForDevices;	// IMP=0x000806a0

@end

