/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCalendarAlertItem : SBAlertItem
{
    double _date;	// 12 = 0xc
    NSString *_title;	// 20 = 0x14
    NSString *_location;	// 24 = 0x18
    int _eventId;	// 28 = 0x1c
    BOOL _isAllDay;	// 32 = 0x20
}

+ (void)adjustOnWake;	// IMP=0x00069768
+ (void)alarmsDidFire:(id)fp8;	// IMP=0x0006921c
+ (void)alarmsDidSchedule:(id)fp8;	// IMP=0x000695a8
+ (void)didWakeFromSleep;	// IMP=0x00069728
+ (void)finishRegisteringForAlerts;	// IMP=0x00069128
+ (void)registerForAlerts;	// IMP=0x0006a3e8
+ (void)significantTimeChange;	// IMP=0x0006a4d8
- (id)_dateString:(BOOL)fp8;	// IMP=0x000698b8
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006a1ac
- (id)awayItem;	// IMP=0x0006a294
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00069df0
- (void)dealloc;	// IMP=0x00069814
- (void)didPresentAlertSheet:(id)fp8;	// IMP=0x0006a058
- (id)initWithDate:(double)fp8 title:(id)fp16 location:(id)fp20 eventId:(int)fp24 isAllDay:(BOOL)fp28;	// IMP=0x0006977c
- (id)lockLabel;	// IMP=0x00069ffc
- (void)performUnlockAction;	// IMP=0x0006a234
- (void)revealEvent;	// IMP=0x0006a0ec
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x0006a284
- (BOOL)willShowInAwayItems;	// IMP=0x0006a28c

@end

