/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@interface SBCountDownAlertItem : SBRingingAlertItem
{
}

- (id)avAudioCategory;	// IMP=0x0006d014
- (id)avClientName;	// IMP=0x0006d008
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006ce88
- (id)lockLabel;	// IMP=0x0006ce2c
- (id)soundIdentifier;	// IMP=0x0006cfd0

@end

