/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x00077190
- (float)delayForOthersActivation;	// IMP=0x000772a4
- (void)deviceUnlockCanceled;	// IMP=0x00077148
- (void)deviceUnlockSucceeded;	// IMP=0x00077100
- (void)dismiss;	// IMP=0x00077248
- (float)durationForOthersActivation;	// IMP=0x000772ac
- (void)useEmergencyCallButton;	// IMP=0x000770fc

@end

