/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBDisplayStack : NSObject
{
    NSMutableArray *_displayStack;	// 4 = 0x4
    void *_pushCallback;	// 8 = 0x8
    void *_popCallback;	// 12 = 0xc
}

- (void)_setDisplayStack:(id)fp8;	// IMP=0x0003b5d8
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x0003b620
- (void)dealloc;	// IMP=0x0003b6a8
- (id)description;	// IMP=0x0003ba70
- (id)displays;	// IMP=0x0003b908
- (void)flushWithoutCallbackSparingDisplay:(id)fp8;	// IMP=0x0003b7c8
- (id)init;	// IMP=0x0003b568
- (BOOL)isEmpty;	// IMP=0x0003b718
- (id)pop;	// IMP=0x0003b784
- (id)popDisplay:(id)fp8;	// IMP=0x0003b8a0
- (void)pushDisplay:(id)fp8;	// IMP=0x0003b740
- (void)setPopCallBack:(void *)fp8;	// IMP=0x0003b710
- (void)setPushCallBack:(void *)fp8;	// IMP=0x0003b708
- (id)topAlert;	// IMP=0x0003b9d0
- (id)topApplication;	// IMP=0x0003b930
- (id)topDisplay;	// IMP=0x0003b910

@end

