/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBEdgeActivationAlertItem : SBAlertItem
{
    int _error;	// 12 = 0xc
    NSString *_reason;	// 16 = 0x10
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00076bc4
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00076be0
- (void)dealloc;	// IMP=0x00076b30
- (void)dismiss;	// IMP=0x00076b84
- (id)initWithErrorCode:(int)fp8 reason:(id)fp12;	// IMP=0x00076ac4

@end

