/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPushButton.h"

@class NSString;

@interface SBEmergencyCallButton : UIPushButton
{
    NSString *_subtitle;	// 84 = 0x54
}

+ (struct __GSFont *)defaultFont;	// IMP=0x00064cc0
- (void)dealloc;	// IMP=0x00064d38
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x000650dc
- (void)drawTitleInRect:(struct CGRect)fp8;	// IMP=0x00064fa0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00064cd4
- (void)setSubtitle:(id)fp8;	// IMP=0x00064d8c
- (id)styleStringForColor:(struct CGColor *)fp8;	// IMP=0x00064dd4

@end

