/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIScroller.h"

@class UIView;

@interface SBIconScroller : UIScroller
{
    UIView *_lastHilightView;	// 328 = 0x148
}

- (void)highlightView:(id)fp8 state:(BOOL)fp12;	// IMP=0x0007c738
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0007c788

@end

