/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, SBApplicationIcon;

@interface SBIconModel : NSObject
{
    SBApplicationIcon *_pendingIcon;	// 4 = 0x4
    SBApplicationIcon *_lastClickedIcon;	// 8 = 0x8
    double _lastClickedTime;	// 12 = 0xc
    NSMutableDictionary *_allAppIcons;	// 20 = 0x14
    NSMutableArray *_displayedIcons;	// 24 = 0x18
    NSMutableDictionary *_accessoryIcons;	// 28 = 0x1c
    NSMutableArray *_buttonBarIcons;	// 32 = 0x20
    NSMutableArray *_hiddenIconTags;	// 36 = 0x24
    NSMutableArray *_visibleIconTags;	// 40 = 0x28
    NSMutableArray *_duplicateIcons;	// 44 = 0x2c
    NSMutableDictionary *_displayDefinitions;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x0007dfd8
- (void)_addItemsToIconList:(id)fp8 fromPath:(id)fp12 withTags:(id)fp16;	// IMP=0x0007e6ec
- (id)_rolesForInfoPlist:(id)fp8;	// IMP=0x0007e468
- (id)_rolesForRoleDefinitions:(id)fp8;	// IMP=0x0007e394
- (BOOL)_shouldShowIcon:(id)fp8;	// IMP=0x0007e2bc
- (void)_updateSchemesForRoleDefinition:(id)fp8 displayIdentifier:(id)fp12;	// IMP=0x0007e5fc
- (id)allDisplayedIcons;	// IMP=0x0007f650
- (void)attemptPendingLaunch;	// IMP=0x0007f8f8
- (id)buttonBarIcons;	// IMP=0x0007f648
- (void)changeVisibilityOfIconsWithVisibleTags:(id)fp8 hiddenTags:(id)fp12;	// IMP=0x0007e1e0
- (void)clickedIcon:(id)fp8;	// IMP=0x0007f78c
- (void)dealloc;	// IMP=0x0007e138
- (id)displayNameForRoleDefinition:(id)fp8 inBundle:(id)fp12;	// IMP=0x0007e504
- (id)displayOrder;	// IMP=0x0007ef9c
- (void)doubleClickedIcon:(id)fp8;	// IMP=0x0007f698
- (BOOL)hasLaunchPending;	// IMP=0x0007f9f8
- (void)hideIcon:(id)fp8;	// IMP=0x0007f628
- (id)iconForDisplayIdentifier:(id)fp8;	// IMP=0x0007f658
- (void)iconVisibilityChanged;	// IMP=0x0007f198
- (id)init;	// IMP=0x0007e028
- (void)launchIcon:(id)fp8;	// IMP=0x0007f6e4
- (void)loadAccessoryIcons;	// IMP=0x0007eed0
- (void)loadAllIcons;	// IMP=0x0007f45c
- (void)loadSectionDefinitions:(id)fp8 sectionIcons:(id)fp12 allIcons:(id)fp16;	// IMP=0x0007eff8
- (void)pendLaunchOfIcon:(id)fp8;	// IMP=0x0007fa08
- (void)showIcon:(id)fp8;	// IMP=0x0007f608

@end

