/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray;

@interface SBIconList : UIView
{
    NSMutableArray *_iconMatrix;	// 28 = 0x1c
    unsigned int _scattered:1;	// 32 = 0x20
    unsigned int _needsLayout:1;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0004c094
- (void)clickedIcon:(id)fp8;	// IMP=0x0004d2d4
- (BOOL)containsIcon:(id)fp8;	// IMP=0x0004c8d0
- (void)dealloc;	// IMP=0x0004c1d4
- (BOOL)firstFreeSlotX:(int *)fp8 Y:(int *)fp12;	// IMP=0x0004c2a4
- (BOOL)getX:(int *)fp8 Y:(int *)fp12 forIcon:(id)fp16;	// IMP=0x0004c82c
- (id)iconAtX:(int)fp8 Y:(int)fp12;	// IMP=0x0004c228
- (int)iconsInRow:(id)fp8;	// IMP=0x0004d42c
- (id)initWithDefaultSize;	// IMP=0x0004c0a4
- (void)insertIcon:(id)fp8 atX:(int)fp12 Y:(int)fp16 animate:(BOOL)fp20;	// IMP=0x0004c588
- (BOOL)isEmpty;	// IMP=0x0004c3cc
- (BOOL)isScattered;	// IMP=0x0004cc30
- (void)layoutIconsIfNeeded;	// IMP=0x0004d4d4
- (struct CGPoint)originForIcon:(id)fp8;	// IMP=0x0004d830
- (struct CGPoint)originForIconAtX:(int)fp8 Y:(int)fp12;	// IMP=0x0004d758
- (void)removeAllIcons;	// IMP=0x0004cae0
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0004ca28
- (void)removeIconAtX:(int)fp8 Y:(int)fp12 animate:(BOOL)fp16;	// IMP=0x0004c954
- (void)scatter:(BOOL)fp8;	// IMP=0x0004cc3c
- (void)setIconsNeedLayout;	// IMP=0x0004d41c
- (void)showIconAnimationDidStop:(id)fp8 didFinish:(id)fp12 icon:(id)fp16;	// IMP=0x0004c4c8
- (void)stopAnimations;	// IMP=0x0004d1b8
- (float)topIconPadding;	// IMP=0x0004d3e8
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;	// IMP=0x0004cf4c
- (float)verticalIconPadding;	// IMP=0x0004d314

@end

