/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, SBIconModel, TPLCDTextView, UIPageIndicator, UIScroller, UIView;

@interface SBIconController : NSObject
{
    NSMutableArray *_iconLists;	// 4 = 0x4
    SBIconModel *_iconModel;	// 8 = 0x8
    UIView *_contentView;	// 12 = 0xc
    UIScroller *_scroller;	// 16 = 0x10
    UIPageIndicator *_pageIndicator;	// 20 = 0x14
    int _currentIconListIndex;	// 24 = 0x18
    TPLCDTextView *_idleText;	// 28 = 0x1c
}

+ (id)sharedInstance;	// IMP=0x0007c7cc
- (id)addEmptyIconList;	// IMP=0x0007ce5c
- (void)addIconToFirstAvailableList:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16;	// IMP=0x0007d278
- (id)contentView;	// IMP=0x0007c938
- (id)currentIconList;	// IMP=0x0007cc70
- (void)dealloc;	// IMP=0x0007c894
- (BOOL)hasIdleModeText;	// IMP=0x0007d804
- (id)iconListContainingIcon:(id)fp8;	// IMP=0x0007cc94
- (id)iconLists;	// IMP=0x0007d3dc
- (float)idleModeTextHeight;	// IMP=0x0007d44c
- (void)idleTextDidAnimate:(id)fp8 finished:(id)fp12 toText:(id)fp16;	// IMP=0x0007d490
- (id)init;	// IMP=0x0007c81c
- (void)lcdTextViewCompletedScroll:(id)fp8;	// IMP=0x0007d410
- (int)maxIconColumns;	// IMP=0x0007dfd0
- (int)maxIconRows;	// IMP=0x0007dfc8
- (void)relayoutIcons;	// IMP=0x0007d0f0
- (void)removeAccessory:(id)fp8;	// IMP=0x0007df6c
- (void)removeEmptyIconList:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0007cf7c
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0007d3a0
- (void)scatter:(BOOL)fp8;	// IMP=0x0007dc7c
- (void)scrollToIconListAtIndex:(int)fp8 animate:(BOOL)fp12;	// IMP=0x0007cd1c
- (void)scrollerDidEndAnimatedScrolling:(id)fp8;	// IMP=0x0007decc
- (void)scrollerDidEndDragging:(id)fp8 willSmoothScroll:(BOOL)fp12;	// IMP=0x0007de94
- (void)scrollerDidEndSmoothScrolling:(id)fp8;	// IMP=0x0007deb0
- (void)setIdleModeText:(id)fp8;	// IMP=0x0007d83c
- (void)showAccessory:(id)fp8;	// IMP=0x0007dee8
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;	// IMP=0x0007dd58
- (void)updateContentSizeAndPageCount;	// IMP=0x0007cda4
- (void)updateCurrentIconListIndex;	// IMP=0x0007cbe0
- (void)updateNumberOfRowsWithDuration:(float)fp8;	// IMP=0x0007d500

@end

