/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBDismissOnlyAlertItem;

@interface SBLockdownManager : NSObject
{
    int _state;	// 4 = 0x4
    BOOL _settingUpActivationState;	// 8 = 0x8
    BOOL _isBricked;	// 9 = 0x9
    BOOL _hasShownWaitingAlertThisSession;	// 10 = 0xa
    BOOL _hasShownMismatchedSIM;	// 11 = 0xb
    SBDismissOnlyAlertItem *_activatingAlertItem;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x0007147c
- (void)_activationFailed;	// IMP=0x00071cd8
- (BOOL)_hasEverRegistered;	// IMP=0x00071618
- (BOOL)_isRegisteredToNetwork;	// IMP=0x0007177c
- (void)_postAlertsIfNeeded;	// IMP=0x000718e4
- (void)_resetActivationState;	// IMP=0x00071c60
- (void)_serviceAvailabilityChanged:(id)fp8;	// IMP=0x00071e60
- (void)_setCurrentAlertItem:(id)fp8;	// IMP=0x000717c4
- (void)_setHasEverRegistered:(BOOL)fp8;	// IMP=0x00071708
- (void)_setupActivationState;	// IMP=0x00071e7c
- (BOOL)_shouldShowTelephonyAlerts;	// IMP=0x00071890
- (BOOL)brickedDevice;	// IMP=0x00072078
- (void)dealloc;	// IMP=0x000720dc
- (id)init;	// IMP=0x000714e0
- (int)lockdownState;	// IMP=0x000720a8

@end

