/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageView.h"

@class UIImage;

@interface SBNowPlayingReflectionView : UIImageView
{
    UIImage *_image;	// 52 = 0x34
}

- (void)dealloc;	// IMP=0x0003af10
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0003b21c
- (void)setImage:(id)fp8;	// IMP=0x0003af64

@end

