/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class UIImage, UIImageView;

@interface SBPhoneApplicationIcon : SBApplicationIcon
{
    UIImageView *_blinkIcon;	// 80 = 0x50
    UIImage *_blinkOnIcon;	// 84 = 0x54
    unsigned int _isBlinking:1;	// 88 = 0x58
}

- (void)_activeCallStateChanged:(id)fp8;	// IMP=0x00047ad8
- (void)_startTimer;	// IMP=0x00047624
- (void)_stopTimer;	// IMP=0x000478b8
- (void)alertWindowHidden;	// IMP=0x00047988
- (void)dealloc;	// IMP=0x00047558
- (id)icon;	// IMP=0x000475c8
- (void)iconBecameVisible;	// IMP=0x00047908
- (void)iconWillBeHidden;	// IMP=0x00047948
- (id)initWithApplication:(id)fp8;	// IMP=0x000474e4
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x00047a0c
- (void)startBlinking;	// IMP=0x000479b8
- (void)stopBlinking;	// IMP=0x000479bc

@end

