/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SBPlatformController : NSObject
{
    NSString *_currentConfigurationName;	// 4 = 0x4
    NSMutableDictionary *_currentConfiguration;	// 8 = 0x8
    NSMutableDictionary *_currentCapabilities;	// 12 = 0xc
    void *_shmem;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00078fc0
- (id)allowedDisplayIdentifiers;	// IMP=0x00079294
- (void)dealloc;	// IMP=0x00079090
- (id)displayOrder;	// IMP=0x000791dc
- (BOOL)hasCapability:(id)fp8;	// IMP=0x000791b0
- (id)infoForCapability:(id)fp8;	// IMP=0x00079150
- (id)init;	// IMP=0x00079010
- (BOOL)matchesPlatforms:(id)fp8;	// IMP=0x0007920c
- (id)platformDisplayName;	// IMP=0x000794b8
- (id)platformName;	// IMP=0x000791d4
- (void)setInfo:(id)fp8 forCapability:(id)fp12;	// IMP=0x00079170
- (id)systemVersion;	// IMP=0x000790f0

@end

