/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPlatformController.h"

@interface SBPlatformController (private)
- (void)_addConfigurationNamed:(id)fp8 toCompositeDictionary:(id)fp12;	// IMP=0x000796dc
- (id)currentConfigurationName;	// IMP=0x00079540
- (void)discoverCurrentConfiguration;	// IMP=0x00079844
- (void)loadBundlesForCurrentConfiguration;	// IMP=0x00079a00
- (void)noteConfigurationChanged:(id)fp8;	// IMP=0x00079b18
- (void)postCurrentConfiguration;	// IMP=0x000795b8
- (void)runPrefUpdateToolIfNeeded;	// IMP=0x00079bb0
@end

