/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class NSTimer, SBPowerDownController, TPBottomButtonBar, TPTopLockBar, UIView;

@interface SBPowerDownView : SBAlertDisplay
{
    UIView *_dimView;	// 36 = 0x24
    TPTopLockBar *_lockView;	// 40 = 0x28
    TPBottomButtonBar *_cancelView;	// 44 = 0x2c
    SBPowerDownController *_powerDownController;	// 48 = 0x30
    NSTimer *_autoDismissTimer;	// 52 = 0x34
}

- (void)animateDark;	// IMP=0x0004661c
- (void)animateIn;	// IMP=0x00046200
- (void)animateOut;	// IMP=0x00046434
- (void)cancel:(id)fp8;	// IMP=0x000460c4
- (void)cancelAutoDismissTimer;	// IMP=0x00046000
- (void)dealloc;	// IMP=0x00045f84
- (void)finishedAnimatingIn;	// IMP=0x0004618c
- (void)finishedAnimatingOut;	// IMP=0x000461c4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00045b34
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x0004612c
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00046148
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x000460f8
- (void)notifyDelegateOfPowerDown;	// IMP=0x000461e0
- (void)powerDown:(id)fp8;	// IMP=0x00046164
- (void)resetAutoDismissTimer;	// IMP=0x00046040
- (void)setPowerDownController:(id)fp8;	// IMP=0x00046184

@end

