/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert
{
    int _count;	// 48 = 0x30
    id _delegate;	// 52 = 0x34
    SBPowerDownView *_powerDownView;	// 56 = 0x38
    BOOL _isFront;	// 60 = 0x3c
}

+ (id)sharedInstance;	// IMP=0x0004584c
- (void)activate;	// IMP=0x00045a10
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00045ac4
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00045ae0
- (float)autoLockTime;	// IMP=0x000458f0
- (void)cancel;	// IMP=0x00045b10
- (BOOL)deactivate;	// IMP=0x00045a7c
- (void)dealloc;	// IMP=0x0004589c
- (BOOL)isOrderedFront;	// IMP=0x000458fc
- (void)orderFront;	// IMP=0x00045904
- (void)orderOut;	// IMP=0x00045914
- (void)powerDown;	// IMP=0x00045aec
- (id)powerDownView;	// IMP=0x00045934
- (void)setDelegate:(id)fp8;	// IMP=0x00045ae4

@end

