/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject
{
    BOOL _isInitialUpdate;	// 4 = 0x4
    int _status;	// 8 = 0x8
    SBSIMLockAlertItem *_currentAlert;	// 12 = 0xc
    SBSIMLockEntryAlert *_lockEntryAlert;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00067014
- (int)_CTToSBSIMStatus:(struct __CFString *)fp8;	// IMP=0x00067140
- (BOOL)_hopelesslyPUKLocked;	// IMP=0x00067118
- (void)_initialUpdate;	// IMP=0x00067a28
- (int)_statusFromCT;	// IMP=0x000672b8
- (void)_tearDownAlertAndUpdateStatus;	// IMP=0x000676fc
- (void)_tryToUpdateStatus;	// IMP=0x00067680
- (void)_updateSIMStatus:(struct __CFString *)fp8 withOptions:(struct __CFDictionary *)fp12;	// IMP=0x0006777c
- (void)_updateToStatus:(int)fp8;	// IMP=0x0006742c
- (void)alertItemDismissed:(id)fp8;	// IMP=0x00067318
- (void)attemptUnlock;	// IMP=0x000673dc
- (void)dealloc;	// IMP=0x00067064
- (void)lockEntryAlertDismissed:(id)fp8;	// IMP=0x000672e4
- (int)pinLockAttemptsRemaining;	// IMP=0x000678ec
- (int)pukLockAttemptsRemaining;	// IMP=0x000678fc
- (void)registerForAlerts;	// IMP=0x00067a74
- (void)repopAlert;	// IMP=0x0006734c
- (int)status;	// IMP=0x00067ba4

@end

