/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBSIMLockAlertItem : SBAlertItem
{
    int _status;	// 12 = 0xc
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00067f3c
- (id)alertText;	// IMP=0x00067d34
- (id)alertTitle;	// IMP=0x00067bc4
- (BOOL)canUnlock;	// IMP=0x00067bac
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00067ff4
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x00067e74
- (void)dismiss;	// IMP=0x00067eb4
- (id)lockLabel;	// IMP=0x00068268
- (void)performUnlockAction;	// IMP=0x00067f94
- (int)status;	// IMP=0x00067e6c
- (void)unlock;	// IMP=0x00067ef4

@end

