/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitAlert.h"

@interface SBSIMToolkitAlert (PhoneAlert)
- (struct __CFString *)callPriority;	// IMP=0x00053c20
- (struct __CFString *)displayTextPriority;	// IMP=0x00053c5c
- (id)inCallText;	// IMP=0x00053d24
- (id)phoneNumber;	// IMP=0x00053ce8
- (BOOL)shouldRedial;	// IMP=0x00053c98
@end

