/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBSIMLockEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (id)_pinAttemptsRemainingLabel;	// IMP=0x00068554
- (void)_unlock:(id)fp8;	// IMP=0x00068e38
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00068c60
- (id)failureLabel;	// IMP=0x00068814
- (id)failureTitle;	// IMP=0x00068754
- (id)label;	// IMP=0x00068a1c
- (void)passcodeFieldDidAcceptEntry:(id)fp8;	// IMP=0x0006910c
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;	// IMP=0x00068f44
- (void)setupCurrentLockAttemptState;	// IMP=0x00068ba4
- (void)setupFailureState;	// IMP=0x00068884
- (void)setupSuccess;	// IMP=0x00068d5c
- (void)setupUnlockAttemptState;	// IMP=0x00068654
- (id)titleText;	// IMP=0x0006895c
- (void)unlock;	// IMP=0x00068e88

@end

