/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSArray, UITable;

@interface SBSIMToolkitListDisplay : SBSlidingAlertDisplay
{
    UITable *_table;	// 76 = 0x4c
    NSArray *_items;	// 80 = 0x50
}

+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00055db4
- (void)_selectListItem:(unsigned long)fp8;	// IMP=0x00054fd4
- (id)_simToolkitListItems;	// IMP=0x00054f1c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x000553c8
- (void)dealloc;	// IMP=0x00054ebc
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00055080
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00055580
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x00055604
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x0005536c
- (BOOL)showsDesktopImage;	// IMP=0x00055364
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x00055630
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x00055838

@end

