/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitTextAlertDisplay.h"

@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00055fac
- (id)_activeCalls;	// IMP=0x00055910
- (id)alertText;	// IMP=0x00055c5c
- (void)dial:(id)fp8;	// IMP=0x00055934
- (void)dismiss:(id)fp8;	// IMP=0x000558bc

@end

