/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBSIMToolkitAlert : SBAlert
{
    BOOL _needsResponse;	// 48 = 0x30
    NSTimer *_timeoutTimer;	// 52 = 0x34
}

+ (void)_idleScreenShown:(id)fp8;	// IMP=0x000534cc
+ (void)_restartMonitor;	// IMP=0x0005388c
+ (void)_startSTKMonitor;	// IMP=0x000535e8
+ (void)_stopSTKMonitor;	// IMP=0x00053544
+ (id)currentAlert;	// IMP=0x000530ec
+ (void)dismissCurrentAlert;	// IMP=0x000530fc
+ (void)registerForAlerts;	// IMP=0x000538c0
+ (void)setCurrentAlert:(id)fp8;	// IMP=0x000530a0
+ (struct __CTServerConnection *)simToolkitServerConnection;	// IMP=0x00052420
+ (void)test;	// IMP=0x00053388
+ (void)userEventOccurred;	// IMP=0x00052440
+ (BOOL)wantsNextUserEvent;	// IMP=0x00052430
- (BOOL)_delayEnabled;	// IMP=0x000539c8
- (void)_playTone:(struct __CFString *)fp8 forDuration:(float)fp12;	// IMP=0x0005289c
- (void)_stopTone:(id)fp8;	// IMP=0x00052628
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0005318c
- (BOOL)allowsEventOnlySuspension;	// IMP=0x00052758
- (void)clearTimeoutTimer;	// IMP=0x00053988
- (BOOL)deactivate;	// IMP=0x00052760
- (void)dealloc;	// IMP=0x00052708
- (void)displayDidTimeout;	// IMP=0x00053b94
- (BOOL)needsResponse;	// IMP=0x0005248c
- (void)restartTimeoutTimer:(float)fp8;	// IMP=0x00053a20
- (void)sendResponse:(struct __CFString *)fp8;	// IMP=0x000525ac
- (void)sendResponse:(struct __CFString *)fp8 withBool:(BOOL)fp12;	// IMP=0x00052520
- (void)sendResponse:(struct __CFString *)fp8 withString:(id)fp12;	// IMP=0x00052494
- (BOOL)sendResponseUponDisplay;	// IMP=0x000526b0
- (void)setNeedsResponse:(BOOL)fp8;	// IMP=0x00052484
- (void)startTimeoutTimerIfNecessary;	// IMP=0x00053ab0
- (struct __CFString *)toolkitAlertType;	// IMP=0x00053168

@end

