/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIScroller;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay
{
    SBTextDisplayView *_contentView;	// 76 = 0x4c
    UIScroller *_scroller;	// 80 = 0x50
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00056588
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00053d98
- (void)accept:(id)fp8;	// IMP=0x0005460c
- (void)adjustScrollerFrame;	// IMP=0x00054078
- (void)alertDisplayWillBecomeVisible;	// IMP=0x000544ec
- (id)alertText;	// IMP=0x000544a4
- (void)dealloc;	// IMP=0x00053f98
- (void)dismiss;	// IMP=0x000546f4
- (void)dismiss:(id)fp8;	// IMP=0x00054680
- (void)displayDidTimeout;	// IMP=0x00054450
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000541b4
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00053ff8
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x000543f4
- (BOOL)showsDesktopImage;	// IMP=0x000543ec

@end

