/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBDeviceLockKeypad, SBEmergencyCallView, TPLCDView, UIImageView, UIPasscodeField, UIView;

@interface SBSlidingAlertDisplay : SBAlertDisplay
{
    UIImageView *_backgroundView;	// 36 = 0x24
    UIView *_topBar;	// 40 = 0x28
    UIView *_bottomBar;	// 44 = 0x2c
    TPLCDView *_deviceLockStatusView;	// 48 = 0x30
    SBDeviceLockKeypad *_deviceLockKeypad;	// 52 = 0x34
    UIImageView *_deviceLockEntryBackground;	// 56 = 0x38
    UIPasscodeField *_deviceLockEntryField;	// 60 = 0x3c
    SBEmergencyCallView *_emergencyCallView;	// 64 = 0x40
    UIView *_emergencyCallTopBar;	// 68 = 0x44
    BOOL _playKeyboardClicks;	// 72 = 0x48
    unsigned int _animatingEmergencyCall:1;	// 73 = 0x49
    unsigned int _animatingIn:1;	// 73 = 0x49
    unsigned int _animatingOut:1;	// 73 = 0x49
    unsigned int _shouldFenceAnimations:1;	// 73 = 0x49
    unsigned int _showingDeviceLock:1;	// 73 = 0x49
    unsigned int _attemptingUnlock:1;	// 73 = 0x49
    unsigned int _showingDeviceUnlockFailure:1;	// 73 = 0x49
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0004e868
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x0004e7f4
+ (void)setDisplayPropertiesForActivationOfAlert:(id)fp8;	// IMP=0x0004e870
- (void)_animateToHidingDeviceLockFinished;	// IMP=0x00050744
- (void)_animateToHidingOrShowingDeviceLockFinished;	// IMP=0x000506ac
- (void)_animateToShowingDeviceLockFinished;	// IMP=0x00050700
- (void)_animateView:(id)fp8 direction:(int)fp12;	// IMP=0x00050e00
- (void)_clearUnlockFailedIndicator;	// IMP=0x0004ebbc
- (void)_enableEntry;	// IMP=0x000509f0
- (void)_entryFinishedWithPassword:(id)fp8;	// IMP=0x00050b18
- (struct CGRect)_entryFrame;	// IMP=0x0005019c
- (void)_fadeOutCompleted:(id)fp8;	// IMP=0x0004f444
- (void)_resetStatusTextView;	// IMP=0x0004eb00
- (void)_setTopBarImage:(id)fp8 shadowColor:(struct CGColor *)fp12;	// IMP=0x0004e9a0
- (void)_showUnlockFailedIndicator;	// IMP=0x0004ec1c
- (float)_startingKeypadXOrigin;	// IMP=0x0005023c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0004ffdc
- (void)animateDisplayIn:(float)fp8 middleDelay:(float)fp12 animateStatusBar:(BOOL)fp16;	// IMP=0x0004fcd4
- (void)animateFromEmergencyCallWithDuration:(float)fp8;	// IMP=0x0005139c
- (void)animateToEmergencyCall;	// IMP=0x00050e84
- (void)animateToShowingDeviceLock:(BOOL)fp8;	// IMP=0x000502f4
- (void)beginAnimatingDisplayIn:(BOOL)fp8;	// IMP=0x0004fa28
- (id)bottomBar;	// IMP=0x00051784
- (void)dealloc;	// IMP=0x0004ee6c
- (void)deviceUnlockCanceled;	// IMP=0x000509b0
- (void)deviceUnlockFailed;	// IMP=0x000507bc
- (void)deviceUnlockSucceeded;	// IMP=0x00050788
- (void)dismiss;	// IMP=0x0004f560
- (float)durationForOthersActivation;	// IMP=0x0004f558
- (void)emergencyCallWasDisplayed;	// IMP=0x000512d0
- (void)emergencyCallWasRemoved;	// IMP=0x0005168c
- (void)finishedAnimatingIn;	// IMP=0x0004f368
- (void)getFrameForTopButton:(struct CGRect *)fp8 bottomButton:(struct CGRect *)fp12;	// IMP=0x0004f02c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0004eccc
- (BOOL)isAnimatingOut;	// IMP=0x0004f434
- (BOOL)isDisplayingErrorStatus;	// IMP=0x00050ab8
- (BOOL)isReadyToBeRemovedFromView;	// IMP=0x0004f544
- (BOOL)isShowingDeviceLock;	// IMP=0x0005018c
- (id)lockBar;	// IMP=0x0004ef14
- (struct CGRect)middleFrame;	// IMP=0x0004ef6c
- (void)passcodeFieldDidAcceptEntry:(id)fp8;	// IMP=0x00050dfc
- (void)performAnimateDisplayIn;	// IMP=0x0004fc3c
- (void)phonePad:(id)fp8 keyDown:(BOOL)fp12;	// IMP=0x00050b6c
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;	// IMP=0x00050b9c
- (void)removeBlockedStatus;	// IMP=0x00050a84
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x0004f524
- (void)setShouldFenceAnimations:(BOOL)fp8;	// IMP=0x00050174
- (void)setShowingDeviceLock:(BOOL)fp8;	// IMP=0x000502d0
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;	// IMP=0x00051794
- (BOOL)shouldAnimateIconsIn;	// IMP=0x0004f3e4
- (BOOL)shouldAnimateIconsOut;	// IMP=0x0004f42c
- (BOOL)shouldShowBlockedRedStatus;	// IMP=0x00050a40
- (void)showBlockedStatus;	// IMP=0x00050a48
- (BOOL)showsDesktopImage;	// IMP=0x0004f1cc
- (id)topBar;	// IMP=0x0005178c
- (void)updateDesktopImage:(id)fp8;	// IMP=0x0004f1d4

@end

