/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBSMSAlertItem : SBAlertItem
{
    struct __CTSMSMessage *_message;	// 12 = 0xc
}

+ (void)prefsChanged;	// IMP=0x000665ac
- (void)_deactivateAllTaggedSMSAlertItems;	// IMP=0x0006615c
- (void)_playMessageReceived;	// IMP=0x00066300
- (BOOL)_showSMSPreviewWithPasscodeEnabled;	// IMP=0x000665c0
- (void)_tag;	// IMP=0x0006604c
- (void)_untag;	// IMP=0x0006611c
- (id)address;	// IMP=0x000663c0
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006655c
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00066634
- (void)dealloc;	// IMP=0x00065ffc
- (void)didActivate;	// IMP=0x00066274
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x0006629c
- (void)dismiss;	// IMP=0x0006651c
- (id)lockLabel;	// IMP=0x00066a4c
- (id)messageText;	// IMP=0x000663fc
- (void)performUnlockAction;	// IMP=0x00066590
- (void)reply;	// IMP=0x00066438
- (void)setMessage:(struct __CTSMSMessage *)fp8;	// IMP=0x000662b8
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00066ab0
- (void)willActivate;	// IMP=0x00066258
- (void)willPresentAlertSheet:(id)fp8;	// IMP=0x0006638c
- (BOOL)willShowInAwayItems;	// IMP=0x00066aa8

@end

