/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUSSDAlert.h"

@interface SBSMSClass0Alert : SBUSSDAlert
{
}

+ (void)registerForAlerts;	// IMP=0x00052354
- (void)_registerForNotifications;	// IMP=0x000523a4
- (void)_unregisterForNotifications;	// IMP=0x000523a0
- (id)initWithString:(id)fp8;	// IMP=0x000523a8

@end

