/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSoundPreferences : NSObject
{
}

+ (id)calendarAlarmPath;	// IMP=0x0004d9a4
+ (BOOL)playLockSound;	// IMP=0x0004da78
+ (id)ringtonePath;	// IMP=0x0004d9f4
+ (BOOL)shouldVibrateForCurrentRingerState;	// IMP=0x0004dcc8
+ (void)userDefaultsDidChanged:(id)fp8;	// IMP=0x0004d8c4
+ (id)vibratePattern;	// IMP=0x0004dadc
+ (BOOL)vibrateWhenRinging;	// IMP=0x0004dc00
+ (BOOL)vibrateWhenSilent;	// IMP=0x0004dc64

@end

