/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarBluetoothBatteryView : SBStatusBarContentView
{
}

- (void)batteryLevelChanged;	// IMP=0x00080a48
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x00080a64
- (id)init;	// IMP=0x000808dc
- (void)start;	// IMP=0x00080954
- (void)stop;	// IMP=0x000809e8

@end

