/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class UIImage, UIImageView;

@interface SBStatusBarBluetoothView : SBStatusBarContentView
{
    UIImage *_icon;	// 36 = 0x24
    BOOL _animating;	// 40 = 0x28
    UIImageView *_activeView;	// 44 = 0x2c
    UIImageView *_baseLayer;	// 48 = 0x30
    BOOL _isStarted;	// 52 = 0x34
}

+ (void)initialize;	// IMP=0x00063b58
- (void)_btConnectionStatusChanged:(id)fp8;	// IMP=0x00063a5c
- (void)_btDeviceConnected;	// IMP=0x0006393c
- (void)_btDeviceDisconnected:(id)fp8;	// IMP=0x00063ad0
- (void)_btPowerPrefChanged:(id)fp8;	// IMP=0x00063cc0
- (void)_btStatusChanged:(id)fp8;	// IMP=0x00063708
- (int)_effectiveMode;	// IMP=0x00063590
- (void)_setupActiveView;	// IMP=0x000635b0
- (void)_start;	// IMP=0x00063bc4
- (void)animationDidStop:(id)fp8;	// IMP=0x00063af0
- (int)btStatus;	// IMP=0x00063690
- (void)dealloc;	// IMP=0x00063da0
- (id)icon;	// IMP=0x0006352c
- (id)init;	// IMP=0x00063534
- (void)start;	// IMP=0x00063cdc
- (void)stop;	// IMP=0x00063d58

@end

