/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class SBStatusBarOperatorNameView, UIImage;

@interface SBStatusBarCarrierView : SBStatusBarContentView
{
    UIImage *_operatorIcon;	// 36 = 0x24
    SBStatusBarOperatorNameView *_operatorNameView;	// 40 = 0x28
    BOOL _operatorNameIsLooping;	// 44 = 0x2c
}

- (BOOL)_operatorName:(id)fp8 isEqualToName:(id)fp12 allowPrefixMatch:(BOOL)fp16;	// IMP=0x0003e90c
- (void)clearLastOperatorNameLooped;	// IMP=0x0003ded4
- (void)dealloc;	// IMP=0x0003dcb8
- (struct CGSize)defaultSize;	// IMP=0x0003e87c
- (void)finishedLoopingOperatorName:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003e148
- (id)init;	// IMP=0x0003eb1c
- (void)loopIfNecessary;	// IMP=0x0003e290
- (void)loopOperatorNameToBeginning:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003df30
- (void)loopOperatorNameToEnd;	// IMP=0x0003e00c
- (id)operatorIconForName:(id)fp8;	// IMP=0x0003e608
- (void)operatorNameChanged;	// IMP=0x0003e8b4
- (void)setOperatorName:(id)fp8;	// IMP=0x0003e30c
- (void)start;	// IMP=0x0003dd18
- (void)startOperatorNameLooping:(id)fp8;	// IMP=0x0003e224
- (void)stop;	// IMP=0x0003de40

@end

