/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarBatteryView : SBStatusBarContentView
{
    int _batteryCapacity;	// 36 = 0x24
    BOOL _batteryCharging;	// 40 = 0x28
    BOOL _isOnAC;	// 41 = 0x29
}

- (void)_batteryStatusChanged:(id)fp8;	// IMP=0x0003f358
- (void)dealloc;	// IMP=0x0003f3ec
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0003f57c
- (id)init;	// IMP=0x0003f374
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0003fa7c
- (void)setBatteryCapacity:(int)fp8 andCharging:(BOOL)fp12 isOnAC:(BOOL)fp16;	// IMP=0x0003f4fc
- (void)start;	// IMP=0x0003f43c
- (void)stop;	// IMP=0x0003f4bc
- (void)updateBattery;	// IMP=0x0003f2b0

@end

