/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarSignalView : SBStatusBarContentView
{
    int _dBm;	// 36 = 0x24
    int _signalStrength;	// 40 = 0x28
}

- (int)barsForRawDBM:(float)fp8;	// IMP=0x0003fccc
- (void)dealloc;	// IMP=0x0003fb8c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0003ff70
- (id)init;	// IMP=0x0003fb14
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x00040190
- (void)setSignalStrength:(int)fp8;	// IMP=0x0003fe40
- (void)start;	// IMP=0x0003fbdc
- (void)stop;	// IMP=0x0003fc7c

@end

