/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class SBStatusBarContentsView, SBStatusBarInCallView, SBStatusWindow, UIView;

@interface SBStatusBar : UIControl
{
    int _mode;	// 52 = 0x34
    int _orientation;	// 56 = 0x38
    SBStatusBarContentsView *_contentsView;	// 60 = 0x3c
    SBStatusBarInCallView *_inCallView;	// 64 = 0x40
    SBStatusWindow *_statusWindow;	// 68 = 0x44
    UIView *_airplaneView;	// 72 = 0x48
    UIView *_glowView;	// 76 = 0x4c
    UIView *_glassView;	// 80 = 0x50
    UIView *_dimmerView;	// 84 = 0x54
    unsigned int _animate:1;	// 88 = 0x58
    unsigned int _animating:1;	// 88 = 0x58
    unsigned int _isPressed:1;	// 88 = 0x58
    unsigned int _airplaneMode:1;	// 88 = 0x58
}

- (id)airplaneView;	// IMP=0x0001a0c8
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x0001a774
- (id)contentsView;	// IMP=0x0001a054
- (void)dealloc;	// IMP=0x00019f88
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0001a1e0
- (id)initWithMode:(int)fp8 orientation:(int)fp12;	// IMP=0x00019b24
- (BOOL)isDimmed;	// IMP=0x0001a7dc
- (int)mode;	// IMP=0x0001a044
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x0001a8c4
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x0001a978
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0001aa28
- (int)orientation;	// IMP=0x0001a04c
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x0001aadc
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x0001a340
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x0001a72c
- (void)setStatusWindow:(id)fp8;	// IMP=0x00019f78
- (void)showDimmerOverlay:(BOOL)fp8;	// IMP=0x0001a4f8
- (void)start;	// IMP=0x0001a48c
- (void)startGlowAnimation;	// IMP=0x0001a54c
- (void)statusBarClicked;	// IMP=0x0001a81c
- (id)statusWindow;	// IMP=0x00019f80
- (void)stop;	// IMP=0x0001a4c8
- (void)stopGlowAnimation;	// IMP=0x0001a6f0

@end

