/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBTelephonyManager : NSObject
{
    NSString *_operatorName;	// 4 = 0x4
    unsigned int _usingWifi:1;	// 8 = 0x8
    unsigned int _iTunesNeedsToRecheckActivation:1;	// 8 = 0x8
}

+ (id)sharedTelephonyManager;	// IMP=0x0002836c
- (BOOL)EDGEIsOn;	// IMP=0x0002a970
- (id)SIMStatus;	// IMP=0x0002b4c4
- (void)_cancelFakeService;	// IMP=0x0002af78
- (void)_delayedAudioResume;	// IMP=0x00029268
- (id)_fetchOperatorName;	// IMP=0x0002b14c
- (void)_headphoneChanged:(id)fp8;	// IMP=0x0002ad4c
- (void)_mainThreadDaemonRestart:(struct __CFDictionary *)fp8;	// IMP=0x0002918c
- (void)_reallySetOperatorName:(id)fp8;	// IMP=0x0002b170
- (void)_resetCTMMode;	// IMP=0x0002ad10
- (struct __CTServerConnection *)_serverConnection;	// IMP=0x000283c0
- (void)_setRegistrationStatus:(int)fp8;	// IMP=0x0002aea0
- (void)_startFakeServiceIfNecessary;	// IMP=0x0002afbc
- (void)_stopFakeService;	// IMP=0x0002b04c
- (void)_updateRegistrationNow;	// IMP=0x0002af3c
- (void)_updateState;	// IMP=0x00028720
- (void)_whackGain:(id)fp8;	// IMP=0x000289d8
- (BOOL)activeCallExists;	// IMP=0x00029f04
- (id)allMissedCallsAfterRowID:(long long)fp8;	// IMP=0x00029da8
- (id)allUnreadSMSAfterRowID:(long long)fp8;	// IMP=0x00029de0
- (void)answerIncomingCall;	// IMP=0x0002a050
- (void)answerIncomingCallEndingOthers;	// IMP=0x0002a0e0
- (int)callCount;	// IMP=0x00029ef4
- (void)checkForRegistrationSoon;	// IMP=0x0002b398
- (void)configureForTTY:(BOOL)fp8;	// IMP=0x0002aac0
- (void)copyICCID:(id *)fp8 IMEI:(id *)fp12;	// IMP=0x0002aa34
- (int)dataConnectionType;	// IMP=0x0002b580
- (void)disconnectAllCalls;	// IMP=0x0002a1fc
- (void)disconnectCall;	// IMP=0x0002a224
- (void)disconnectCallAndActivateHeld;	// IMP=0x0002a32c
- (void)disconnectIncomingCall;	// IMP=0x0002a02c
- (id)displayForOutgoingCallURL:(id)fp8;	// IMP=0x00028ba0
- (void)dumpBasebandState:(id)fp8;	// IMP=0x0002a3b0
- (long long)getRowIDOfLastCallInsert;	// IMP=0x00029d98
- (long long)getRowIDOfLastSMSInsert;	// IMP=0x00029dd0
- (void)handleSIMReady;	// IMP=0x0002888c
- (BOOL)heldCallExists;	// IMP=0x00029f1c
- (BOOL)inCall;	// IMP=0x00029fec
- (double)inCallDuration;	// IMP=0x00028580
- (BOOL)inCallUsingReceiver;	// IMP=0x00029f64
- (BOOL)incomingCallExists;	// IMP=0x00029f34
- (id)init;	// IMP=0x0002b8f4
- (BOOL)isUsingDataConnection;	// IMP=0x0002a9e8
- (BOOL)isUsingWiFiConnection;	// IMP=0x0002aa10
- (void)kickStartSearching;	// IMP=0x0002b4a4
- (void)markMessageAsRead:(struct __CTSMSMessage *)fp8;	// IMP=0x00029e08
- (void)noteSIMUnlockAttempt;	// IMP=0x0002b530
- (id)operatorName;	// IMP=0x0002b290
- (BOOL)outgoingCallExists;	// IMP=0x00029f4c
- (void)powerOffRadio;	// IMP=0x0002a424
- (int)registrationStatus;	// IMP=0x0002b388
- (void)setIsUsingWiFiConnection:(BOOL)fp8;	// IMP=0x0002aa1c
- (void)setOperatorName:(id)fp8;	// IMP=0x0002b214
- (BOOL)shouldPromptForTTY;	// IMP=0x0002ab28
- (void)swapCalls;	// IMP=0x0002a1c4
- (id)ttyTitle;	// IMP=0x0002ac00
- (void)unmute;	// IMP=0x0002a33c
- (void)updateAirplaneMode;	// IMP=0x00028668
- (void)updateCalls;	// IMP=0x00029b04
- (void)updateLocale;	// IMP=0x00028854
- (void)updateNetworkLocale;	// IMP=0x00028870
- (void)updatePhoneNumberPrefs;	// IMP=0x0002842c
- (void)updateSMSBadges;	// IMP=0x00029e3c
- (void)updateSpringBoard;	// IMP=0x0002bf18
- (void)updateTTYIndicator;	// IMP=0x000284f8
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20;	// IMP=0x00028a54

@end

