/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x000631dc
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00063134
- (void)_chooseTTYMode:(id)fp8;	// IMP=0x00063488
- (void)_chooseVoiceMode:(id)fp8;	// IMP=0x00063434
- (void)_ignore:(id)fp8;	// IMP=0x000634e0
- (void)_makeCall;	// IMP=0x000632ec
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x00062f40

@end

