/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBTVOutController : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0007fa70
- (void)dealloc;	// IMP=0x0007fb18
- (id)init;	// IMP=0x0007fac0
- (void)mergeSetting:(struct __CFString *)fp8 iapSettings:(id)fp12 finalSettings:(id)fp16 settingMergeSelector:(SEL)fp20;	// IMP=0x0007fb68
- (id)mergedTVOutSettingForUserSetting:(id)fp8 iapSetting:(id)fp12;	// IMP=0x0007fc34
- (void)setIntialTVModeIfNeeded;	// IMP=0x0007fce0
- (void)updateLayerKitSettings:(id)fp8;	// IMP=0x0007fe44
- (void)updateSettings;	// IMP=0x0007ff3c

@end

