/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBUserNotificationCenter : NSObject
{
}

+ (void)_userNotificationDone:(id)fp8;	// IMP=0x000610c4
+ (void)startUserNotificationCenter;	// IMP=0x00060f40

@end

