/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBUSSDAlert : SBAlert
{
    unsigned int _receivedString:1;	// 48 = 0x30
    unsigned int _dismissOnActivate:1;	// 48 = 0x30
    NSTimer *_delayedDismissTimer;	// 52 = 0x34
}

+ (void)_daemonRestart:(id)fp8;	// IMP=0x0005add0
+ (void)_newSIM:(id)fp8;	// IMP=0x0005ae98
+ (id)errorStringForCode:(unsigned int)fp8;	// IMP=0x0005ad44
+ (void)registerForAlerts;	// IMP=0x0005ab20
+ (void)registerForSettingsAlerts;	// IMP=0x0005aa6c
+ (void)test;	// IMP=0x0005acb4
- (void)USSDStringAvailable:(id)fp8 allowsResponse:(BOOL)fp12;	// IMP=0x0005af00
- (void)_delayedDismiss;	// IMP=0x0005b02c
- (BOOL)activate;	// IMP=0x0005b090
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0005aea8
- (BOOL)allowsResponse;	// IMP=0x0005afd0
- (BOOL)deactivate;	// IMP=0x0005b1b0
- (void)dealloc;	// IMP=0x0005a9e8
- (BOOL)receivedString;	// IMP=0x0005b008
- (void)setDismissOnActivate:(BOOL)fp8;	// IMP=0x0005b014

@end

