/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBVoicemailManager : NSObject
{
    CDAnonymousStruct1 _alertMark;	// 4 = 0x4
    CDAnonymousStruct1 _awayItemMark;	// 20 = 0x14
    BOOL _hasVisualVoicemail;	// 36 = 0x24
    int _visualVoicemailSubscriptionToken;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x0007619c
- (void)_handleVoicemailAvailableNotification:(id)fp8;	// IMP=0x00076678
- (void)_handleVoicemailStoreChangedNotification;	// IMP=0x00076840
- (BOOL)_hasVisualVoicemail;	// IMP=0x00076334
- (void)_mark:(CDAnonymousStruct1 *)fp8;	// IMP=0x0007633c
- (void)_presentAlertForRecord:(void *)fp8 visualVoicemail:(BOOL)fp12;	// IMP=0x00076480
- (void)_updateVisualVoicemailState;	// IMP=0x000762f0
- (id)copyVisualVoicemailRecordsForAwayItems;	// IMP=0x00076440
- (void)dealloc;	// IMP=0x000760fc
- (id)init;	// IMP=0x00076014
- (void)mark;	// IMP=0x0007640c
- (void)markForAlerts;	// IMP=0x000763cc
- (void)markForAwayItems;	// IMP=0x000763ec
- (void)setHasVisualVoicemail:(BOOL)fp8;	// IMP=0x00076200

@end

