/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBWeatherApplicationIcon : SBApplicationIcon
{
}

- (void)dealloc;	// IMP=0x000821f8
- (id)icon;	// IMP=0x00082324
- (id)initWithApplication:(id)fp8;	// IMP=0x00082184
- (void)resetIcon;	// IMP=0x00082250
- (BOOL)showFahrenheit;	// IMP=0x000822cc

@end

