/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplication.h"

@interface SBWidgetApplication : SBApplication
{
}

- (id)arguments;	// IMP=0x00021f64
- (id)bundleForLaunching;	// IMP=0x00021efc
- (BOOL)isWidget;	// IMP=0x00021f5c
- (id)pathForDefaultImage:(char *)fp8;	// IMP=0x00021d94
- (id)pathForIcon;	// IMP=0x00021ed4

@end

