/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageView.h"

@interface SBWiFiSignalStrength : UIImageView
{
    int _bars;	// 52 = 0x34
    int _rawStrength;	// 56 = 0x38
    BOOL _hilited;	// 60 = 0x3c
    BOOL _selected;	// 61 = 0x3d
    BOOL _secure;	// 62 = 0x3e
    BOOL _joining;	// 63 = 0x3f
    UIImageView *_icon;	// 64 = 0x40
}

+ (void)hideSpinner;	// IMP=0x00070360
- (void)dealloc;	// IMP=0x000709e4
- (void)hide;	// IMP=0x00070dd4
- (BOOL)hilited;	// IMP=0x00070e38
- (id)initWithFrame:(struct CGRect)fp8 inView:(id)fp24;	// IMP=0x000703c8
- (BOOL)joining;	// IMP=0x00070a9c
- (BOOL)secure;	// IMP=0x00070e74
- (BOOL)selected;	// IMP=0x00070dcc
- (void)setHilited:(BOOL)fp8;	// IMP=0x00070e40
- (void)setJoining:(BOOL)fp8;	// IMP=0x00070aa4
- (void)setSecure:(BOOL)fp8;	// IMP=0x00070e7c
- (void)setSelected:(BOOL)fp8;	// IMP=0x00070e04
- (void)setSpinnerHilited:(BOOL)fp8;	// IMP=0x00070394
- (void)updateImage;	// IMP=0x00070eb0
- (void)updateStrength:(id)fp8;	// IMP=0x00070c20

@end

