/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SpringBoard.h"

@interface SpringBoard (SBApplicationTesting)
- (id)_pathForTestOptions:(id)fp8;	// IMP=0x0001ae7c
- (void)anotherApplicationFinishedLaunching:(struct __GSEvent *)fp8;	// IMP=0x0001b43c
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;	// IMP=0x0001b488
- (BOOL)runTest:(id)fp8 options:(id)fp12;	// IMP=0x0001aef4
- (void)startLaunchTestNamed:(id)fp8 options:(id)fp12;	// IMP=0x0001b05c
- (void)startResumeTestNamed:(id)fp8 options:(id)fp12;	// IMP=0x0001b358
@end

