/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITextField.h"

@interface WhiteBorderedTextField : UITextField
{
}

- (void)drawBorder:(struct CGRect)fp8;	// IMP=0x00033248
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x00033360
- (struct CGRect)textRect;	// IMP=0x000332d8

@end

