/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString, NSTimer;

@interface AlarmController : NSObject
{
    NSMutableArray *_alarmList;	// 4 = 0x4
    NSTimer *_alarmTimer;	// 8 = 0x8
    NSMutableArray *_alarmsToFire;	// 12 = 0xc
    unsigned int _readingPrefs:1;	// 16 = 0x10
    NSTimer *_countDownTimer;	// 20 = 0x14
    double _countDownTimerInterval;	// 24 = 0x18
    NSString *_countDownTimerSoundIdentifier;	// 32 = 0x20
    struct __CFDate *_alarmWakeupDate;	// 36 = 0x24
    struct __CFDate *_countdownWakeupDate;	// 40 = 0x28
}

+ (id)sharedAlarmController;	// IMP=0x00058cdc
- (void)_alarmChanged:(id)fp8;	// IMP=0x00058f7c
- (void)_alarmTimeReached:(id)fp8;	// IMP=0x00059728
- (void)_countDownTimerFired:(id)fp8;	// IMP=0x00059a08
- (void)_readPreferences;	// IMP=0x00058d2c
- (void)_savePreferences;	// IMP=0x00058e40
- (void)_scheduleAlarms;	// IMP=0x00059338
- (void)_sleepTimerFired:(id)fp8;	// IMP=0x00059ac4
- (void)_wokeFromSleep;	// IMP=0x00059c10
- (unsigned int)addAlarm:(id)fp8;	// IMP=0x00059234
- (id)alarms;	// IMP=0x00059330
- (double)countDownTimerInterval;	// IMP=0x00059bfc
- (id)countDownTimerSoundIdentifier;	// IMP=0x00059c08
- (void)dealloc;	// IMP=0x00059140
- (id)init;	// IMP=0x00058ffc
- (void)removeAlarmAtIndex:(unsigned int)fp8;	// IMP=0x000592e4
- (void)setCountDownTimerInterval:(double)fp8 withSoundIdentifier:(id)fp16;	// IMP=0x000597d4

@end

