/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPushButton.h"

@interface BorderedPushButton : UIPushButton
{
}

- (void)_sizeToFit;	// IMP=0x0002df94
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x0002e060

@end

