/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface EllipseWindow : UIWindow
{
    BOOL showEcho;	// 64 = 0x40
    BOOL inUse;	// 65 = 0x41
    BOOL isAnimating;	// 66 = 0x42
    struct CGPoint startLoc;	// 68 = 0x44
    double startTime;	// 76 = 0x4c
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x00053c94
+ (void)initialize;	// IMP=0x00053b60
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;	// IMP=0x00053f68
- (void)finishHide;	// IMP=0x00053f40
- (void)fixupOrdering;	// IMP=0x00053c68
- (BOOL)isHidden;	// IMP=0x00053edc
- (void)playTouchAnimation;	// IMP=0x00053cb8
- (void)setHidden:(BOOL)fp8;	// IMP=0x00053f00
- (void)showTouchImage:(BOOL)fp8;	// IMP=0x00053f90

@end

