/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (CTHelpers)
- (id)callBarringFacility;	// IMP=0x000559a4
- (id)callClass;	// IMP=0x0005550c
- (id)callForwardingReason;	// IMP=0x000557a0
- (id)callingLineIDRestrictionValue;	// IMP=0x00055c80
- (id)callingLinePresentationValue;	// IMP=0x00055e6c
- (id)connectedLineIDRestrictionValue;	// IMP=0x00055fe0
- (id)connectedLinePresentationValue;	// IMP=0x0005610c
- (id)enabledString;	// IMP=0x00056280
- (id)mmiProcedure;	// IMP=0x000564e4
- (id)serviceCenterAddress;	// IMP=0x00056350
- (struct __CFString *)settingType;	// IMP=0x000566a0
- (id)ssServiceType;	// IMP=0x000563d4
@end

