/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (id)pop;	// IMP=0x000379a4
- (id)popObject:(id)fp8;	// IMP=0x00037a2c
- (void)push:(id)fp8;	// IMP=0x00037938
- (id)top;	// IMP=0x00037aa0
@end

