/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (PrefsNotifications)
- (id)_alertStringForPref:(id)fp8;	// IMP=0x0005703c
- (id)_callBarringString:(id)fp8;	// IMP=0x000569a0
- (id)_callForwardingString:(id)fp8;	// IMP=0x0005673c
- (id)_callWaitingString:(id)fp8;	// IMP=0x000568d8
- (id)_callingLineIDRestrictionString:(id)fp8;	// IMP=0x00056d8c
- (id)_callingLinePresentationString:(id)fp8;	// IMP=0x00056c34
- (id)_connectedLineIDRestrictionString:(id)fp8;	// IMP=0x00056ce0
- (id)_connectedLinePresentationString:(id)fp8;	// IMP=0x00056b88
- (id)_fixedDialingString:(id)fp8;	// IMP=0x00056a84
- (id)_serviceCenterAddressString:(id)fp8;	// IMP=0x00056ee4
- (id)_simLockString:(id)fp8;	// IMP=0x00056e38
- (id)_ssPasswordString:(id)fp8;	// IMP=0x00056f90
- (void)addPrefNotification:(id)fp8 withUserInfo:(id)fp12;	// IMP=0x000566cc
- (id)prefsNotificationsAlertString;	// IMP=0x00057488
@end

