/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@class Alarm;

@interface SBAlarmAlertItem : SBRingingAlertItem
{
    Alarm *_alarm;	// 24 = 0x18
    BOOL _snoozeAlarm;	// 28 = 0x1c
}

- (id)alarm;	// IMP=0x0006074c
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00060acc
- (BOOL)allowsSnooze;	// IMP=0x00060754
- (id)avAudioCategory;	// IMP=0x00060ac0
- (id)avClientName;	// IMP=0x00060ab4
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006086c
- (void)dealloc;	// IMP=0x000606b0
- (id)initWithAlarm:(id)fp8;	// IMP=0x00060670
- (id)lockLabel;	// IMP=0x00060810
- (void)setAlarm:(id)fp8;	// IMP=0x00060704
- (id)soundIdentifier;	// IMP=0x00060a88
- (void)startSnoozingAndDeactivate;	// IMP=0x00060784

@end

