/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBAlert;

@interface SBAlertDisplay : UIView
{
    SBAlert *_alert;	// 28 = 0x1c
    unsigned int _displaysAboveStatusBar:1;	// 32 = 0x20
    unsigned int _shouldAnimateIn:1;	// 32 = 0x20
}

- (id)alert;	// IMP=0x00018bb0
- (void)alertDisplayBecameVisible;	// IMP=0x00018c80
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00018c7c
- (void)dismiss;	// IMP=0x00018c04
- (BOOL)displaysAboveStatusBar;	// IMP=0x00018c84
- (BOOL)isReadyToBeRemovedFromView;	// IMP=0x00018ca8
- (void)launchURL:(id)fp8;	// IMP=0x00018bb8
- (void)setAlert:(id)fp8;	// IMP=0x00018b84
- (void)setDisplaysAboveStatusBar:(BOOL)fp8;	// IMP=0x00018c90
- (void)setHandlerAlreadyActive:(BOOL)fp8;	// IMP=0x00018c40
- (void)setShouldAnimateIn:(BOOL)fp8;	// IMP=0x00018cb0
- (BOOL)shouldAnimateIn;	// IMP=0x00018cc8
- (void)willDismiss;	// IMP=0x00018bd0

@end

