/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDisplay.h"

@class NSMutableDictionary, SBAlertDisplay, SBAlertWindow;

@interface SBAlert : SBDisplay
{
    SBAlertDisplay *_display;	// 36 = 0x24
    NSMutableDictionary *_dictionary;	// 40 = 0x28
    SBAlertWindow *_deferredAlertWindow;	// 44 = 0x2c
}

+ (id)alertWindow;	// IMP=0x00018f00
+ (void)registerForAlerts;	// IMP=0x00018e90
+ (void)test;	// IMP=0x00018f10
- (BOOL)activate;	// IMP=0x00019098
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00018f64
- (struct CGRect)alertWindowRect;	// IMP=0x0001902c
- (BOOL)allowsInCallStatusBar;	// IMP=0x00019588
- (BOOL)allowsStackingOfAlert:(id)fp8;	// IMP=0x00018ff8
- (double)animateInDuration;	// IMP=0x00019018
- (BOOL)animatesDismissal;	// IMP=0x00019580
- (float)autoDimTime;	// IMP=0x00019590
- (BOOL)deactivate;	// IMP=0x00019448
- (void)dealloc;	// IMP=0x00018e94
- (void)didAnimateLockKeypadIn;	// IMP=0x000195ac
- (void)didAnimateLockKeypadOut;	// IMP=0x000195b0
- (void)didFinishAnimatingIn;	// IMP=0x000195b4
- (void)didFinishAnimatingOut;	// IMP=0x000195b8
- (id)display;	// IMP=0x00018f14
- (BOOL)displaysAboveLock;	// IMP=0x00019000
- (float)finalAlpha;	// IMP=0x00019010
- (id)objectForKey:(id)fp8;	// IMP=0x00018fd8
- (void)removeFromView;	// IMP=0x00019364
- (void)setDisplay:(id)fp8;	// IMP=0x00018f1c
- (void)setObject:(id)fp8 forKey:(id)fp12;	// IMP=0x00018f6c
- (int)statusBarMode;	// IMP=0x0001959c
- (int)statusBarOrientation;	// IMP=0x000195a4
- (void)tearDownAlertWindow:(id)fp8;	// IMP=0x00019298
- (BOOL)undimsDisplay;	// IMP=0x00019008

@end

