/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSTimer;

@interface SBAlertItemsController : NSObject
{
    NSMutableArray *_lockedAlertItems;	// 4 = 0x4
    NSMutableArray *_unlockedAlertItems;	// 8 = 0x8
    NSTimer *_autoDismissTimer;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x0005f2c4
- (void)_deactivateAlertItem:(id)fp8 forLock:(BOOL)fp12;	// IMP=0x0005f918
- (void)activateAlertItem:(id)fp8;	// IMP=0x0005f694
- (void)autoDismissAlertItem:(id)fp8;	// IMP=0x0005faac
- (void)convertAnimatingUnlockedAlertsToLockedAlerts;	// IMP=0x0005f404
- (BOOL)deactivateAlertForMenuClick;	// IMP=0x0005fb34
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x0005fa8c
- (void)deactivateAlertItemsForLock;	// IMP=0x0005fbb8
- (void)deactivateAllAlertItems;	// IMP=0x0005f500
- (void)dealloc;	// IMP=0x0005f3a4
- (id)init;	// IMP=0x0005f314
- (BOOL)isShowingAlerts;	// IMP=0x0005faec
- (void)resetAutoDismissTimer;	// IMP=0x0005f5a0

@end

