/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface SBApplicationIconBadge : UIView
{
    NSString *_badge;	// 28 = 0x1c
    struct CGSize _badgeContentSize;	// 32 = 0x20
}

- (void)dealloc;	// IMP=0x0001b3a0
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0001b3f4
- (id)initWithBadge:(id)fp8;	// IMP=0x0001b244

@end

