/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class SBApplication, SBApplicationIconBadge, SBApplicationIconLabel, UIImage, UIImageView;

@interface SBApplicationIcon : UIControl
{
    UIImage *_icon;	// 52 = 0x34
    SBApplication *_app;	// 56 = 0x38
    UIImageView *_image;	// 60 = 0x3c
    SBApplicationIconBadge *_badge;	// 64 = 0x40
    SBApplicationIconLabel *_label;	// 68 = 0x44
    BOOL _drawsLabel;	// 72 = 0x48
    BOOL _isHidden;	// 73 = 0x49
}

- (id)_automationID;	// IMP=0x0000eca4
- (id)application;	// IMP=0x0000e790
- (void)dealloc;	// IMP=0x0000e73c
- (id)displayName;	// IMP=0x0000ec84
- (id)hilightedIcon;	// IMP=0x0000ea4c
- (id)icon;	// IMP=0x0000e94c
- (id)initWithApplication:(id)fp8;	// IMP=0x0000e6b4
- (BOOL)isHidden;	// IMP=0x0000e7a0
- (void)layout;	// IMP=0x0000ec40
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x0000ed28
- (void)setBadge:(id)fp8;	// IMP=0x0000f10c
- (void)setDisplayedIcon:(id)fp8;	// IMP=0x0000e800
- (void)setDrawsLabel:(BOOL)fp8;	// IMP=0x0000f24c
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x0000eda8
- (void)setIsHidden:(BOOL)fp8;	// IMP=0x0000e798
- (BOOL)shouldTrack;	// IMP=0x0000ece4
- (id)subviews;	// IMP=0x0000e7a8

@end

