/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface SBAppWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0000a5a4
- (void)dealloc;	// IMP=0x0000a474
- (id)initWithContentRect:(struct CGRect)fp8;	// IMP=0x0000a410
- (void)sendEvent:(struct __GSEvent *)fp8;	// IMP=0x0000a4d4
- (BOOL)shouldRespondToStatusBarHeightChange;	// IMP=0x0000a59c

@end

