/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface SBApplicationIconLabel : UIView
{
    NSString *_label;	// 28 = 0x1c
}

- (void)dealloc;	// IMP=0x0000eeec
- (void)drawLabelInRect:(struct CGRect)fp8;	// IMP=0x0000ef40
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0000f0b8
- (id)initWithSize:(struct CGSize)fp8 label:(id)fp16;	// IMP=0x0000ee74

@end

