/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, SBAwayController;

@interface SBAwayModel : NSObject
{
    SBAwayController *_controller;	// 4 = 0x4
    NSMutableArray *_standardVMs;	// 8 = 0x8
    NSMutableArray *_calls;	// 12 = 0xc
    NSMutableArray *_SMSs;	// 16 = 0x10
    NSMutableArray *_otherAwayItems;	// 20 = 0x14
}

- (void)addCall:(struct __CTCall *)fp8;	// IMP=0x000236b4
- (void)addOtherAwayItem:(id)fp8;	// IMP=0x00023650
- (void)addSMSMessage:(struct __CTSMSMessage *)fp8;	// IMP=0x00023738
- (void)dealloc;	// IMP=0x00023534
- (id)initWithController:(id)fp8;	// IMP=0x000234ec
- (void)markAwayTime;	// IMP=0x000235ac
- (id)missedItems;	// IMP=0x0002417c
- (void)populateWithMissedCalls:(id)fp8;	// IMP=0x000239d8
- (void)populateWithMissedEnhancedVoiceMails:(id)fp8;	// IMP=0x00024038
- (void)populateWithMissedSMS:(id)fp8;	// IMP=0x00023d30
- (void)setStandardVoiceMailCount:(int)fp8;	// IMP=0x00024394
- (int)uncoalescedMissedItemCount;	// IMP=0x000242ac

@end

