/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSDate, NSDictionary, NSMutableArray, NSTimeZone, NSTimer, SBAlertItem, SBAwayItem, SBAwayModel, SBAwayView, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;	// 48 = 0x30
    SBAwayModel *_model;	// 52 = 0x34
    SBAwayView *_awayView;	// 56 = 0x38
    NSTimer *_dimTimer;	// 60 = 0x3c
    NSDate *_lockDate;	// 64 = 0x40
    SBAwayItem *_clickedItem;	// 68 = 0x44
    unsigned int _isLocked:1;	// 72 = 0x48
    unsigned int _isDimmed:1;	// 72 = 0x48
    unsigned int _isDimming:1;	// 72 = 0x48
    unsigned int _orderedOutDimmed:1;	// 72 = 0x48
    unsigned int _frontDimmed:1;	// 72 = 0x48
    unsigned int _isBlocked:1;	// 72 = 0x48
    unsigned int _makingEmergencyCall:1;	// 72 = 0x48
    unsigned int _appRequestedPasscodeEntry:1;	// 72 = 0x48
    unsigned int _needToMakeEmergencyCall:1;	// 73 = 0x49
    unsigned int _isSyncing:1;	// 73 = 0x49
    unsigned int _relockAfterUnlock:1;	// 73 = 0x49
    unsigned int _wasLockedBeforeSync:1;	// 73 = 0x49
    unsigned int _wasDeviceLockedBeforeSync:1;	// 73 = 0x49
    NSDictionary *_nowPlayingInfo;	// 76 = 0x4c
    double _sleepDelay;	// 80 = 0x50
    SBSlidingAlertDisplay *_deviceUnlockDisplay;	// 88 = 0x58
    double _deviceLockBlockTime;	// 92 = 0x5c
    double _deviceLockGracePeriodEndTimeInterval;	// 100 = 0x64
    NSTimeZone *_deviceLockGraceTimeZone;	// 108 = 0x6c
    NSMutableArray *_pendingAlertItems;	// 112 = 0x70
    SBAlertItem *_currentAlertItem;	// 116 = 0x74
    int _notifyLockStateToken;	// 120 = 0x78
    int _notifyDontAnimateREOToken;	// 124 = 0x7c
}

+ (void)registerForAlerts;	// IMP=0x0001eef4
+ (id)sharedAwayController;	// IMP=0x0001ee24
- (void)_activateEmergencyCall;	// IMP=0x00022020
- (void)_clearBlockedState;	// IMP=0x0001feb0
- (void)_finishedUnlockAttemptWithStatus:(BOOL)fp8;	// IMP=0x00020c00
- (void)_frontForSuspendedLockAfterDelay;	// IMP=0x000204b0
- (BOOL)_isDeviceBricked;	// IMP=0x0001faf8
- (void)_resetGracePeriod;	// IMP=0x0001f87c
- (void)_sendLockStateChangedNotification;	// IMP=0x0001f3f4
- (void)_setupDeviceLockGracePeriod;	// IMP=0x0001f96c
- (void)_timeChanged;	// IMP=0x0001f904
- (void)_undimScreen;	// IMP=0x00021740
- (void)_unlockWithSound:(BOOL)fp8;	// IMP=0x0001f51c
- (void)activate;	// IMP=0x00021840
- (BOOL)activateAlertItem:(id)fp8;	// IMP=0x0002253c
- (void)activationChanged:(id)fp8;	// IMP=0x0001fad8
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0001f07c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0001f098
- (struct CGRect)alertWindowRect;	// IMP=0x0001eef8
- (BOOL)allowsInCallStatusBar;	// IMP=0x00021b44
- (BOOL)allowsStackingOfAlert:(id)fp8;	// IMP=0x00021af8
- (double)animateInDuration;	// IMP=0x0001f304
- (BOOL)animatesDismissal;	// IMP=0x00021bf0
- (void)animator:(id)fp8 stopAnimation:(id)fp12;	// IMP=0x00021e48
- (void)applicationDidFinishLaunching:(id)fp8;	// IMP=0x0001eea8
- (void)applicationRequestedDeviceUnlock;	// IMP=0x0001fe10
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 alertDisplay:(id)fp12;	// IMP=0x00020c30
- (BOOL)attemptSnoozeRingingAlertItem;	// IMP=0x00022318
- (void)attemptUnlock;	// IMP=0x00020b54
- (id)awayModel;	// IMP=0x0001eea0
- (id)awayView;	// IMP=0x0001ef68
- (void)cancelApplicationRequestedDeviceLockEntry;	// IMP=0x0001fe78
- (void)cancelDimTimer;	// IMP=0x00021084
- (void)clensePendingQueueOfAwayItems;	// IMP=0x000212ac
- (void)clickItem:(id)fp8;	// IMP=0x00021f00
- (id)currentAlertItem;	// IMP=0x000221c8
- (BOOL)deactivate;	// IMP=0x00021978
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00022810
- (void)dealloc;	// IMP=0x0001f100
- (void)delaySleepByNumberOfSeconds:(float)fp8;	// IMP=0x00021578
- (void)didAnimateLockKeypadIn;	// IMP=0x00022144
- (void)didAnimateLockKeypadOut;	// IMP=0x00022148
- (void)didFinishAnimatingOut;	// IMP=0x00021dcc
- (void)dimScreen:(BOOL)fp8;	// IMP=0x0002160c
- (void)emergencyCallWasDisplayed;	// IMP=0x00022090
- (void)emergencyCallWasRemoved;	// IMP=0x00022108
- (float)finalAlpha;	// IMP=0x0001ef58
- (void)frontForSuspendedLockAfterDelay:(float)fp8;	// IMP=0x000204e0
- (void)frontLocked:(BOOL)fp8 animate:(BOOL)fp12 automatically:(BOOL)fp16;	// IMP=0x0002062c
- (void)frontLockedAnimationFinished;	// IMP=0x00020490
- (void)handleClickedItem:(id)fp8;	// IMP=0x0001f1d8
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;	// IMP=0x00021f64
- (id)initWithUIController:(id)fp8;	// IMP=0x0001ebcc
- (BOOL)isAttemptingUnlock;	// IMP=0x00020be8
- (BOOL)isBlocked;	// IMP=0x0001ff6c
- (BOOL)isCurrentAlertItemRinging;	// IMP=0x00022294
- (BOOL)isDeviceLocked;	// IMP=0x0001fb34
- (BOOL)isDimmed;	// IMP=0x000211a8
- (BOOL)isLocked;	// IMP=0x00020408
- (BOOL)isMakingEmergencyCall;	// IMP=0x00022134
- (BOOL)isPasswordProtected;	// IMP=0x0001fa4c
- (BOOL)isPermanentlyBlocked:(double *)fp8;	// IMP=0x0001ffe8
- (BOOL)isSyncing;	// IMP=0x000202ec
- (void)lock;	// IMP=0x0001f450
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00020414
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00020438
- (void)makeEmergencyCall;	// IMP=0x00021fb4
- (BOOL)moveAlertItemToAwayView:(id)fp8;	// IMP=0x00021260
- (void)noteResetRestoreStateChanged;	// IMP=0x000202fc
- (void)noteSyncStateChanged;	// IMP=0x00020070
- (void)orderOut;	// IMP=0x00021c1c
- (void)pendOrDeactivateCurrentAlertItem;	// IMP=0x000221d0
- (void)playLockSound;	// IMP=0x0001f3dc
- (void)preventIdleSleep;	// IMP=0x00020fa4
- (void)reactivatePendingAlertItems;	// IMP=0x0001f310
- (void)relock;	// IMP=0x00021408
- (void)relockDimmed:(BOOL)fp8;	// IMP=0x000214ac
- (void)resetAwayItems;	// IMP=0x00020458
- (void)restartDimTimer:(float)fp8;	// IMP=0x000210cc
- (void)setDeviceLocked:(BOOL)fp8;	// IMP=0x0001fc98
- (BOOL)shouldAnimateOthersSuspension;	// IMP=0x00020524
- (void)sleep;	// IMP=0x00020f68
- (double)sleepDelay;	// IMP=0x000214dc
- (void)snoozeOrStopRingingAlertItem;	// IMP=0x00022444
- (int)statusBarMode;	// IMP=0x00021b4c
- (void)stopRingingAlertItem;	// IMP=0x000223b4
- (void)toggleShowsIMEIandICCID:(id)fp8;	// IMP=0x000229bc
- (BOOL)trySnoozingAlarmAlertItem;	// IMP=0x00022480
- (void)undimScreen;	// IMP=0x00021770
- (BOOL)undimsDisplay;	// IMP=0x0001ef60
- (void)unlockWithSound:(BOOL)fp8;	// IMP=0x0001f648
- (void)unlockWithSound:(BOOL)fp8 alertDisplay:(id)fp12;	// IMP=0x0001f69c
- (void)updateClockFormat;	// IMP=0x00021f84
- (void)updateInCallUI;	// IMP=0x00022978
- (void)updateNowPlayingInfo:(id)fp8;	// IMP=0x00021f04
- (void)wake;	// IMP=0x00020fc4
- (BOOL)wantsToHandleAlert:(id)fp8;	// IMP=0x000227a0

@end

