/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBBatteryChargingView;

@interface SBAwayChargingView : UIView
{
    SBBatteryChargingView *_chargingView;	// 28 = 0x1c
    SBBatteryChargingView *_headsetChargingView;	// 32 = 0x20
    unsigned int _animatingBatteries:1;	// 36 = 0x24
    unsigned int _updateAfterAnimation:1;	// 36 = 0x24
    unsigned int _showingDeviceBattery:1;	// 36 = 0x24
    unsigned int _showingHeadsetBattery:1;	// 36 = 0x24
}

+ (struct CGSize)defaultSize;	// IMP=0x00070640
+ (BOOL)shouldShowDeviceBattery;	// IMP=0x00070710
+ (BOOL)shouldShowHeadsetBattery;	// IMP=0x00070770
- (void)_batteryAnimationFinished:(id)fp8;	// IMP=0x00071634
- (struct CGPoint)_dualBatteryPositionForBattery:(id)fp8;	// IMP=0x000718cc
- (void)_finishedFadeForSwitch:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x00071348
- (void)_finishedHideForHideToSlide:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x00071518
- (void)_finishedSlideForSlideToReveal:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;	// IMP=0x00071430
- (struct CGPoint)_singleBatteryPositionForBattery:(id)fp8;	// IMP=0x00071794
- (void)_slideBattery:(id)fp8 toHideBattery:(id)fp12 animate:(BOOL)fp16;	// IMP=0x000711a8
- (void)_slideBattery:(id)fp8 toShowBattery:(id)fp12 animate:(BOOL)fp16;	// IMP=0x00070ff8
- (void)_switchFromBattery:(id)fp8 toView:(id)fp12 animate:(BOOL)fp16;	// IMP=0x00070e54
- (void)_test:(id)fp8;	// IMP=0x00071678
- (void)addChargingView;	// IMP=0x00070be4
- (void)addHeadsetChargingView;	// IMP=0x00070db8
- (id)chargingView;	// IMP=0x00070a88
- (void)dealloc;	// IMP=0x000705b0
- (id)headsetChargingView;	// IMP=0x00070c80
- (void)hideChargingView;	// IMP=0x00070c5c
- (void)hideHeadsetChargingView;	// IMP=0x00070e30
- (id)initWithFrame:(struct CGRect)fp8 awayView:(id)fp24;	// IMP=0x000704a4
- (void)updateInterface:(BOOL)fp8;	// IMP=0x000707d0

@end

