/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIAlertSheet.h"

@class NSArray;

@interface SBAwayItemsView : UIAlertSheet
{
    NSArray *_displayedItems;	// 96 = 0x60
    float _widestLabel;	// 100 = 0x64
}

+ (struct __GSFont *)createItemTypeFont;	// IMP=0x00032b40
- (void)dealloc;	// IMP=0x00032aec
- (void)drawItems;	// IMP=0x00032f34
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0003321c
- (BOOL)hasAwayItems;	// IMP=0x00032f0c
- (id)init;	// IMP=0x00032a90
- (BOOL)reloadData;	// IMP=0x00032d04

@end

