/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSDictionary, NSString, NSTimer, SBAwayChargingView, SBAwayDateView, SBAwayInCallController, SBAwayItemsView, SBNowPlayingArtView, TPBottomButtonBar, TPBottomLockBar, UIAlertSheet, UIImage, UIPushButton;

@interface SBAwayView : SBSlidingAlertDisplay
{
    BOOL _isDimmed;	// 70 = 0x46
    BOOL _deferAwayItemFetching;	// 71 = 0x47
    BOOL _showingBlockedIndicator;	// 72 = 0x48
    SBAwayChargingView *_chargingView;	// 76 = 0x4c
    SBAwayDateView *_dateView;	// 80 = 0x50
    SBNowPlayingArtView *_albumArtView;	// 84 = 0x54
    SBAwayItemsView *_awayItemsView;	// 88 = 0x58
    NSDictionary *_nowPlayingInfo;	// 92 = 0x5c
    UIImage *_nowPlayingArt;	// 96 = 0x60
    NSString *_lastTrackArtPath;	// 100 = 0x64
    NSTimer *_blockedStatusUpdateTimer;	// 104 = 0x68
    UIAlertSheet *_alertSheet;	// 108 = 0x6c
    SBAwayInCallController *_inCallController;	// 112 = 0x70
    TPBottomLockBar *_lockBar;	// 116 = 0x74
    TPBottomButtonBar *_cancelSyncBar;	// 120 = 0x78
    UIPushButton *_infoButton;	// 124 = 0x7c
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0002fb00
+ (id)lockLabel:(BOOL)fp8 fontSize:(float *)fp12;	// IMP=0x0002fcd0
- (void)_batteryStatusChanged:(id)fp8;	// IMP=0x0003205c
- (void)_clearBlockedStatusUpdateTimer;	// IMP=0x0002fd84
- (void)_positionAwayItemsView;	// IMP=0x000319a4
- (void)_postLockCompletedNotification;	// IMP=0x000300e4
- (void)_updateBlockedStatus;	// IMP=0x000316f8
- (void)_updateBlockedStatusLabel;	// IMP=0x00031210
- (void)addChargingView;	// IMP=0x00032208
- (void)addDateView;	// IMP=0x00031844
- (void)animateToShowingDeviceLock:(BOOL)fp8;	// IMP=0x00032a38
- (id)chargingView;	// IMP=0x000320a8
- (id)dateView;	// IMP=0x00031780
- (void)dealloc;	// IMP=0x0002ffa8
- (void)dismiss;	// IMP=0x00030174
- (void)finishedAnimatingIn;	// IMP=0x00030104
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;	// IMP=0x00032868
- (BOOL)hasAwayItems;	// IMP=0x00031c38
- (void)hideAwayItems;	// IMP=0x00031b18
- (void)hideChargingView;	// IMP=0x00032248
- (void)hideInfoButton;	// IMP=0x0003053c
- (void)hideNowPlaying;	// IMP=0x00032424
- (void)hideSyncingBottomBar:(BOOL)fp8;	// IMP=0x000323ac
- (id)inCallController;	// IMP=0x000318d4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0002fdc4
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00030f68
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00030fa8
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x00030edc
- (void)musicPlayerDied:(id)fp8;	// IMP=0x00032564
- (id)nowPlayingArtView;	// IMP=0x00032448
- (void)postLockCompletedNotification:(BOOL)fp8;	// IMP=0x0002ff44
- (void)removeAlertSheet;	// IMP=0x00031e98
- (void)removeBlockedStatus;	// IMP=0x000315f0
- (void)removeDateView;	// IMP=0x00031820
- (void)setBottomLockBar:(id)fp8;	// IMP=0x000301f8
- (void)setDimmed:(BOOL)fp8;	// IMP=0x00030d60
- (void)setDrawsBlackBackground:(BOOL)fp8;	// IMP=0x00030e8c
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00030ce4
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;	// IMP=0x00031c5c
- (BOOL)shouldAnimateIn;	// IMP=0x00030240
- (BOOL)shouldShowBlockedRedStatus;	// IMP=0x00031194
- (BOOL)shouldShowInCallInfo;	// IMP=0x00031944
- (void)showAlertSheet:(id)fp8;	// IMP=0x00031d4c
- (void)showAwayItems;	// IMP=0x00031b48
- (void)showBlockedStatus;	// IMP=0x0003158c
- (void)showInfoButton;	// IMP=0x00030320
- (void)showSyncingBottomBar:(BOOL)fp8;	// IMP=0x0003226c
- (void)slideAlertSheetOut:(BOOL)fp8 direction:(BOOL)fp12 duration:(float)fp16;	// IMP=0x00031eec
- (void)startAnimations;	// IMP=0x00030248
- (void)stopAnimations;	// IMP=0x0003028c
- (void)updateInCallInfo;	// IMP=0x00031988
- (void)updateInterface;	// IMP=0x0003055c
- (void)updateLockBarLabel;	// IMP=0x00030fe4
- (BOOL)updateNowPlayingArt;	// IMP=0x000326d4
- (void)updateNowPlayingInfo:(id)fp8;	// IMP=0x00032584

@end

