/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0005a330
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x0005a0bc
- (void)callBack:(id)fp8;	// IMP=0x0005a6f4
- (void)ignore:(id)fp8;	// IMP=0x0005a680
- (void)setAlert:(id)fp8;	// IMP=0x0005a808

@end

