/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class SBCalendarIconContentsView;

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
    SBCalendarIconContentsView *_dateContents;	// 76 = 0x4c
}

- (void)dealloc;	// IMP=0x00045750
- (id)initWithApplication:(id)fp8;	// IMP=0x0004563c
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x000457a4

@end

