/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCalendarAlertItem : SBAlertItem
{
    double _date;	// 12 = 0xc
    NSString *_title;	// 20 = 0x14
    NSString *_location;	// 24 = 0x18
    int _eventId;	// 28 = 0x1c
}

+ (void)adjustOnWake;	// IMP=0x000630b8
+ (void)alarmsDidFire:(id)fp8;	// IMP=0x00062c30
+ (void)alarmsDidSchedule:(id)fp8;	// IMP=0x00062fa4
+ (void)didWakeFromSleep;	// IMP=0x00063078
+ (void)finishRegisteringForAlerts;	// IMP=0x00062b14
+ (void)registerForAlerts;	// IMP=0x00063cb8
+ (void)significantTimeChange;	// IMP=0x00063d68
- (id)_dateString:(BOOL)fp8;	// IMP=0x000631f8
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00063a7c
- (id)awayItem;	// IMP=0x00063b64
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006373c
- (void)dealloc;	// IMP=0x00063154
- (void)didPresentAlertSheet:(id)fp8;	// IMP=0x000639a4
- (id)initWithDate:(double)fp8 title:(id)fp16 location:(id)fp20 eventId:(int)fp24;	// IMP=0x000630cc
- (id)lockLabel;	// IMP=0x00063948
- (void)performUnlockAction;	// IMP=0x00063b04
- (void)revealEvent;	// IMP=0x000639bc
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00063b54
- (BOOL)willShowInAwayItems;	// IMP=0x00063b5c

@end

