/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCallAlertDisplay.h"

@class TPBottomButtonBar, TPCallWaitingButton, TPPushButton;

@interface SBCallWaitingAlertDisplay : SBCallAlertDisplay
{
    TPCallWaitingButton *_ignoreButton;	// 72 = 0x48
    TPCallWaitingButton *_answerButton;	// 76 = 0x4c
    TPPushButton *_answerAndReleaseButton;	// 80 = 0x50
    TPBottomButtonBar *_animatingBottomBar;	// 84 = 0x54
    unsigned int _didRelease:1;	// 88 = 0x58
    unsigned int _didHeldRelease:1;	// 88 = 0x58
    unsigned int _setupForThree:1;	// 88 = 0x58
}

+ (id)_createBottomButtonBarForDisplay:(id)fp8;	// IMP=0x00044054
+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00042f74
- (void)_addCallWaitingButtons:(BOOL)fp8;	// IMP=0x00043d24
- (void)_answerButtonsSwapped;	// IMP=0x00043634
- (void)_bottomBarSwitchDone;	// IMP=0x00043cd0
- (void)_bottomBarSwitchHalfDone;	// IMP=0x00043c1c
- (void)_callCountChanged:(id)fp8;	// IMP=0x0004308c
- (void)_callWaitingControlsFaded;	// IMP=0x000435e8
- (void)_setPhoneFlipBackAttribute;	// IMP=0x000436a0
- (id)additionalURLParameter;	// IMP=0x00043820
- (void)answerAndRelease:(id)fp8;	// IMP=0x00043970
- (void)answerCall:(struct __CTCall *)fp8;	// IMP=0x00043884
- (void)dealloc;	// IMP=0x00042ff0
- (void)dismiss;	// IMP=0x000437b0
- (void)ignore;	// IMP=0x00043730
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x00042e54
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x000439f4
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00043998

@end

