/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@interface SBCalendarIconContentsView : UIView
{
    unsigned int _highlighted:1;	// 28 = 0x1c
}

- (void)dealloc;	// IMP=0x000458b8
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0004596c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000457fc
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x00045928

@end

