/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@interface SBCountDownAlertItem : SBRingingAlertItem
{
}

- (id)avAudioCategory;	// IMP=0x00066694
- (id)avClientName;	// IMP=0x00066688
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00066508
- (id)lockLabel;	// IMP=0x000664ac
- (id)soundIdentifier;	// IMP=0x00066650

@end

