/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x00070380
- (float)delayForOthersActivation;	// IMP=0x00070494
- (void)deviceUnlockCanceled;	// IMP=0x00070338
- (void)deviceUnlockSucceeded;	// IMP=0x000702f0
- (void)dismiss;	// IMP=0x00070438
- (float)durationForOthersActivation;	// IMP=0x0007049c
- (void)useEmergencyCallButton;	// IMP=0x000702ec

@end

