/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */
#ifndef SBDISPLAY_H_
#define SBDISPLAY_H_

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface SBDisplay : NSObject
{
    NSMutableDictionary *_activationValues;	// 4 = 0x4
    NSMutableDictionary *_deactivationValues;	// 8 = 0x8
    int _activationSettings;	// 12 = 0xc
    int _deactivationSettings;	// 16 = 0x10
    NSMutableSet *_suppressVolumeHudCategories;	// 20 = 0x14
    float _autoDimOverride;	// 24 = 0x18
    float _autoLockOverride;	// 28 = 0x1c
    unsigned int _expectsFaceContact:1;	// 32 = 0x20
    unsigned int _disallowTouchPoints:1;	// 32 = 0x20
    unsigned int _accelerometerDeviceOrientationChangedEventsEnabled:1;	// 32 = 0x20
    unsigned int _accelerometerRawEventsEnabled:1;	// 32 = 0x20
    unsigned int _showsProgress:1;	// 32 = 0x20
}

+ (id)defaultValueForKey:(const id)fp8 displayIdentifier:(id)fp12;	// IMP=0x000372bc
+ (void)loadDisplayStates;	// IMP=0x00036f50
+ (void)resetDefaultValuesForDisplayIdentifier:(id)fp8;	// IMP=0x00037324
+ (void)saveDisplayStates;	// IMP=0x000370fc
+ (void)setDefaultValue:(id)fp8 forKey:(const id)fp12 displayIdentifier:(id)fp16;	// IMP=0x00037188
- (BOOL)accelerometerDeviceOrientationChangedEventsEnabled;	// IMP=0x00036a54
- (BOOL)accelerometerRawEventsEnabled;	// IMP=0x00036abc
- (BOOL)activate;	// IMP=0x00036364
- (BOOL)activationSetting:(int)fp8;	// IMP=0x0003618c
- (id)activationSettingsDescription;	// IMP=0x000373c0
- (id)activationValue:(int)fp8;	// IMP=0x00036110
- (BOOL)allowsInCallStatusBar;	// IMP=0x000364f8
- (float)autoDimTime;	// IMP=0x000367fc
- (float)autoLockTime;	// IMP=0x000368c0
- (void)clearActivationSettings;	// IMP=0x00035fd4
- (void)clearDeactivationSettings;	// IMP=0x0003619c
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x00035fac
- (BOOL)deactivate;	// IMP=0x0003636c
- (void)deactivated;	// IMP=0x00036374
- (BOOL)deactivationSetting:(int)fp8;	// IMP=0x000361f8
- (id)deactivationSettingsDescription;	// IMP=0x0003770c
- (id)deactivationValue:(int)fp8;	// IMP=0x000362e8
- (void)dealloc;	// IMP=0x00035f40
- (id)description;	// IMP=0x00036cd8
- (id)displayIdentifier;	// IMP=0x00035fc8
- (void)exitedAbnormally;	// IMP=0x000363ec
- (void)exitedNormally;	// IMP=0x000364f4
- (BOOL)expectsFaceContact;	// IMP=0x000369f0
- (BOOL)kill;	// IMP=0x000363e4
- (void)setAccelerometerDeviceOrientationChangedEventsEnabled:(BOOL)fp8;	// IMP=0x000369fc
- (void)setAccelerometerRawEventsEnabled:(BOOL)fp8;	// IMP=0x00036a64
- (void)setActivationSetting:(int)fp8 flag:(BOOL)fp12;	// IMP=0x00036004
- (void)setActivationSetting:(int)fp8 value:(id)fp12;	// IMP=0x00036030
- (void)setAutoDimTime:(float)fp8;	// IMP=0x000368b8
- (void)setAutoLockTime:(float)fp8;	// IMP=0x0003697c
- (void)setDeactivationSetting:(int)fp8 flag:(BOOL)fp12;	// IMP=0x000361cc
- (void)setDeactivationSetting:(int)fp8 value:(id)fp12;	// IMP=0x00036208
- (void)setExpectsFaceContact:(BOOL)fp8;	// IMP=0x00036984
- (void)setShowsProgress:(BOOL)fp8;	// IMP=0x00036acc
- (void)setSystemVolumeHUDEnabled:(BOOL)fp8 forCategory:(id)fp12;	// IMP=0x00036af4
- (void)setTouchPointsAllowed:(BOOL)fp8;	// IMP=0x00036c7c
- (BOOL)showSystemVolumeHUDForCategory:(id)fp8;	// IMP=0x00036c18
- (BOOL)showsProgress;	// IMP=0x00036ae4
- (int)statusBarMode;	// IMP=0x00036730
- (int)statusBarOrientation;	// IMP=0x000367c0
- (BOOL)touchPointsAllowed;	// IMP=0x00036cc4
- (void)updateStatusBar:(float)fp8;	// IMP=0x00036704
- (void)updateStatusBar:(float)fp8 fence:(int)fp12 animation:(int)fp16;	// IMP=0x000365d4

@end

#endif /*SBDISPLAY_H_*/