/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBDismissOnlyAlertItem : SBAlertItem
{
    NSString *_title;	// 12 = 0xc
    NSString *_body;	// 16 = 0x10
    double _autoDismissInterval;	// 20 = 0x14
    BOOL _hasDeactivated;	// 28 = 0x1c
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006b8c8
- (double)autoDismissInterval;	// IMP=0x0006b790
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006b900
- (void)dealloc;	// IMP=0x0006b730
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x0006ba3c
- (void)dismiss;	// IMP=0x0006b888
- (BOOL)hasDeactivated;	// IMP=0x0006ba48
- (id)initWithTitle:(id)fp8 body:(id)fp12;	// IMP=0x0006b6b0
- (id)lockLabel;	// IMP=0x0006b9e0
- (void)performUnlockAction;	// IMP=0x0006b8e4
- (void)setAutoDismissInterval:(double)fp8;	// IMP=0x0006b79c
- (void)setBodyText:(id)fp8;	// IMP=0x0006b818
- (void)setTitle:(id)fp8;	// IMP=0x0006b7a8

@end

