/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPushButton.h"

@class NSString;

@interface SBEmergencyCallButton : UIPushButton
{
    NSString *_subtitle;	// 84 = 0x54
}

+ (struct __GSFont *)defaultFont;	// IMP=0x0005ec18
- (void)dealloc;	// IMP=0x0005ec90
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x0005ed2c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0005ec2c
- (void)setSubtitle:(id)fp8;	// IMP=0x0005ece4

@end

