/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBLowPowerAlertItem : SBAlertItem
{
    unsigned int _talkMinutesLeft;	// 12 = 0xc
    unsigned int _talkLevel;	// 16 = 0x10
}

+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)fp8;	// IMP=0x000657b4
+ (unsigned int)_thresholdForLevel:(unsigned int)fp8;	// IMP=0x0006577c
+ (void)saveLowBatteryLog;	// IMP=0x00064dec
+ (void)savePowerDiagnosisLogWithCurrentCapacity:(int)fp8 startCapacity:(int)fp12;	// IMP=0x000652b0
+ (void)setBatteryLevel:(unsigned int)fp8;	// IMP=0x0006584c
+ (id)systemVersionDescription;	// IMP=0x00064c84
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00065c1c
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00065a98
- (id)initWithTalkTimeLeft:(unsigned int)fp8 level:(unsigned int)fp12;	// IMP=0x0006572c
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00065c6c
- (BOOL)shouldShowInLockScreen;	// IMP=0x00065c64
- (BOOL)undimsScreen;	// IMP=0x00065c74

@end

