/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBApplication, UIWindow;

@interface SBMiniAlertController : NSObject
{
    SBApplication *_displayShowingAnAlert;	// 4 = 0x4
    UIWindow *_dimmingWindow;	// 8 = 0x8
    unsigned int _dontAskApps:1;	// 12 = 0xc
    unsigned int _reserved:31;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x0005de70
- (BOOL)canShowAlerts;	// IMP=0x0005e8ec
- (void)deactivateAlertItemsWithBundleIdentifier:(id)fp8;	// IMP=0x0005e39c
- (id)dimImageForKeyboard:(BOOL)fp8;	// IMP=0x0005dec0
- (void)display:(id)fp8 willDismissMiniAlert:(int *)fp12 andShowAnother:(BOOL)fp16;	// IMP=0x0005e4e0
- (void)display:(id)fp8 willDisplayMiniAlert:(int *)fp12;	// IMP=0x0005e40c
- (void)displayDidDisableMiniAlerts:(id)fp8;	// IMP=0x0005e60c
- (id)displayShowingAnAlert;	// IMP=0x0005e4c0
- (void)finishedAnimatingDimWindowOut:(id)fp8 didFinish:(id)fp12;	// IMP=0x0005e1f0
- (void)hideApplicationMiniAlerts;	// IMP=0x0005e760
- (void)hideDimmingWindow:(int)fp8;	// IMP=0x0005e280
- (void)noteMiniAlertStateChanged;	// IMP=0x0005e7e4
- (void)setShouldAskApps:(BOOL)fp8;	// IMP=0x0005e4c8
- (void)showApplicationMiniAlertsIfNeeded;	// IMP=0x0005e670
- (void)showDimmingWindow:(int)fp8;	// IMP=0x0005dfd4

@end

