/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBMobilityManagementAlert : SBAlert
{
}

+ (void)registerForAlerts;	// IMP=0x00057ab0
+ (void)test;	// IMP=0x00057d1c

@end

