/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert
{
    int _count;	// 48 = 0x30
    id _delegate;	// 52 = 0x34
    SBPowerDownView *_powerDownView;	// 56 = 0x38
    BOOL _isFront;	// 60 = 0x3c
}

+ (id)sharedInstance;	// IMP=0x0003f578
- (void)activate;	// IMP=0x0003f73c
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0003f7f0
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0003f80c
- (float)autoLockTime;	// IMP=0x0003f61c
- (void)cancel;	// IMP=0x0003f83c
- (BOOL)deactivate;	// IMP=0x0003f7a8
- (void)dealloc;	// IMP=0x0003f5c8
- (BOOL)isOrderedFront;	// IMP=0x0003f628
- (void)orderFront;	// IMP=0x0003f630
- (void)orderOut;	// IMP=0x0003f640
- (void)powerDown;	// IMP=0x0003f818
- (id)powerDownView;	// IMP=0x0003f660
- (void)setDelegate:(id)fp8;	// IMP=0x0003f810

@end

