/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBRestoreFailureAlertItem : SBAlertItem
{
}

- (void)_rebootNow;	// IMP=0x00071d60
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00071e08
- (BOOL)allowMenuButtonDismissal;	// IMP=0x00071e58
- (double)autoDismissInterval;	// IMP=0x00071d50
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00071c14
- (void)performUnlockAction;	// IMP=0x00071db8
- (void)restartSystemEvent;	// IMP=0x00071d74
- (BOOL)shouldShowInLockScreen;	// IMP=0x00071e60

@end

