/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitAlert.h"

@interface SBSIMToolkitAlert (PhoneAlert)
- (struct __CFString *)callPriority;	// IMP=0x0004e0fc
- (struct __CFString *)displayTextPriority;	// IMP=0x0004e138
- (id)inCallText;	// IMP=0x0004e200
- (id)phoneNumber;	// IMP=0x0004e1c4
- (BOOL)shouldRedial;	// IMP=0x0004e174
@end

