/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBSIMToolkitAlert : SBAlert
{
    BOOL _needsResponse;	// 48 = 0x30
    NSTimer *_timeoutTimer;	// 52 = 0x34
}

+ (void)_idleScreenShown:(id)fp8;	// IMP=0x0004d9a8
+ (void)_restartMonitor;	// IMP=0x0004dd68
+ (void)_startSTKMonitor;	// IMP=0x0004dac4
+ (void)_stopSTKMonitor;	// IMP=0x0004da20
+ (id)currentAlert;	// IMP=0x0004d634
+ (void)registerForAlerts;	// IMP=0x0004dd9c
+ (void)setCurrentAlert:(id)fp8;	// IMP=0x0004d5e8
+ (struct __CTServerConnection *)simToolkitServerConnection;	// IMP=0x0004ca6c
+ (void)test;	// IMP=0x0004d864
+ (void)userEventOccurred;	// IMP=0x0004ca8c
+ (BOOL)wantsNextUserEvent;	// IMP=0x0004ca7c
- (BOOL)_delayEnabled;	// IMP=0x0004dea4
- (void)_playTone:(struct __CFString *)fp8 forDuration:(float)fp12;	// IMP=0x0004cda4
- (void)_stopTone:(id)fp8;	// IMP=0x0004cc74
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0004d668
- (void)clearTimeoutTimer;	// IMP=0x0004de64
- (void)dealloc;	// IMP=0x0004cd54
- (void)displayDidTimeout;	// IMP=0x0004e070
- (BOOL)needsResponse;	// IMP=0x0004cad8
- (void)restartTimeoutTimer:(float)fp8;	// IMP=0x0004defc
- (void)sendResponse:(struct __CFString *)fp8;	// IMP=0x0004cbf8
- (void)sendResponse:(struct __CFString *)fp8 withBool:(BOOL)fp12;	// IMP=0x0004cb6c
- (void)sendResponse:(struct __CFString *)fp8 withString:(id)fp12;	// IMP=0x0004cae0
- (BOOL)sendResponseUponDisplay;	// IMP=0x0004ccfc
- (void)setNeedsResponse:(BOOL)fp8;	// IMP=0x0004cad0
- (void)startTimeoutTimerIfNecessary;	// IMP=0x0004df8c
- (struct __CFString *)toolkitAlertType;	// IMP=0x0004d644

@end

