/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertInputView.h"

@interface SBSIMToolkitGetInputDisplay : SBAlertInputView
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x0004ef38
- (void)displayDidTimeout;	// IMP=0x0004f1c8
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0004eeb4
- (void)sbAlertInputViewCancelClicked:(id)fp8;	// IMP=0x0004f2b4
- (void)sbAlertInputViewSendClicked:(id)fp8;	// IMP=0x0004f21c

@end

