/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitTextAlertDisplay.h"

@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x000504a8
- (id)_activeCalls;	// IMP=0x0004fe0c
- (id)alertText;	// IMP=0x00050158
- (void)dial:(id)fp8;	// IMP=0x0004fe30
- (void)dismiss:(id)fp8;	// IMP=0x0004fdb8

@end

