/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject
{
    BOOL _isInitialUpdate;	// 4 = 0x4
    int _status;	// 8 = 0x8
    SBSIMLockAlertItem *_currentAlert;	// 12 = 0xc
    SBSIMLockEntryAlert *_lockEntryAlert;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00060b78
- (int)_CTToSBSIMStatus:(struct __CFString *)fp8;	// IMP=0x00060ca4
- (BOOL)_hopelesslyPUKLocked;	// IMP=0x00060c7c
- (void)_initialUpdate;	// IMP=0x00061500
- (int)_statusFromCT;	// IMP=0x00060e1c
- (void)_tearDownAlertAndUpdateStatus;	// IMP=0x00061260
- (void)_tryToUpdateStatus;	// IMP=0x000611e4
- (void)_updateSIMStatus:(struct __CFString *)fp8 withOptions:(struct __CFDictionary *)fp12;	// IMP=0x000612e0
- (void)_updateToStatus:(int)fp8;	// IMP=0x00060f90
- (void)alertItemDismissed:(id)fp8;	// IMP=0x00060e7c
- (void)attemptUnlock;	// IMP=0x00060f40
- (void)dealloc;	// IMP=0x00060bc8
- (void)lockEntryAlertDismissed:(id)fp8;	// IMP=0x00060e48
- (int)pinLockAttemptsRemaining;	// IMP=0x00061450
- (int)pukLockAttemptsRemaining;	// IMP=0x00061460
- (void)registerForAlerts;	// IMP=0x0006154c
- (void)repopAlert;	// IMP=0x00060eb0
- (int)status;	// IMP=0x0006167c

@end

