/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMLockEntryAlertDisplay.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertDisplay : SBSIMLockEntryAlertDisplay
{
    int _state;	// 72 = 0x48
    NSString *_enteredPUKCode;	// 76 = 0x4c
    NSString *_newPIN;	// 80 = 0x50
}

- (void)_attemptPUKUnlock;	// IMP=0x00064a0c
- (id)_pukAttemptsRemainingLabel;	// IMP=0x00064570
- (void)dealloc;	// IMP=0x00064510
- (id)label;	// IMP=0x0006494c
- (void)setupFailureState;	// IMP=0x00064828
- (void)setupSuccess;	// IMP=0x00064670
- (id)titleText;	// IMP=0x0006474c
- (void)unlock;	// IMP=0x00064a24

@end

