/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUSSDAlert.h"

@interface SBSMSClass0Alert : SBUSSDAlert
{
}

+ (void)registerForAlerts;	// IMP=0x0004c9a0
- (void)_registerForNotifications;	// IMP=0x0004c9f0
- (void)_unregisterForNotifications;	// IMP=0x0004c9ec
- (id)initWithString:(id)fp8;	// IMP=0x0004c9f4

@end

