/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBSMSAlertItem : SBAlertItem
{
    struct __CTSMSMessage *_message;	// 12 = 0xc
}

+ (void)prefsChanged;	// IMP=0x000601c8
- (void)_deactivateAllTaggedSMSAlertItems;	// IMP=0x0005fdec
- (void)_playMessageReceived;	// IMP=0x0005ff90
- (BOOL)_showSMSPreviewWithPasscodeEnabled;	// IMP=0x000601dc
- (void)_tag;	// IMP=0x0005fcdc
- (void)_untag;	// IMP=0x0005fdac
- (id)address;	// IMP=0x0005ffdc
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00060178
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00060250
- (void)dealloc;	// IMP=0x0005fc8c
- (void)didActivate;	// IMP=0x0005ff04
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x0005ff2c
- (void)dismiss;	// IMP=0x00060138
- (id)lockLabel;	// IMP=0x00060604
- (id)messageText;	// IMP=0x00060018
- (void)performUnlockAction;	// IMP=0x000601ac
- (void)reply;	// IMP=0x00060054
- (void)setMessage:(struct __CTSMSMessage *)fp8;	// IMP=0x0005ff48
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00060668
- (void)willActivate;	// IMP=0x0005fee8
- (void)willPresentAlertSheet:(id)fp8;	// IMP=0x0005ffa8
- (BOOL)willShowInAwayItems;	// IMP=0x00060660

@end

