/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSoundPreferences : NSObject
{
}

+ (id)calendarAlarmPath;	// IMP=0x000481f8
+ (BOOL)playLockSound;	// IMP=0x000482bc
+ (id)ringtonePath;	// IMP=0x00048238
+ (BOOL)shouldVibrateForCurrentRingerState;	// IMP=0x0004850c
+ (void)userDefaultsDidChanged:(id)fp8;	// IMP=0x00048118
+ (id)vibratePattern;	// IMP=0x00048320
+ (BOOL)vibrateWhenRinging;	// IMP=0x00048444
+ (BOOL)vibrateWhenSilent;	// IMP=0x000484a8

@end

