/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class SBStatusBarOperatorNameView, UIImage;

@interface SBStatusBarCarrierView : SBStatusBarContentView
{
    UIImage *_operatorIcon;	// 36 = 0x24
    SBStatusBarOperatorNameView *_operatorNameView;	// 40 = 0x28
    BOOL _operatorNameIsLooping;	// 44 = 0x2c
}

- (BOOL)_operatorName:(id)fp8 isEqualToName:(id)fp12;	// IMP=0x00038a04
- (void)clearLastOperatorNameLooped;	// IMP=0x000380ec
- (void)dealloc;	// IMP=0x00037f14
- (struct CGSize)defaultSize;	// IMP=0x00038974
- (void)finishedLoopingOperatorName:(id)fp8 didFinish:(id)fp12;	// IMP=0x00038360
- (id)init;	// IMP=0x00038bcc
- (void)loopIfNecessary;	// IMP=0x000384a8
- (void)loopOperatorNameToBeginning:(id)fp8 didFinish:(id)fp12;	// IMP=0x00038148
- (void)loopOperatorNameToEnd;	// IMP=0x00038224
- (id)operatorIconForName:(id)fp8;	// IMP=0x00038840
- (void)operatorNameChanged;	// IMP=0x000389ac
- (void)setOperatorName:(id)fp8;	// IMP=0x00038524
- (void)start;	// IMP=0x00037f74
- (void)startOperatorNameLooping:(id)fp8;	// IMP=0x0003843c
- (void)stop;	// IMP=0x00038058

@end

