/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class UIImage, UIImageView;

@interface SBStatusBarBluetoothView : SBStatusBarContentView
{
    UIImage *_icon;	// 36 = 0x24
    BOOL _animating;	// 40 = 0x28
    UIImageView *_activeView;	// 44 = 0x2c
    UIImageView *_baseLayer;	// 48 = 0x30
    BOOL _isStarted;	// 52 = 0x34
}

+ (void)initialize;	// IMP=0x0005db74
- (void)_btConnectionStatusChanged:(id)fp8;	// IMP=0x0005da78
- (void)_btDeviceConnected;	// IMP=0x0005d958
- (void)_btDeviceDisconnected:(id)fp8;	// IMP=0x0005daec
- (void)_btPowerPrefChanged:(id)fp8;	// IMP=0x0005dcdc
- (void)_btStatusChanged:(id)fp8;	// IMP=0x0005d724
- (int)_effectiveMode;	// IMP=0x0005d5ac
- (void)_setupActiveView;	// IMP=0x0005d5cc
- (void)_start;	// IMP=0x0005dbe0
- (void)animationDidStop:(id)fp8;	// IMP=0x0005db0c
- (int)btStatus;	// IMP=0x0005d6ac
- (void)dealloc;	// IMP=0x0005ddbc
- (id)icon;	// IMP=0x0005d548
- (id)init;	// IMP=0x0005d550
- (void)start;	// IMP=0x0005dcf8
- (void)stop;	// IMP=0x0005dd74

@end

