/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBStatusBarAirPortView, SBStatusBarBatteryView, SBStatusBarBluetoothView, SBStatusBarCarrierView, SBStatusBarController, SBStatusBarIndicatorsView, SBStatusBarNoServiceView, SBStatusBarProgressView, SBStatusBarSignalView, SBStatusBarTimeView;

@interface SBStatusBarContentsView : UIView
{
    SBStatusBarController *_controller;	// 28 = 0x1c
    int _mode;	// 32 = 0x20
    BOOL _dimmed;	// 36 = 0x24
    UIView *_lockIconView;	// 40 = 0x28
    SBStatusBarTimeView *_timeView;	// 44 = 0x2c
    SBStatusBarBatteryView *_batteryView;	// 48 = 0x30
    SBStatusBarSignalView *_signalView;	// 52 = 0x34
    SBStatusBarCarrierView *_carrierView;	// 56 = 0x38
    SBStatusBarIndicatorsView *_indicatorsView;	// 60 = 0x3c
    SBStatusBarAirPortView *_airPortView;	// 64 = 0x40
    SBStatusBarNoServiceView *_noServiceView;	// 68 = 0x44
    SBStatusBarBluetoothView *_bluetoothView;	// 72 = 0x48
    SBStatusBarProgressView *_progressView;	// 76 = 0x4c
}

+ (float)contentAlphaForMode:(int)fp8;	// IMP=0x000280b4
- (void)buildContentViews;	// IMP=0x00027f34
- (void)cloakChanged;	// IMP=0x00028cac
- (void)customTextChanged;	// IMP=0x00028c6c
- (void)dealloc;	// IMP=0x00027e64
- (void)indicatorsChanged;	// IMP=0x00028d60
- (id)initWithStatusBarController:(id)fp8 mode:(int)fp12;	// IMP=0x00027d54
- (void)loopCarrierNameIfNecessary;	// IMP=0x00028f44
- (void)progressChanged;	// IMP=0x00028c8c
- (void)reflowContentViews;	// IMP=0x000280d8
- (void)setAirPortStrength:(int)fp8;	// IMP=0x00028d00
- (void)setIsInAirplaneMode:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x00028e30
- (void)setShowsAirPort:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x00028d20
- (void)setShowsService:(BOOL)fp8 SIMStatus:(id)fp12;	// IMP=0x000289a4
- (void)signalFormatChanged;	// IMP=0x00028c4c
- (void)significantTimeChange;	// IMP=0x00028c14
- (void)start;	// IMP=0x000288a8
- (void)startClock;	// IMP=0x0002894c
- (void)stop;	// IMP=0x00028824
- (void)stopClock;	// IMP=0x0002892c
- (void)updateClockFormat;	// IMP=0x0002896c
- (void)updateContentViewsAlpha;	// IMP=0x00028f64

@end

