/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString, SBStatusBar, SBStatusBarContentsView, UIWindow;

@interface SBStatusBarController : NSObject
{
    UIWindow *_slidingStatusBarWindow;	// 4 = 0x4
    int _slidingStatusBarAnimation;	// 8 = 0x8
    UIWindow *_animatingCallStatusBarWindow;	// 12 = 0xc
    UIWindow *_leftBottomCorner;	// 16 = 0x10
    UIWindow *_rightBottomCorner;	// 20 = 0x14
    SBStatusBar *_statusBarView;	// 24 = 0x18
    SBStatusBarContentsView *_statusBarContentsView;	// 28 = 0x1c
    SBStatusBar *_transitioningStatusBarView;	// 32 = 0x20
    SBStatusBar *_animatingCallStatusBar;	// 36 = 0x24
    SBStatusBarContentsView *_transitioningStatusBarContentsView;	// 40 = 0x28
    unsigned int _isLocked:1;	// 44 = 0x2c
    unsigned int _lockIsChanging:1;	// 44 = 0x2c
    unsigned int _dimmed:1;	// 44 = 0x2c
    unsigned int _showDimmerOverlay:1;	// 44 = 0x2c
    unsigned int _animating:1;	// 44 = 0x2c
    unsigned int _isInCall:1;	// 44 = 0x2c
    unsigned int _airplaneMode:1;	// 44 = 0x2c
    unsigned int _showsProgress:1;	// 44 = 0x2c
    unsigned int _cloakStatusBar:1;	// 45 = 0x2d
    unsigned int _showAirport:1;	// 45 = 0x2d
    unsigned int _animateDefaultStatusBarDown:1;	// 45 = 0x2d
    unsigned int _animateDefaultStatusBarUp:1;	// 45 = 0x2d
    NSMutableArray *_statusBarIndicatorNames;	// 48 = 0x30
    int _mode;	// 52 = 0x34
    int _orientation;	// 56 = 0x38
    int _animatingCallStatusBarOrientation;	// 60 = 0x3c
    NSString *_customText;	// 64 = 0x40
    int _airPortSignalStrength;	// 68 = 0x44
    int _queuedStatusBarMode;	// 72 = 0x48
    int _queuedStatusBarOrientation;	// 76 = 0x4c
    float _duration;	// 80 = 0x50
    BOOL _telephonyControllerCheckedIn;	// 84 = 0x54
    BOOL _bluetoothControllerCheckedIn;	// 85 = 0x55
}

+ (BOOL)isLikeAFullScreenStatusBar:(int)fp8;	// IMP=0x0002969c
+ (id)sharedStatusBarController;	// IMP=0x000291b4
+ (id)statusBarImageNamed:(id)fp8 forMode:(int)fp12;	// IMP=0x0002a788
- (void)_SIMOrServiceStatusChanged;	// IMP=0x00029c84
- (id)_SIMStatus;	// IMP=0x00029c14
- (void)_SIMStatusChanged:(id)fp8;	// IMP=0x00029cfc
- (void)_finishStatusBarAnimation;	// IMP=0x0002a334
- (BOOL)_isServiceAvailable;	// IMP=0x00029b78
- (void)_serviceStatusChanged:(id)fp8;	// IMP=0x00029d18
- (void)_setStatusBarSize:(BOOL)fp8;	// IMP=0x0002b5f4
- (void)_setTransitionalStatusBarSize:(BOOL)fp8;	// IMP=0x0002b4d8
- (void)addStatusBarItem:(id)fp8;	// IMP=0x000293c8
- (int)airPortStrength;	// IMP=0x0002a008
- (BOOL)airplaneModeIsEnabled;	// IMP=0x00029e00
- (void)animateDefaultStatusBarDown;	// IMP=0x00029aec
- (void)animateDefaultStatusBarUp:(int)fp8;	// IMP=0x00029b0c
- (float)animationDuration;	// IMP=0x0002a780
- (BOOL)bluetoothControllerCheckedIn;	// IMP=0x0002ab14
- (void)checkInController:(int)fp8;	// IMP=0x0002aaac
- (BOOL)cloakStatusBar;	// IMP=0x0002a080
- (id)customText;	// IMP=0x00029ea0
- (void)dealloc;	// IMP=0x00029204
- (BOOL)dimmed;	// IMP=0x00029618
- (void)endCallStatusBarAnimationFinished;	// IMP=0x00029960
- (void)finishSwitching;	// IMP=0x0002a0e0
- (id)init;	// IMP=0x0002c2e4
- (BOOL)isAnimatingStatusBarDown;	// IMP=0x00029afc
- (BOOL)isAnimatingStatusBarUp;	// IMP=0x00029b68
- (BOOL)isInCall;	// IMP=0x00029adc
- (BOOL)isLockChanging;	// IMP=0x00029528
- (BOOL)isLocked;	// IMP=0x0002951c
- (void)lockCurrentStatusBarForAnimation;	// IMP=0x0002a4ac
- (void)loopCarrierNameIfNecessary;	// IMP=0x0002ab1c
- (void)orderStatusBarFront;	// IMP=0x0002a260
- (void)preheatStatusBarForMode:(int)fp8 orientation:(int)fp12;	// IMP=0x0002c7c0
- (void)releaseLockedStatusBarForAnimationForDisplay:(id)fp8;	// IMP=0x0002a554
- (void)removeStatusBarItem:(id)fp8;	// IMP=0x00029e10
- (void)resizeStatusBar:(float)fp8 grow:(BOOL)fp12;	// IMP=0x0002ba7c
- (void)restoreLevels;	// IMP=0x0002a1e8
- (void)setAirPortStrength:(int)fp8;	// IMP=0x00029f10
- (void)setAirplaneModeIsEnabled:(BOOL)fp8;	// IMP=0x00029d34
- (void)setCloakStatusBar:(BOOL)fp8;	// IMP=0x0002a028
- (void)setCustomText:(id)fp8;	// IMP=0x00029ea8
- (void)setDimmed:(BOOL)fp8;	// IMP=0x00029538
- (void)setIsInCall:(BOOL)fp8;	// IMP=0x000299c0
- (void)setIsLocked:(BOOL)fp8;	// IMP=0x000294b4
- (void)setShowDimmerOverlay:(BOOL)fp8;	// IMP=0x00029638
- (void)setShowsAirPort:(BOOL)fp8;	// IMP=0x00029f74
- (void)setStatusBarMode:(int)fp8 orientation:(int)fp12 duration:(float)fp16 fenceID:(int)fp20 animation:(int)fp24;	// IMP=0x0002ab3c
- (void)setupWindowForSlidingStatusBar:(id)fp8 overStatusBar:(id)fp12;	// IMP=0x00029794
- (BOOL)showDimmerOverlay;	// IMP=0x00029628
- (BOOL)showsAirPort;	// IMP=0x00029fe0
- (BOOL)showsProgress;	// IMP=0x0002a0bc
- (void)signalFormatChanged;	// IMP=0x0002aa7c
- (void)significantTimeChange;	// IMP=0x0002aa2c
- (void)statusBarDidFinishAnimatingDown;	// IMP=0x0002a1d8
- (void)statusBarDidFinishAnimatingUp;	// IMP=0x0002a250
- (id)statusBarIndicatorNames;	// IMP=0x00029e98
- (int)statusBarMode;	// IMP=0x0002a770
- (int)statusBarOrientation;	// IMP=0x0002a778
- (id)statusBarView;	// IMP=0x000293b8
- (id)statusBarWindow;	// IMP=0x00029398
- (void)switchBackstopFrom:(int)fp8 to:(int)fp12 fromOrientation:(int)fp16 toOrientation:(int)fp20 duration:(float)fp24 fenceID:(int)fp28 animation:(int)fp32;	// IMP=0x0002c7f4
- (void)tearDownWindowForSlidingStatusBar:(id)fp8 overStatusBar:(id)fp12;	// IMP=0x000296c4
- (BOOL)telephonyControllerCheckedIn;	// IMP=0x0002ab0c
- (id)transitioningStatusBarView;	// IMP=0x000293c0
- (void)updateClockFormat;	// IMP=0x0002aa5c
- (void)updateProgressVisibility;	// IMP=0x0002a08c

@end

