/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class SBStatusBarContentsView, SBStatusBarController, SBStatusBarInCallView, SBStatusWindow, UIView;

@interface SBStatusBar : UIControl
{
    int _mode;	// 52 = 0x34
    int _orientation;	// 56 = 0x38
    SBStatusBarController *_controller;	// 60 = 0x3c
    SBStatusBarContentsView *_contentsView;	// 64 = 0x40
    SBStatusBarInCallView *_inCallView;	// 68 = 0x44
    SBStatusWindow *_statusWindow;	// 72 = 0x48
    UIView *_airplaneView;	// 76 = 0x4c
    UIView *_glowView;	// 80 = 0x50
    UIView *_glassView;	// 84 = 0x54
    UIView *_dimmerView;	// 88 = 0x58
    unsigned int _animate:1;	// 92 = 0x5c
    unsigned int _animating:1;	// 92 = 0x5c
    unsigned int _isPressed:1;	// 92 = 0x5c
    unsigned int _airplaneMode:1;	// 92 = 0x5c
}

- (id)airplaneView;	// IMP=0x00016fc0
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x0001766c
- (id)contentsView;	// IMP=0x00016f4c
- (void)dealloc;	// IMP=0x00016e80
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x000170d8
- (id)initWithStatusBarController:(id)fp8 mode:(int)fp12 orientation:(int)fp16;	// IMP=0x00016a2c
- (BOOL)isDimmed;	// IMP=0x000176d4
- (int)mode;	// IMP=0x00016f3c
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x000177a0
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x00017854
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x00017904
- (int)orientation;	// IMP=0x00016f44
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x000179b8
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x00017238
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x00017624
- (void)setStatusWindow:(id)fp8;	// IMP=0x00016e70
- (void)showDimmerOverlay:(BOOL)fp8;	// IMP=0x000173f0
- (void)start;	// IMP=0x00017384
- (void)startGlowAnimation;	// IMP=0x00017444
- (void)statusBarClicked;	// IMP=0x00017714
- (id)statusWindow;	// IMP=0x00016e78
- (void)stop;	// IMP=0x000173c0
- (void)stopGlowAnimation;	// IMP=0x000175e8

@end

