/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class UIView;

@interface SBStatusWindow : UIWindow
{
    int _orientation;	// 64 = 0x40
    UIView *_holderView;	// 68 = 0x44
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x00017c18
- (id)holderView;	// IMP=0x00017d50
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00017c44
- (BOOL)isOpaque;	// IMP=0x00017c3c
- (int)orientation;	// IMP=0x00017d40
- (void)setOrientation:(int)fp8;	// IMP=0x00017d48

@end

