/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString, NSTimer;

@interface SBStatusBarTimeView : SBStatusBarContentView
{
    NSTimer *_dateTimer;	// 36 = 0x24
    NSString *_time;	// 40 = 0x28
    struct CGRect _textRect;	// 44 = 0x2c
}

- (void)dealloc;	// IMP=0x00038f04
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x000390b4
- (id)init;	// IMP=0x00038e04
- (void)start;	// IMP=0x00038f68
- (void)stop;	// IMP=0x00039074
- (void)tile;	// IMP=0x00039118
- (void)updateClockFormat;	// IMP=0x00038e94

@end

