/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSyncController : NSObject
{
    int _syncState;	// 4 = 0x4
    int _restoreState;	// 8 = 0x8
    int _resetState;	// 12 = 0xc
    int _sofwareUpdateState;	// 16 = 0x10
    struct __CFMachPort *_backupAgentCFPort;	// 20 = 0x14
}

+ (id)sharedInstance;	// IMP=0x0006c65c
- (void)_delayedTurnOffRadio;	// IMP=0x0006d100
- (void)_invalidateBackupAgentCFPort;	// IMP=0x0006d354
- (void)_notifyAppsSyncWillBegin;	// IMP=0x0006cb08
- (void)_notifyRestoreCanProceed;	// IMP=0x0006cd18
- (void)_rebootNow;	// IMP=0x0006cf30
- (BOOL)_setupBackupAgentPort;	// IMP=0x0006d3c4
- (void)beginResetting;	// IMP=0x0006d178
- (void)beginRestoring;	// IMP=0x0006cd48
- (void)beginSyncing;	// IMP=0x0006cbf4
- (void)cancelRestoring;	// IMP=0x0006cf24
- (void)cancelSyncing;	// IMP=0x0006caa8
- (void)dealloc;	// IMP=0x0006c6ac
- (void)didEndResetting;	// IMP=0x0006d20c
- (void)didEndRestoring:(int)fp8;	// IMP=0x0006cf60
- (void)didEndSyncing;	// IMP=0x0006c928
- (void)didShowSyncPanel;	// IMP=0x0006cb38
- (void)finishEndRestoring;	// IMP=0x0006cf44
- (void)finishedTerminatingApplications;	// IMP=0x0006ce5c
- (void)frontLockedWhenPossible;	// IMP=0x0006cb54
- (void)iTunesSyncHasCompleted:(int)fp8;	// IMP=0x0006ccb8
- (void)iTunesSyncRequestedStart;	// IMP=0x0006cc94
- (BOOL)isResetting;	// IMP=0x0006d0e0
- (BOOL)isRestoring;	// IMP=0x0006ccf8
- (BOOL)isSoftwareUpdating;	// IMP=0x0006d468
- (BOOL)isSyncing;	// IMP=0x0006c8f4
- (int)resetState;	// IMP=0x0006d0f8
- (int)restoreState;	// IMP=0x0006cd10
- (void)resumeSyncing;	// IMP=0x0006ca00
- (void)setSoftwareUpdateState:(int)fp8;	// IMP=0x0006d460
- (void)showPreSoftwareUpdateScreen;	// IMP=0x0006d510
- (void)startObserving;	// IMP=0x0006c6fc
- (void)stopObserving;	// IMP=0x0006c824
- (void)suspendSyncing;	// IMP=0x0006c9ac
- (int)syncState;	// IMP=0x0006c920

@end

