/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSString;

@interface SBTTYPromptAlert : SBAlert
{
    NSString *_number;	// 48 = 0x30
    int _uid;	// 52 = 0x34
}

+ (BOOL)dialNumberPromptingIfNecessary:(id)fp8 addressBookUID:(int)fp12 urlAddition:(id)fp16;	// IMP=0x0005cd04
+ (void)displayForNumber:(id)fp8 addressBookUID:(int)fp12;	// IMP=0x0005cc84
- (int)addressBookUID;	// IMP=0x0005cf08
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0005cea8
- (void)dealloc;	// IMP=0x0005cc30
- (id)initWithNumber:(id)fp8 addressBookUID:(int)fp12;	// IMP=0x0005cba4
- (id)number;	// IMP=0x0005cf00

@end

