/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0005d1ac
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x0005d104
- (void)_chooseTTYMode:(id)fp8;	// IMP=0x0005d4a4
- (void)_chooseVoiceMode:(id)fp8;	// IMP=0x0005d450
- (void)_ignore:(id)fp8;	// IMP=0x0005d4fc
- (void)_makeCall;	// IMP=0x0005d2bc
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x0005cf10

@end

