/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class SBApplication, SBButtonBar, SBContentLayer, SBIconList, SBZoomView, UIWindow;

@interface SBUIController : NSObject
{
    UIWindow *_window;	// 4 = 0x4
    SBIconList *_iconList;	// 8 = 0x8
    SBButtonBar *_buttonBar;	// 12 = 0xc
    SBContentLayer *_contentLayer;	// 16 = 0x10
    SBZoomView *_zoomLayer;	// 20 = 0x14
    SBApplication *_launchedApp;	// 24 = 0x18
    int _launchState;	// 28 = 0x1c
    BOOL _lastVolumeDownToControl;	// 32 = 0x20
    BOOL _shouldAutoLock;	// 33 = 0x21
    int _batteryCapacity;	// 36 = 0x24
    BOOL _isBatteryCharging;	// 40 = 0x28
    BOOL _isOnAC;	// 41 = 0x29
    BOOL _cancelingLaunch;	// 42 = 0x2a
    int _batteryLoggingStartCapacity;	// 44 = 0x2c
    unsigned char _headsetBatteryCapacity;	// 48 = 0x30
    BOOL _isHeadsetCharging;	// 49 = 0x31
    BOOL _isHeadsetDocked;	// 50 = 0x32
}

+ (int)displayedLevelForBatteryLevel:(int)fp8;	// IMP=0x0000aaf0
+ (int)displayedLevelForBatteryStatusBarLevel:(int)fp8;	// IMP=0x0000ad8c
+ (id)sharedInstance;	// IMP=0x0000b560
- (void)ACPowerChanged;	// IMP=0x0000dc50
- (void)_indicateConnectedToPower;	// IMP=0x0000aad8
- (struct CGAffineTransform)_initialStatusBarTransformForScale:(float)fp8;	// IMP=0x0000cbf8
- (double)animateLaunchForReturnToLastApp:(id)fp8;	// IMP=0x0000d510
- (void)animateLaunchIcon:(id)fp8;	// IMP=0x0000d424
- (void)animateLaunchOfApplication:(id)fp8;	// IMP=0x0000d3bc
- (void)animateLaunchOfApplication:(id)fp8 afterDelay:(double)fp12 startingAtTime:(double)fp20 forDuration:(double)fp28 includingIconsAndButtonBar:(BOOL)fp36 initialZoomScale:(float)fp40 fadeInZoom:(BOOL)fp44;	// IMP=0x0000cc68
- (void)applicationExited:(id)fp8;	// IMP=0x0000dc30
- (void)applicationSuspended:(id)fp8;	// IMP=0x0000dc34
- (int)batteryCapacity;	// IMP=0x0000dc38
- (id)buttonBar;	// IMP=0x0000c230
- (float)calculateStartupTime;	// IMP=0x0000b634
- (void)cancelLaunchAnimationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x0000d71c
- (void)cancelLaunchOfApplication:(id)fp8 duration:(double)fp12;	// IMP=0x0000d1d8
- (void)clearZoomLayer;	// IMP=0x0000c124
- (void)clickedMenuButton;	// IMP=0x0000d778
- (void)completeAlertDisplay;	// IMP=0x0000d91c
- (id)contentView;	// IMP=0x0000c1e8
- (void)dealloc;	// IMP=0x0000b5b0
- (void)finishLaunching;	// IMP=0x0000bbb0
- (void)finishedFadingInButtonBar;	// IMP=0x0000d5c4
- (id)getVMstats;	// IMP=0x0000b72c
- (void)handleAccessoryAvailabilityChange:(struct __GSEvent *)fp8 removal:(BOOL)fp12;	// IMP=0x0000dda0
- (void)handleAccessoryEvent:(struct __GSEvent *)fp8;	// IMP=0x0000de08
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x0000dab8
- (unsigned char)headsetBatteryCapacity;	// IMP=0x0000dd98
- (void)hideIconListAndBar:(BOOL)fp8;	// IMP=0x0000c5b0
- (id)iconList;	// IMP=0x0000c238
- (id)init;	// IMP=0x0000ded8
- (BOOL)isBatteryCharging;	// IMP=0x0000dc40
- (BOOL)isHeadsetBatteryCharging;	// IMP=0x0000dd90
- (BOOL)isHeadsetDocked;	// IMP=0x0000dd88
- (BOOL)isOnAC;	// IMP=0x0000dc48
- (int)launchState;	// IMP=0x0000c11c
- (void)lock;	// IMP=0x0000c0fc
- (void)lock:(BOOL)fp8;	// IMP=0x0000bdac
- (void)logStartupData;	// IMP=0x0000b9d8
- (void)noteStatusBarHeightChanged:(float)fp8 duration:(double)fp12;	// IMP=0x0000dcbc
- (void)quitTopApplication;	// IMP=0x0000cbd0
- (void)restoreIconList:(BOOL)fp8 force:(BOOL)fp12;	// IMP=0x0000c604
- (void)setState:(int)fp8;	// IMP=0x0000c164
- (BOOL)shouldDisconnectCallsOnLockPress;	// IMP=0x0000bda4
- (void)showButtonBar:(BOOL)fp8 animate:(BOOL)fp12 action:(SEL)fp16 delegate:(id)fp20;	// IMP=0x0000ca18
- (void)showZoomLayerAnimationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x0000d634
- (void)showZoomLayerForApp:(id)fp8;	// IMP=0x0000c240
- (id)statusBarWindow;	// IMP=0x0000c1f0
- (void)stopAllAnimations;	// IMP=0x0000c5ac
- (void)stopRestoringIconList;	// IMP=0x0000c970
- (void)systemControllerRouteChanged:(id)fp8;	// IMP=0x0000bd70
- (void)wakeUp:(id)fp8;	// IMP=0x0000d9bc
- (id)window;	// IMP=0x0000c228

@end

