/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBTextDisplayView, TPBottomButtonBar, UIProgressIndicator, UIScroller, UITextField, UITransitionView, UIView;

@interface SBUSSDAlertDisplay : SBAlertDisplay
{
    TPBottomButtonBar *_responseBar;	// 36 = 0x24
    UIView *_notifyView;	// 40 = 0x28
    UIView *_replyView;	// 44 = 0x2c
    UITransitionView *_transitionView;	// 48 = 0x30
    UIScroller *_scroller;	// 52 = 0x34
    UIView *_contentView;	// 56 = 0x38
    SBTextDisplayView *_charsRemainingView;	// 60 = 0x3c
    UIProgressIndicator *_progressIndicator;	// 64 = 0x40
    UITextField *_responseField;	// 68 = 0x44
    BOOL _allowsResponse;	// 72 = 0x48
}

- (void)_cancelClicked;	// IMP=0x0002df38
- (id)_notifyView;	// IMP=0x0002da28
- (void)_okayClicked;	// IMP=0x0002dec8
- (void)_replyClicked;	// IMP=0x0002e3d0
- (id)_replyView;	// IMP=0x0002dac8
- (void)_setupResponseBar;	// IMP=0x0002ef58
- (void)_textChanged:(id)fp8;	// IMP=0x0002deac
- (void)_updateCharsRemaining;	// IMP=0x0002dd7c
- (void)alertDisplayBecameVisible;	// IMP=0x0002dc74
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0002f30c
- (void)alertStringAvailable:(id)fp8;	// IMP=0x0002dc94
- (BOOL)allowsResponse;	// IMP=0x0002dd18
- (void)dealloc;	// IMP=0x0002dbc0
- (void)displayString:(id)fp8 centerVertically:(BOOL)fp12;	// IMP=0x0002e678
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0002d89c
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0002df60
- (void)setAllowsResponse:(BOOL)fp8;	// IMP=0x0002e9f4
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;	// IMP=0x0002dd20

@end

