/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBUSSDAlert : SBAlert
{
    unsigned int _receivedString:1;	// 48 = 0x30
    unsigned int _dismissOnActivate:1;	// 48 = 0x30
    NSTimer *_delayedDismissTimer;	// 52 = 0x34
}

+ (void)_daemonRestart:(id)fp8;	// IMP=0x0005513c
+ (id)errorStringForCode:(unsigned int)fp8;	// IMP=0x000550b0
+ (void)registerForAlerts;	// IMP=0x00054ec4
+ (void)registerForSettingsAlerts;	// IMP=0x00054e10
+ (void)test;	// IMP=0x00055020
- (void)USSDStringAvailable:(id)fp8 allowsResponse:(BOOL)fp12;	// IMP=0x0005525c
- (void)_delayedDismiss;	// IMP=0x00055388
- (BOOL)activate;	// IMP=0x000553ec
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00055204
- (BOOL)allowsResponse;	// IMP=0x0005532c
- (void)dealloc;	// IMP=0x00054da0
- (BOOL)receivedString;	// IMP=0x00055364
- (void)setDismissOnActivate:(BOOL)fp8;	// IMP=0x00055370

@end

