/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBVoicemailManager : NSObject
{
    CDAnonymousStruct1 _alertMark;	// 4 = 0x4
    CDAnonymousStruct1 _awayItemMark;	// 20 = 0x14
    BOOL _hasVisualVoicemail;	// 36 = 0x24
}

+ (id)sharedInstance;	// IMP=0x0006f4d8
- (void)_handleVoicemailAvailableNotification:(id)fp8;	// IMP=0x0006f924
- (void)_handleVoicemailStoreChangedNotification;	// IMP=0x0006fae0
- (void)_mark:(CDAnonymousStruct1 *)fp8;	// IMP=0x0006f5f4
- (void)_presentAlertForRecord:(void *)fp8 visualVoicemail:(BOOL)fp12;	// IMP=0x0006f72c
- (id)copyVisualVoicemailRecordsForAwayItems;	// IMP=0x0006f70c
- (void)dealloc;	// IMP=0x0006f458
- (id)init;	// IMP=0x0006f3b0
- (void)mark;	// IMP=0x0006f6d8
- (void)markForAlerts;	// IMP=0x0006f698
- (void)markForAwayItems;	// IMP=0x0006f6b8
- (void)setHasVisualVoicemail:(BOOL)fp8;	// IMP=0x0006f53c

@end

