/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDismissOnlyAlertItem.h"

@interface SBVoiceMailAlertItem : SBDismissOnlyAlertItem
{
    BOOL _isForVisualVoicemail;	// 29 = 0x1d
    unsigned int _recordUID;	// 32 = 0x20
}

+ (id)currentInstance;	// IMP=0x0006ba50
+ (BOOL)hasCurrentInstance;	// IMP=0x0006bb14
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x0006bb40
- (BOOL)isForVisualVoicemail;	// IMP=0x0006bb2c
- (id)lockLabel;	// IMP=0x0006bd0c
- (void)performUnlockAction;	// IMP=0x0006bb78
- (void)setIsVisualVoicemail:(BOOL)fp8 recordUID:(unsigned int)fp12;	// IMP=0x0006bb34
- (BOOL)willShowInAwayItems;	// IMP=0x0006bb70

@end

