/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBWiFiErrorAlertItem : SBAlertItem
{
    id _delegate;	// 12 = 0xc
    NSString *_name;	// 16 = 0x10
    int _error;	// 20 = 0x14
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006ec28
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006ec44
- (void)dealloc;	// IMP=0x0006eaec
- (void)dismiss;	// IMP=0x0006eb9c
- (id)initWithNetworkName:(id)fp8 error:(int)fp12;	// IMP=0x0006ea80
- (void)setDelegate:(id)fp8;	// IMP=0x0006eb40

@end

