/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageView.h"

@interface SBWiFiSignalStrength : UIImageView
{
    int _bars;	// 52 = 0x34
    int _rawStrength;	// 56 = 0x38
    BOOL _hilited;	// 60 = 0x3c
    BOOL _selected;	// 61 = 0x3d
    BOOL _secure;	// 62 = 0x3e
    BOOL _joining;	// 63 = 0x3f
    UIImageView *_icon;	// 64 = 0x40
}

+ (void)hideSpinner;	// IMP=0x000699c4
- (void)dealloc;	// IMP=0x0006a048
- (void)hide;	// IMP=0x0006a438
- (BOOL)hilited;	// IMP=0x0006a49c
- (id)initWithFrame:(struct CGRect)fp8 inView:(id)fp24;	// IMP=0x00069a2c
- (BOOL)joining;	// IMP=0x0006a100
- (BOOL)secure;	// IMP=0x0006a4d8
- (BOOL)selected;	// IMP=0x0006a430
- (void)setHilited:(BOOL)fp8;	// IMP=0x0006a4a4
- (void)setJoining:(BOOL)fp8;	// IMP=0x0006a108
- (void)setSecure:(BOOL)fp8;	// IMP=0x0006a4e0
- (void)setSelected:(BOOL)fp8;	// IMP=0x0006a468
- (void)setSpinnerHilited:(BOOL)fp8;	// IMP=0x000699f8
- (void)updateImage;	// IMP=0x0006a514
- (void)updateStrength:(id)fp8;	// IMP=0x0006a284

@end

