/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SpringBoard.h"

@interface SpringBoard (SBApplicationTesting)
- (id)_pathForTestOptions:(id)fp8;	// IMP=0x00017d58
- (void)anotherApplicationFinishedLaunching:(struct __GSEvent *)fp8;	// IMP=0x00018318
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;	// IMP=0x00018364
- (BOOL)runTest:(id)fp8 options:(id)fp12;	// IMP=0x00017dd0
- (void)startLaunchTestNamed:(id)fp8 options:(id)fp12;	// IMP=0x00017f38
- (void)startResumeTestNamed:(id)fp8 options:(id)fp12;	// IMP=0x00018234
@end

