/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@interface VolumeControlView : UIView
{
    float _volume;	// 28 = 0x1c
    int _mode;	// 32 = 0x20
}

+ (struct CGSize)controlSize;	// IMP=0x00034ad0
+ (void)loadImages;	// IMP=0x0003480c
- (id)_label;	// IMP=0x00034c98
- (BOOL)_showLabel;	// IMP=0x00034db0
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x00034df0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00034b30
- (void)setMode:(int)fp8;	// IMP=0x00034bf4
- (void)setVolume:(float)fp8 mode:(int)fp12;	// IMP=0x00034c30
- (float)volume;	// IMP=0x00034c90

@end

