/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, UIWindow, VolumeControlView;

@interface VolumeControl : NSObject
{
    UIWindow *_volumeWindow;	// 4 = 0x4
    VolumeControlView *_volumeView;	// 8 = 0x8
    BOOL _windowVisible;	// 12 = 0xc
    BOOL _debounce;	// 13 = 0xd
    int _mode;	// 16 = 0x10
    double _lastButtonEventTime;	// 20 = 0x14
    NSString *_lastDisplayedCategory;	// 28 = 0x1c
    NSString *_lastEventCategory;	// 32 = 0x20
}

+ (id)sharedVolumeControl;	// IMP=0x00033298
- (BOOL)_HUDIsDisplayableForCategory:(id)fp8;	// IMP=0x000339b0
- (BOOL)_allowVolumeChangeForCategory:(id)fp8;	// IMP=0x00033c10
- (float)_calcButtonRepeatDelay;	// IMP=0x00033d98
- (void)_changeVolumeBy:(float)fp8;	// IMP=0x00033c80
- (void)_createUI;	// IMP=0x0003365c
- (void)_orderWindowFront:(id)fp8 forCategory:(id)fp12;	// IMP=0x00033a74
- (void)_orderWindowOut:(id)fp8;	// IMP=0x000338d0
- (void)_registerForAVSystemControllerNotifications;	// IMP=0x000343b8
- (void)_serverConnectionDied:(id)fp8;	// IMP=0x00034554
- (void)_systemVolumeChanged:(id)fp8;	// IMP=0x000346a4
- (void)_tearDown;	// IMP=0x00033874
- (void)_unregisterForAVSystemControllerNotifications;	// IMP=0x000344c0
- (int)_volumeModeForCategory:(id)fp8;	// IMP=0x00034588
- (float)_windowFadeDelay;	// IMP=0x00033a50
- (void)animationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x00034328
- (void)cancelVolumeEvent;	// IMP=0x00034270
- (void)dealloc;	// IMP=0x00033340
- (void)decreaseVolume;	// IMP=0x00033f00
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x0003410c
- (void)hideHUD;	// IMP=0x00033fb0
- (void)increaseVolume;	// IMP=0x00033e54
- (id)init;	// IMP=0x000332e8
- (id)lastDisplayedCategory;	// IMP=0x000340fc
- (void)reorientHUDIfNeeded:(BOOL)fp8;	// IMP=0x000333a0
- (void)setHUDMode:(int)fp8;	// IMP=0x00034104
- (void)showHUD;	// IMP=0x00034020

@end

