/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCalendarDate, NSString;

@interface Alarm : NSObject
{
    unsigned int _alarmHour;	// 4 = 0x4
    unsigned int _alarmMinute;	// 8 = 0x8
    int _alarmSetting;	// 12 = 0xc
    NSString *_alarmSoundIdentifier;	// 16 = 0x10
    NSString *_alarmTitle;	// 20 = 0x14
    NSCalendarDate *_snoozeUntilDate;	// 24 = 0x18
    unsigned int _isActive:1;	// 28 = 0x1c
    unsigned int _repeats:1;	// 28 = 0x1c
    unsigned int _allowsSnooze:1;	// 28 = 0x1c
    unsigned int _dontSendUpdate:1;	// 28 = 0x1c
    unsigned int _dontStopSnoozing:1;	// 28 = 0x1c
    unsigned int _reserved:27;	// 28 = 0x1c
}

- (void)_activeAlertItem;	// IMP=0x0005db4c
- (id)_fireDateAfterDate:(id)fp8;	// IMP=0x0005d568
- (id)_initWithDictionary:(id)fp8;	// IMP=0x0005cff8
- (id)_prefsDictionary;	// IMP=0x0005d218
- (id)_snoozeUntilDate;	// IMP=0x0005d9dc
- (void)_update;	// IMP=0x0005cf28
- (id)alarmSoundIdentifier;	// IMP=0x0005da58
- (BOOL)alarmTimesEqualTo:(id)fp8;	// IMP=0x0005d4bc
- (id)alarmTitle;	// IMP=0x0005db44
- (BOOL)allowsSnooze;	// IMP=0x0005d8a0
- (int)daySetting;	// IMP=0x0005d850
- (void)dealloc;	// IMP=0x0005d450
- (id)description;	// IMP=0x0005ce34
- (void)fireAlarm;	// IMP=0x0005dbd4
- (void)getAlarmHour:(unsigned int *)fp8 minute:(unsigned int *)fp12;	// IMP=0x0005d554
- (id)init;	// IMP=0x0005cfac
- (BOOL)isActive;	// IMP=0x0005d7b8
- (BOOL)isSnoozing;	// IMP=0x0005d8b0
- (BOOL)repeats;	// IMP=0x0005d80c
- (void)setActive:(BOOL)fp8;	// IMP=0x0005d774
- (void)setAlarmHour:(unsigned int)fp8 minute:(unsigned int)fp12;	// IMP=0x0005d518
- (void)setAlarmSoundIdentifier:(id)fp8;	// IMP=0x0005d9e4
- (void)setAlarmTitle:(id)fp8;	// IMP=0x0005da60
- (void)setAllowsSnooze:(BOOL)fp8;	// IMP=0x0005d858
- (void)setDaySetting:(int)fp8;	// IMP=0x0005d81c
- (void)setRepeats:(BOOL)fp8;	// IMP=0x0005d7c4
- (void)startSnoozingFromDate:(id)fp8;	// IMP=0x0005d8c0
- (void)stopSnoozing;	// IMP=0x0005d984

@end

