/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (CTHelpers)
- (id)callBarringFacility;	// IMP=0x0005a8ec
- (id)callClass;	// IMP=0x0005a454
- (id)callForwardingReason;	// IMP=0x0005a6e8
- (id)callingLineIDRestrictionValue;	// IMP=0x0005abc8
- (id)callingLinePresentationValue;	// IMP=0x0005adb4
- (id)connectedLineIDRestrictionValue;	// IMP=0x0005af28
- (id)connectedLinePresentationValue;	// IMP=0x0005b054
- (id)enabledString;	// IMP=0x0005b1c8
- (id)mmiProcedure;	// IMP=0x0005b42c
- (id)serviceCenterAddress;	// IMP=0x0005b298
- (struct __CFString *)settingType;	// IMP=0x0005b5e8
- (id)ssServiceType;	// IMP=0x0005b31c
@end

