/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (PrefsNotifications)
- (id)_alertStringForPref:(id)fp8;	// IMP=0x0005bf84
- (id)_callBarringString:(id)fp8;	// IMP=0x0005b8e8
- (id)_callForwardingString:(id)fp8;	// IMP=0x0005b684
- (id)_callWaitingString:(id)fp8;	// IMP=0x0005b820
- (id)_callingLineIDRestrictionString:(id)fp8;	// IMP=0x0005bcd4
- (id)_callingLinePresentationString:(id)fp8;	// IMP=0x0005bb7c
- (id)_connectedLineIDRestrictionString:(id)fp8;	// IMP=0x0005bc28
- (id)_connectedLinePresentationString:(id)fp8;	// IMP=0x0005bad0
- (id)_fixedDialingString:(id)fp8;	// IMP=0x0005b9cc
- (id)_serviceCenterAddressString:(id)fp8;	// IMP=0x0005be2c
- (id)_simLockString:(id)fp8;	// IMP=0x0005bd80
- (id)_ssPasswordString:(id)fp8;	// IMP=0x0005bed8
- (void)addPrefNotification:(id)fp8 withUserInfo:(id)fp12;	// IMP=0x0005b614
- (id)prefsNotificationsAlertString;	// IMP=0x0005c3d0
@end

