/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (Formatting)
- (id)ICCID;	// IMP=0x00073238
- (id)IMEI;	// IMP=0x000732f0
@end

