/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface SBAlertItemsController : NSObject
{
    NSMutableArray *_lockedAlertItems;	// 4 = 0x4
    NSMutableArray *_unlockedAlertItems;	// 8 = 0x8
    NSTimer *_autoDismissTimer;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x0006449c
- (void)_deactivateAlertItem:(id)fp8 forLock:(BOOL)fp12;	// IMP=0x00064af0
- (void)activateAlertItem:(id)fp8;	// IMP=0x0006486c
- (void)autoDismissAlertItem:(id)fp8;	// IMP=0x00064c84
- (void)convertAnimatingUnlockedAlertsToLockedAlerts;	// IMP=0x000645dc
- (BOOL)deactivateAlertForMenuClick;	// IMP=0x00064d74
- (void)deactivateAlertItem:(id)fp8;	// IMP=0x00064c64
- (void)deactivateAlertItemsForLock;	// IMP=0x00064df8
- (void)deactivateAllAlertItems;	// IMP=0x000646d8
- (void)dealloc;	// IMP=0x0006457c
- (id)init;	// IMP=0x000644ec
- (BOOL)isShowingAlerts;	// IMP=0x00064cc4
- (void)resetAutoDismissTimer;	// IMP=0x00064778
- (id)visibleAlertItem;	// IMP=0x00064d0c

@end

