/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBAlert;

@interface SBAlertDisplay : UIView
{
    SBAlert *_alert;	// 28 = 0x1c
    unsigned int _displaysAboveStatusBar:1;	// 32 = 0x20
    unsigned int _shouldAnimateIn:1;	// 32 = 0x20
}

- (id)alert;	// IMP=0x0001ba0c
- (void)alertDisplayBecameVisible;	// IMP=0x0001badc
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0001bad8
- (void)dismiss;	// IMP=0x0001ba60
- (BOOL)displaysAboveStatusBar;	// IMP=0x0001bae0
- (BOOL)isReadyToBeRemovedFromView;	// IMP=0x0001bb04
- (void)launchURL:(id)fp8;	// IMP=0x0001ba14
- (void)setAlert:(id)fp8;	// IMP=0x0001b9e0
- (void)setDisplaysAboveStatusBar:(BOOL)fp8;	// IMP=0x0001baec
- (void)setHandlerAlreadyActive:(BOOL)fp8;	// IMP=0x0001ba9c
- (void)setShouldAnimateIn:(BOOL)fp8;	// IMP=0x0001bb0c
- (BOOL)shouldAnimateIn;	// IMP=0x0001bb24
- (void)willDismiss;	// IMP=0x0001ba2c

@end

