/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIKeyboard, UINavigationBar, UIScroller, UITextField;

@interface SBAlertInputView : SBSlidingAlertDisplay
{
    UITextField *_inputTextField;	// 72 = 0x48
    UIKeyboard *_keyboard;	// 76 = 0x4c
    SBTextDisplayView *_textDisplay;	// 80 = 0x50
    UIScroller *_scroller;	// 84 = 0x54
    UINavigationBar *_bar;	// 88 = 0x58
    BOOL _digitsOnly;	// 92 = 0x5c
    id _delegate;	// 96 = 0x60
    int _minLength;	// 100 = 0x64
    int _maxLength;	// 104 = 0x68
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00056c18
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x000566b4
- (void)_sendClicked:(id)fp8;	// IMP=0x00056b4c
- (void)_setInputTextField:(id)fp8;	// IMP=0x00056948
- (void)_setKeyboard:(id)fp8;	// IMP=0x000569a4
- (void)_setNavigationBar:(id)fp8;	// IMP=0x00056900
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00056638
- (void)dealloc;	// IMP=0x00056248
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000562cc
- (void)sbAlertInputViewCancelClicked:(id)fp8;	// IMP=0x00056b24
- (void)sbAlertInputViewSendClicked:(id)fp8;	// IMP=0x00056b04
- (void)setDelegate:(id)fp8;	// IMP=0x00056240
- (void)setDigitsOnly:(BOOL)fp8;	// IMP=0x00056ac0
- (void)setMaxLength:(int)fp8;	// IMP=0x000566ac
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x000565a4
- (void)setMinLength:(int)fp8;	// IMP=0x000566a4
- (void)setText:(id)fp8;	// IMP=0x00056600
- (BOOL)showsDesktopImage;	// IMP=0x0005659c
- (id)textField;	// IMP=0x00056b44
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;	// IMP=0x000569ec

@end

