/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class NSMutableArray, NSMutableDictionary, SBAlertDisplay, UIView;

@interface SBAlertWindow : UIWindow
{
    UIView *_contentLayer;	// 72 = 0x48
    unsigned int _isAnimating:1;	// 76 = 0x4c
    unsigned int _isInvalid:1;	// 76 = 0x4c
    unsigned int _handlerActive:1;	// 76 = 0x4c
    float _finalAlpha;	// 80 = 0x50
    SBAlertDisplay *_currentDisplay;	// 84 = 0x54
    NSMutableArray *_stackedAlertDisplays;	// 88 = 0x58
    NSMutableDictionary *_alertToDisplayMap;	// 92 = 0x5c
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0001b1e0
- (void)_backgroundFadedIn;	// IMP=0x0001b320
- (void)alertDisplayWillDismiss;	// IMP=0x0001b958
- (id)currentDisplay;	// IMP=0x0001b9b0
- (BOOL)deactivateAlert:(id)fp8;	// IMP=0x0001b7e0
- (void)dealloc;	// IMP=0x0001b348
- (void)dismissWindow:(id)fp8;	// IMP=0x0001b944
- (void)displayAlert:(id)fp8;	// IMP=0x0001b46c
- (int)displayCount;	// IMP=0x0001b924
- (BOOL)handlerAlreadyActive;	// IMP=0x0001b9d0
- (id)initWithContentRect:(struct CGRect)fp8;	// IMP=0x0001b204
- (BOOL)isOpaque;	// IMP=0x0001b3e0
- (void)popInCurrentDisplay;	// IMP=0x0001b95c
- (void)setHandlerAlreadyActive:(BOOL)fp8;	// IMP=0x0001b9b8
- (id)stackedDisplayForAlert:(id)fp8;	// IMP=0x0001b3e8

@end

