/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@class Alarm;

@interface SBAlarmAlertItem : SBRingingAlertItem
{
    Alarm *_alarm;	// 24 = 0x18
    BOOL _snoozeAlarm;	// 28 = 0x1c
}

- (id)alarm;	// IMP=0x00065a0c
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00065de0
- (BOOL)allowsSnooze;	// IMP=0x00065a14
- (id)avAudioCategory;	// IMP=0x00065dd4
- (id)avClientName;	// IMP=0x00065dc8
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00065b2c
- (void)dealloc;	// IMP=0x00065970
- (id)initWithAlarm:(id)fp8;	// IMP=0x00065930
- (id)lockLabel;	// IMP=0x00065ad0
- (void)setAlarm:(id)fp8;	// IMP=0x000659c4
- (id)soundIdentifier;	// IMP=0x00065d9c
- (void)startSnoozingAndDeactivate;	// IMP=0x00065a44

@end

