/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDisplay.h"

@class NSMutableArray, NSMutableSet, NSString, UIRemoteApplication;

@interface SBApplication : SBDisplay
{
    NSString *_roleID;	// 36 = 0x24
    NSString *_path;	// 40 = 0x28
    NSString *_bundleID;	// 44 = 0x2c
    BOOL _isLaunching;	// 48 = 0x30
    int _failedLaunchCount;	// 52 = 0x34
    int _memoryWarningCount;	// 56 = 0x38
    BOOL _enabled;	// 60 = 0x3c
    BOOL _useDemoRole;	// 61 = 0x3d
    unsigned int _dataUsage:3;	// 62 = 0x3e
    unsigned int _relauchesOnAbnormalExit:1;	// 62 = 0x3e
    unsigned int _isDefaultRole:1;	// 62 = 0x3e
    NSString *_demoRole;	// 64 = 0x40
    NSMutableSet *_statusBarItemSet;	// 68 = 0x44
    NSMutableArray *_tags;	// 72 = 0x48
    UIRemoteApplication *_remoteApplication;	// 76 = 0x4c
    struct __CFSet *_launchAlerts;	// 80 = 0x50
    int _pid;	// 84 = 0x54
    NSString *_displayName;	// 88 = 0x58
}

+ (id)applicationWithDisplayIdentifier:(id)fp8;	// IMP=0x0001ead8
+ (id)applicationWithPath:(id)fp8;	// IMP=0x0001e66c
+ (id)applicationWithPath:(id)fp8 roleID:(id)fp12;	// IMP=0x0001e68c
+ (id)applicationWithPath:(id)fp8 roleID:(id)fp12 plist:(id)fp16;	// IMP=0x0001e6d8
+ (id)applicationsByRoleWithPath:(id)fp8;	// IMP=0x0001e4fc
+ (void)flushLaunchAlertsOfType:(int)fp8;	// IMP=0x000219a0
+ (void)flushSnapshotsForIdentifier:(id)fp8;	// IMP=0x0001f7e8
+ (id)iPod;	// IMP=0x0001eca4
+ (void)setUseDemoRole:(BOOL)fp8;	// IMP=0x0001ed28
+ (id)springBoard;	// IMP=0x0001ec24
- (int)PID;	// IMP=0x000216a8
- (id)_additionalDisplayQualification;	// IMP=0x0001f5a4
- (void)_autoLaunchMailIfNeeded;	// IMP=0x00020f84
- (void)_cancelWatchdogTimer;	// IMP=0x0001f2a8
- (void)_relaunchAfterAbnormalExit;	// IMP=0x00020f98
- (void)_sendCurrentDeviceOrientation;	// IMP=0x0001fcc0
- (void)_startDeactivationWatchdogTimer;	// IMP=0x0001f12c
- (void)_startLaunchWatchdogTimer;	// IMP=0x0001ee34
- (void)_startResumeWatchdogTimer;	// IMP=0x0001efb0
- (BOOL)activate;	// IMP=0x0001fda8
- (id)arguments;	// IMP=0x0001f520
- (id)bundle;	// IMP=0x0001f4d8
- (id)bundleForLaunching;	// IMP=0x0001f504
- (id)bundleID;	// IMP=0x0001f4d0
- (unsigned int)dataUsage;	// IMP=0x0001f590
- (BOOL)deactivate;	// IMP=0x00020838
- (void)deactivated;	// IMP=0x00020f1c
- (void)dealloc;	// IMP=0x0001f308
- (id)demoRole;	// IMP=0x0001f464
- (id)description;	// IMP=0x0001edd8
- (id)displayIdentifier;	// IMP=0x0001f6ac
- (id)displayName;	// IMP=0x0001fb80
- (BOOL)enabled;	// IMP=0x0001f43c
- (void)exitedAbnormally;	// IMP=0x00020fc8
- (void)exitedNormally;	// IMP=0x00021308
- (int)failedLaunchCount;	// IMP=0x0002143c
- (id)init;	// IMP=0x0001ed94
- (BOOL)isDefaultRole;	// IMP=0x0001f42c
- (BOOL)isRunning;	// IMP=0x00021a0c
- (BOOL)isWidget;	// IMP=0x0001f59c
- (BOOL)kill;	// IMP=0x00020f70
- (void)launchFailed;	// IMP=0x00021508
- (void)launchSucceeded;	// IMP=0x00021560
- (id)launchURLArgument;	// IMP=0x0001fc7c
- (int)memoryWarningCount;	// IMP=0x00021708
- (void)noteAddedStatusBarItem:(id)fp8;	// IMP=0x00021760
- (void)noteRemovedStatusBarItem:(id)fp8;	// IMP=0x000217c4
- (id)path;	// IMP=0x0001f4c8
- (id)pathForDefaultImage:(char *)fp8;	// IMP=0x0001f95c
- (id)pathForIcon;	// IMP=0x0001f758
- (unsigned int)priority;	// IMP=0x000213e8
- (BOOL)relaunchesAfterAbnormalExit;	// IMP=0x00021750
- (id)remoteApplication;	// IMP=0x000217e4
- (void)removeAppPrefs;	// IMP=0x00021444
- (void)resetLaunchAlertForType:(int)fp8;	// IMP=0x00021980
- (id)roleID;	// IMP=0x0001f40c
- (void)setDemoRole:(id)fp8;	// IMP=0x0001f478
- (void)setDisplayName:(id)fp8;	// IMP=0x0001fc34
- (void)setEnabled:(BOOL)fp8;	// IMP=0x0001f45c
- (void)setIsDefaultRole:(BOOL)fp8;	// IMP=0x0001f414
- (void)setMemoryWarningCount:(id)fp8;	// IMP=0x00021710
- (void)setPID:(int)fp8;	// IMP=0x000216d8
- (void)setRelaunchesAfterAbnormalExit:(BOOL)fp8;	// IMP=0x00021738
- (void)setRoleID:(id)fp8;	// IMP=0x0001f3c4
- (void)setTags:(id)fp8;	// IMP=0x0001f540
- (void)setUseDemoRole:(BOOL)fp8;	// IMP=0x0001f4c0
- (BOOL)shouldLaunchPNGless;	// IMP=0x0001f8e4
- (BOOL)showLaunchAlertForType:(int)fp8;	// IMP=0x00021854
- (id)tags;	// IMP=0x0001f588
- (void)watchdogForDeactivate;	// IMP=0x00020df0
- (void)watchdogForLaunch;	// IMP=0x00020eb8
- (void)watchdogForResume;	// IMP=0x00020e54

@end

