/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class SBApplication, SBApplicationIconBadge, SBApplicationIconLabel, UIImage, UIImageView;

@interface SBApplicationIcon : UIControl
{
    UIImage *_icon;	// 52 = 0x34
    SBApplication *_app;	// 56 = 0x38
    UIImageView *_image;	// 60 = 0x3c
    UIImageView *_reflection;	// 64 = 0x40
    SBApplicationIconBadge *_badge;	// 68 = 0x44
    SBApplicationIconLabel *_label;	// 72 = 0x48
    BOOL _drawsLabel;	// 76 = 0x4c
    BOOL _isHidden;	// 77 = 0x4d
    BOOL _isRevealable;	// 78 = 0x4e
    BOOL _inDock;	// 79 = 0x4f
}

+ (struct CGSize)defaultIconSize;	// IMP=0x00010ed4
- (id)_automationID;	// IMP=0x00010640
- (id)application;	// IMP=0x0000fe00
- (void)dealloc;	// IMP=0x0000fdac
- (id)displayName;	// IMP=0x00010620
- (id)hilightedIcon;	// IMP=0x000103e8
- (id)icon;	// IMP=0x000102e8
- (BOOL)ignoresMouseEvents;	// IMP=0x0000fe08
- (id)initWithApplication:(id)fp8;	// IMP=0x0000fd0c
- (BOOL)isHidden;	// IMP=0x0001012c
- (BOOL)isRevealable;	// IMP=0x0001013c
- (void)layout;	// IMP=0x000105dc
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x000106c4
- (id)reflectedIcon:(BOOL)fp8;	// IMP=0x00011244
- (void)setBadge:(id)fp8;	// IMP=0x00011030
- (void)setDisplayedIcon:(id)fp8;	// IMP=0x0001019c
- (void)setDrawsLabel:(BOOL)fp8;	// IMP=0x00010eec
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x00010744
- (void)setInDock:(BOOL)fp8;	// IMP=0x000108c4
- (void)setIsHidden:(BOOL)fp8 animate:(BOOL)fp12;	// IMP=0x0000fed4
- (void)setIsRevealable:(BOOL)fp8;	// IMP=0x00010134
- (void)setOrigin:(struct CGPoint)fp8;	// IMP=0x00010af4
- (BOOL)shouldTrack;	// IMP=0x00010680
- (void)showIconAnimationDidStop:(id)fp8 didFinish:(id)fp12 icon:(id)fp16;	// IMP=0x0000fe10
- (id)subviews;	// IMP=0x00010144
- (void)updateLabelOrigin;	// IMP=0x00011170

@end

