/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface SBAppWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0000b558
- (void)dealloc;	// IMP=0x0000b428
- (id)initWithContentRect:(struct CGRect)fp8;	// IMP=0x0000b3c4
- (void)sendEvent:(struct __GSEvent *)fp8;	// IMP=0x0000b488
- (BOOL)shouldRespondToStatusBarHeightChange;	// IMP=0x0000b550

@end

