/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIPushButton, UIScrubberControl;

@interface SBAwayMediaControlsView : UIView
{
    unsigned int _seeked:1;	// 28 = 0x1c
    UIPushButton *_prevButton;	// 32 = 0x20
    UIPushButton *_nextButton;	// 36 = 0x24
    UIPushButton *_playPauseButton;	// 40 = 0x28
    UIScrubberControl *_slider;	// 44 = 0x2c
}

- (void)_clearSeekedFlag:(id)fp8;	// IMP=0x0007ab24
- (void)_controlButtonAction:(id)fp8;	// IMP=0x0007ab34
- (id)_createButtonWithImage:(id)fp8 action:(SEL)fp12 tag:(int)fp16;	// IMP=0x0007a81c
- (void)_nowPlayingChanged:(id)fp8;	// IMP=0x0007afe4
- (void)_registerForNowPlayingNotifications;	// IMP=0x0007ae24
- (void)_registerForVolumeNotifications;	// IMP=0x0007af04
- (void)_systemVolumeChanged:(id)fp8;	// IMP=0x0007b000
- (void)_unregisterForNowPlayingNotifications;	// IMP=0x0007aea4
- (void)_unregisterForVolumeNotifications;	// IMP=0x0007af84
- (void)_updateInformation;	// IMP=0x0007a914
- (void)_volumeChange:(id)fp8;	// IMP=0x0007ac24
- (void)dealloc;	// IMP=0x0007a724
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0007a3d0
- (void)layoutSubviews;	// IMP=0x0007b07c
- (void)setAlpha:(float)fp8;	// IMP=0x0007aaac
- (void)viewHandleTouchPause:(id)fp8 isDown:(BOOL)fp12;	// IMP=0x0007acb8
- (double)viewTouchPauseThreshold:(id)fp8;	// IMP=0x0007ae14

@end

