/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, NSTimer, TPLCDView, UIImage;

@interface SBAwayInCallController : NSObject
{
    TPLCDView *_lcdView;	// 4 = 0x4
    BOOL _showsInCallInfo;	// 8 = 0x8
    NSTimer *_durationTimer;	// 12 = 0xc
    struct __CTCall *_displayedCall;	// 16 = 0x10
    NSString *_localizedLabel;	// 20 = 0x14
    UIImage *_callerImage;	// 24 = 0x18
    BOOL _isFullScreen;	// 28 = 0x1c
}

- (id)callerImage;	// IMP=0x00071638
- (BOOL)callerImageIsFullScreen;	// IMP=0x00071640
- (void)dealloc;	// IMP=0x00071580
- (void)fetchCallInformation:(id *)fp8 name:(id *)fp12 label:(id *)fp16 image:(id *)fp20 isFullScreen:(char *)fp24;	// IMP=0x00071648
- (id)initWithLCDView:(id)fp8;	// IMP=0x0007151c
- (void)reload;	// IMP=0x00071ab0
- (void)setShowsInCallInfo:(BOOL)fp8;	// IMP=0x00071d4c
- (void)updateDuration;	// IMP=0x000718bc

@end

