/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class SBCalendarIconContentsView;

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
    SBCalendarIconContentsView *_dateContents;	// 80 = 0x50
}

- (void)dealloc;	// IMP=0x0004b0f4
- (id)initWithApplication:(id)fp8;	// IMP=0x0004afe0
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x0004b148

@end

