/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCallAlertDisplay.h"

@class TPBottomButtonBar, TPCallWaitingButton, TPPushButton;

@interface SBCallWaitingAlertDisplay : SBCallAlertDisplay
{
    TPCallWaitingButton *_ignoreButton;	// 72 = 0x48
    TPCallWaitingButton *_answerButton;	// 76 = 0x4c
    TPPushButton *_answerAndReleaseButton;	// 80 = 0x50
    TPBottomButtonBar *_animatingBottomBar;	// 84 = 0x54
    unsigned int _didRelease:1;	// 88 = 0x58
    unsigned int _didHeldRelease:1;	// 88 = 0x58
    unsigned int _setupForThree:1;	// 88 = 0x58
}

+ (id)_createBottomButtonBarForDisplay:(id)fp8;	// IMP=0x00049970
+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00048890
- (void)_addCallWaitingButtons:(BOOL)fp8;	// IMP=0x00049640
- (void)_answerButtonsSwapped;	// IMP=0x00048f50
- (void)_bottomBarSwitchDone;	// IMP=0x000495ec
- (void)_bottomBarSwitchHalfDone;	// IMP=0x00049538
- (void)_callCountChanged:(id)fp8;	// IMP=0x000489a8
- (void)_callWaitingControlsFaded;	// IMP=0x00048f04
- (void)_setPhoneFlipBackAttribute;	// IMP=0x00048fbc
- (id)additionalURLParameter;	// IMP=0x0004913c
- (void)answerAndRelease:(id)fp8;	// IMP=0x0004928c
- (void)answerCall:(struct __CTCall *)fp8;	// IMP=0x000491a0
- (void)dealloc;	// IMP=0x0004890c
- (void)dismiss;	// IMP=0x000490cc
- (void)ignore;	// IMP=0x0004904c
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x00048770
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x00049310
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x000492b4

@end

