/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCalendarAlertItem : SBAlertItem
{
    double _date;	// 12 = 0xc
    NSString *_title;	// 20 = 0x14
    NSString *_location;	// 24 = 0x18
    int _eventId;	// 28 = 0x1c
    BOOL _isAllDay;	// 32 = 0x20
}

+ (void)adjustOnWake;	// IMP=0x000684f4
+ (void)alarmsDidFire:(id)fp8;	// IMP=0x00067fa8
+ (void)alarmsDidSchedule:(id)fp8;	// IMP=0x00068334
+ (void)didWakeFromSleep;	// IMP=0x000684b4
+ (void)finishRegisteringForAlerts;	// IMP=0x00067eb4
+ (void)registerForAlerts;	// IMP=0x00069164
+ (void)significantTimeChange;	// IMP=0x00069254
- (id)_dateString:(BOOL)fp8;	// IMP=0x00068644
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00068f28
- (id)awayItem;	// IMP=0x00069010
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00068b7c
- (void)dealloc;	// IMP=0x000685a0
- (void)didPresentAlertSheet:(id)fp8;	// IMP=0x00068de4
- (id)initWithDate:(double)fp8 title:(id)fp16 location:(id)fp20 eventId:(int)fp24 isAllDay:(BOOL)fp28;	// IMP=0x00068508
- (id)lockLabel;	// IMP=0x00068d88
- (void)performUnlockAction;	// IMP=0x00068fb0
- (void)revealEvent;	// IMP=0x00068e68
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x00069000
- (BOOL)willShowInAwayItems;	// IMP=0x00069008

@end

