/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSString;

@interface SBCallFailureAlert : SBAlert
{
    int _causeCode;	// 48 = 0x30
    NSString *_address;	// 52 = 0x34
    int _uid;	// 56 = 0x38
    struct __CTCall *_call;	// 60 = 0x3c
}

+ (void)activateForCall:(struct __CTCall *)fp8 causeCode:(long)fp12;	// IMP=0x0005ee2c
+ (BOOL)shouldDisplayForCauseCode:(long)fp8;	// IMP=0x0005edb0
+ (void)test;	// IMP=0x0005ef34
- (void)activateWhenPossible;	// IMP=0x0005edc0
- (int)addressBookUID;	// IMP=0x0005f08c
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0005f01c
- (struct __CTCall *)call;	// IMP=0x0005f07c
- (id)callAddress;	// IMP=0x0005f084
- (long)causeCode;	// IMP=0x0005f074
- (void)dealloc;	// IMP=0x0005ed4c
- (id)initWithCauseCode:(long)fp8 call:(struct __CTCall *)fp12;	// IMP=0x0005ec7c
- (void)setCallAddress:(id)fp8;	// IMP=0x0005f094

@end

