/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallAlertDisplay : SBSlidingAlertDisplay
{
    BOOL _wasToldToStopRinging;	// 70 = 0x46
    BOOL _answered;	// 71 = 0x47
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0001df48
+ (id)createBottomLockBarForDisplay:(id)fp8;	// IMP=0x0001cec4
- (void)_ringIfNecessary;	// IMP=0x0001d648
- (id)additionalURLParameter;	// IMP=0x0001d84c
- (void)alertDisplayBecameVisible;	// IMP=0x0001d7dc
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0001d6f8
- (void)answer:(id)fp8;	// IMP=0x0001d92c
- (void)answerAndRelease;	// IMP=0x0001d8e4
- (void)answerCall:(struct __CTCall *)fp8;	// IMP=0x0001d858
- (void)checkForStatusChange;	// IMP=0x0001d540
- (void)dealloc;	// IMP=0x0001d02c
- (void)dismiss;	// IMP=0x0001dce8
- (void)finishedAnimatingIn;	// IMP=0x0001d7f8
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;	// IMP=0x0001df04
- (void)ignore;	// IMP=0x0001ddc4
- (void)ignoreAndRelease;	// IMP=0x0001dd80
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x0001dccc
- (void)ringOrVibrate;	// IMP=0x0001d07c
- (void)ringerChanged;	// IMP=0x0001d190
- (void)setAlert:(id)fp8;	// IMP=0x0001d340
- (void)stopRingingOrVibrating;	// IMP=0x0001d0f8
- (void)updateImageFromPerson:(struct CPRecord *)fp8;	// IMP=0x0001d2cc
- (void)updateLCDWithName:(id)fp8 label:(id)fp12 breakPoint:(unsigned int)fp16;	// IMP=0x0001d1bc
- (BOOL)wasToldToStopRinging;	// IMP=0x0001d188

@end

