/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@interface SBCountDownAlertItem : SBRingingAlertItem
{
}

- (id)avAudioCategory;	// IMP=0x0006bd90
- (id)avClientName;	// IMP=0x0006bd84
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006bc04
- (id)lockLabel;	// IMP=0x0006bba8
- (id)soundIdentifier;	// IMP=0x0006bd4c

@end

