/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBDeviceLockPasscodeEntryAlert : SBAlert
{
}

+ (id)sharedInstance;	// IMP=0x00075c14
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x00075d3c
- (BOOL)deactivate;	// IMP=0x00075c64
- (int)statusBarMode;	// IMP=0x00075cdc

@end

