/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TPPhonePad.h"

@class SBEmergencyCallButton, UIImage, UIPushButton;

@interface SBDeviceLockKeypad : TPPhonePad
{
    UIImage *_deleteIcon;	// 104 = 0x68
    UIPushButton *_deleteButton;	// 108 = 0x6c
    SBEmergencyCallButton *_emergencyCallButton;	// 112 = 0x70
    BOOL _showDeleteIcon;	// 116 = 0x74
    BOOL _playKeyboardClicks;	// 117 = 0x75
}

- (id)_keypadImage;	// IMP=0x00061ac4
- (id)_pressedImage;	// IMP=0x00061968
- (float)_yFudge;	// IMP=0x00061bb0
- (void)dealloc;	// IMP=0x00061794
- (void)hiddenFromView;	// IMP=0x00061a40
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000612f8
- (void)setPlaysKeyboardClicks:(BOOL)fp8;	// IMP=0x00061530
- (void)setShowsDeleteIcon:(BOOL)fp8;	// IMP=0x00061814
- (void)setShowsEmergencyCallButton:(BOOL)fp8;	// IMP=0x000615c0
- (BOOL)showsEmergencyCallButton;	// IMP=0x000615b0
- (void)willBecomeVisible;	// IMP=0x00061aa8

@end

