/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBDiskSpaceAlertItem : SBAlertItem
{
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006ef38
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006ef70
- (void)dismiss;	// IMP=0x0006eef8
- (void)performUnlockAction;	// IMP=0x0006ef54
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x0006f0d4

@end

