/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, SBIconModel, TPLCDTextView, UIPageIndicator, UIScroller, UIView;

@interface SBIconController : NSObject
{
    NSMutableArray *_iconLists;	// 4 = 0x4
    SBIconModel *_iconModel;	// 8 = 0x8
    UIView *_contentView;	// 12 = 0xc
    UIScroller *_scroller;	// 16 = 0x10
    UIPageIndicator *_pageIndicator;	// 20 = 0x14
    int _currentIconListIndex;	// 24 = 0x18
    TPLCDTextView *_idleText;	// 28 = 0x1c
}

+ (id)sharedInstance;	// IMP=0x0007b430
- (id)addEmptyIconList;	// IMP=0x0007bac0
- (void)addIconToFirstAvailableList:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16;	// IMP=0x0007bef8
- (id)contentView;	// IMP=0x0007b59c
- (id)currentIconList;	// IMP=0x0007b8d4
- (void)dealloc;	// IMP=0x0007b4f8
- (BOOL)hasIdleModeText;	// IMP=0x0007c46c
- (id)iconListContainingIcon:(id)fp8;	// IMP=0x0007b8f8
- (id)iconLists;	// IMP=0x0007c05c
- (float)idleModeTextHeight;	// IMP=0x0007c0cc
- (void)idleTextDidAnimate:(id)fp8 finished:(id)fp12 toText:(id)fp16;	// IMP=0x0007c110
- (id)init;	// IMP=0x0007b480
- (void)lcdTextViewCompletedScroll:(id)fp8;	// IMP=0x0007c090
- (int)maxIconColumns;	// IMP=0x0007cc1c
- (int)maxIconRows;	// IMP=0x0007cc14
- (void)relayoutIcons;	// IMP=0x0007bd54
- (void)removeAccessory:(id)fp8;	// IMP=0x0007cbb8
- (void)removeEmptyIconList:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0007bbe0
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0007c020
- (void)scatter:(BOOL)fp8;	// IMP=0x0007c8c8
- (void)scrollToIconListAtIndex:(int)fp8 animate:(BOOL)fp12;	// IMP=0x0007b980
- (void)scrollerDidEndAnimatedScrolling:(id)fp8;	// IMP=0x0007cb18
- (void)scrollerDidEndDragging:(id)fp8 willSmoothScroll:(BOOL)fp12;	// IMP=0x0007cae0
- (void)scrollerDidEndSmoothScrolling:(id)fp8;	// IMP=0x0007cafc
- (void)setIdleModeText:(id)fp8;	// IMP=0x0007c4a4
- (void)showAccessory:(id)fp8;	// IMP=0x0007cb34
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;	// IMP=0x0007c9a4
- (void)updateContentSizeAndPageCount;	// IMP=0x0007ba08
- (void)updateCurrentIconListIndex;	// IMP=0x0007b844
- (void)updateNumberOfRowsWithDuration:(float)fp8;	// IMP=0x0007c168

@end

