/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray;

@interface SBIconList : UIView
{
    NSMutableArray *_iconMatrix;	// 28 = 0x1c
    unsigned int _scattered:1;	// 32 = 0x20
    unsigned int _needsLayout:1;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0004b610
- (void)clickedIcon:(id)fp8;	// IMP=0x0004c850
- (BOOL)containsIcon:(id)fp8;	// IMP=0x0004be4c
- (void)dealloc;	// IMP=0x0004b750
- (BOOL)firstFreeSlotX:(int *)fp8 Y:(int *)fp12;	// IMP=0x0004b820
- (BOOL)getX:(int *)fp8 Y:(int *)fp12 forIcon:(id)fp16;	// IMP=0x0004bda8
- (id)iconAtX:(int)fp8 Y:(int)fp12;	// IMP=0x0004b7a4
- (int)iconsInRow:(id)fp8;	// IMP=0x0004c9a8
- (id)initWithDefaultSize;	// IMP=0x0004b620
- (void)insertIcon:(id)fp8 atX:(int)fp12 Y:(int)fp16 animate:(BOOL)fp20;	// IMP=0x0004bb04
- (BOOL)isEmpty;	// IMP=0x0004b948
- (BOOL)isScattered;	// IMP=0x0004c1ac
- (void)layoutIconsIfNeeded;	// IMP=0x0004ca50
- (struct CGPoint)originForIcon:(id)fp8;	// IMP=0x0004cdac
- (struct CGPoint)originForIconAtX:(int)fp8 Y:(int)fp12;	// IMP=0x0004ccd4
- (void)removeAllIcons;	// IMP=0x0004c05c
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;	// IMP=0x0004bfa4
- (void)removeIconAtX:(int)fp8 Y:(int)fp12 animate:(BOOL)fp16;	// IMP=0x0004bed0
- (void)scatter:(BOOL)fp8;	// IMP=0x0004c1b8
- (void)setIconsNeedLayout;	// IMP=0x0004c998
- (void)showIconAnimationDidStop:(id)fp8 didFinish:(id)fp12 icon:(id)fp16;	// IMP=0x0004ba44
- (void)stopAnimations;	// IMP=0x0004c734
- (float)topIconPadding;	// IMP=0x0004c964
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;	// IMP=0x0004c4c8
- (float)verticalIconPadding;	// IMP=0x0004c890

@end

