/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBLowPowerAlertItem : SBAlertItem
{
    unsigned int _talkMinutesLeft;	// 12 = 0xc
    unsigned int _talkLevel;	// 16 = 0x10
}

+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)fp8;	// IMP=0x0006acf8
+ (unsigned int)_thresholdForLevel:(unsigned int)fp8;	// IMP=0x0006acc0
+ (void)saveLowBatteryLog;	// IMP=0x0006a2d4
+ (void)savePowerDiagnosisLogWithCurrentCapacity:(int)fp8 startCapacity:(int)fp12;	// IMP=0x0006a7f4
+ (void)setBatteryLevel:(unsigned int)fp8;	// IMP=0x0006ad90
+ (id)systemVersionDescription;	// IMP=0x0006a16c
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x0006b178
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x0006aff4
- (id)initWithTalkTimeLeft:(unsigned int)fp8 level:(unsigned int)fp12;	// IMP=0x0006ac70
- (BOOL)shouldShowInEmergencyCall;	// IMP=0x0006b1c8
- (BOOL)shouldShowInLockScreen;	// IMP=0x0006b1c0
- (BOOL)undimsScreen;	// IMP=0x0006b1d0
- (void)willPresentAlertSheet:(id)fp8;	// IMP=0x0006afdc

@end

