/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SBApplication, UIWindow;

@interface SBMiniAlertController : NSObject
{
    SBApplication *_displayShowingAnAlert;	// 4 = 0x4
    UIWindow *_dimmingWindow;	// 8 = 0x8
    unsigned int _dontAskApps:1;	// 12 = 0xc
    unsigned int _reserved:31;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x00062db0
- (BOOL)canShowAlerts;	// IMP=0x00063864
- (void)cancelHideDimmingWindow;	// IMP=0x00063194
- (void)deactivateAlertItemsWithBundleIdentifier:(id)fp8;	// IMP=0x00063330
- (id)dimImageForKeyboard:(BOOL)fp8;	// IMP=0x00062e00
- (void)displayDidDisableMiniAlerts:(id)fp8;	// IMP=0x00063598
- (id)displayShowingAnAlert;	// IMP=0x0006345c
- (void)displayWillDismissMiniAlert:(id)fp8 andShowAnother:(BOOL)fp12;	// IMP=0x0006347c
- (void)displayWillShowMiniAlert:(id)fp8;	// IMP=0x000633a0
- (void)finishedAnimatingDimWindowOut:(id)fp8 didFinish:(id)fp12;	// IMP=0x00063104
- (void)hideApplicationMiniAlerts;	// IMP=0x000636d8
- (void)hideDimmingWindow;	// IMP=0x00063220
- (void)hideDimmingWindowAfterDelay;	// IMP=0x000631dc
- (void)noteMiniAlertStateChanged;	// IMP=0x0006375c
- (void)setShouldAskApps:(BOOL)fp8;	// IMP=0x00063464
- (void)showApplicationMiniAlertsIfNeeded;	// IMP=0x000635ec
- (void)showDimmingWindow;	// IMP=0x00062f14

@end

