/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBNowPlayingAlertItem : SBAlertItem
{
    unsigned int _seeked:1;	// 10 = 0xa
}

+ (id)currentInstance;	// IMP=0x000789d0
+ (BOOL)hasCurrentInstance;	// IMP=0x00078a20
- (void)_clearSeekedFlag:(id)fp8;	// IMP=0x00079450
- (void)_controlButtonAction:(id)fp8;	// IMP=0x00079460
- (id)_createButtonWithImage:(id)fp8 action:(SEL)fp12 tag:(int)fp16;	// IMP=0x000790c4
- (void)_nowPlayingChanged:(id)fp8;	// IMP=0x00079854
- (void)_registerForNowPlayingNotifications;	// IMP=0x00079694
- (void)_registerForVolumeNotifications;	// IMP=0x00079774
- (void)_systemVolumeChanged:(id)fp8;	// IMP=0x000798ac
- (void)_unregisterForNowPlayingNotifications;	// IMP=0x00079714
- (void)_unregisterForVolumeNotifications;	// IMP=0x000797f4
- (void)_updateLabelWithTag:(int)fp8 text:(id)fp12 faded:(BOOL)fp16 cursor:(float *)fp20 sheet:(id)fp24;	// IMP=0x00078bf8
- (void)_volumeChange:(id)fp8;	// IMP=0x0007951c
- (id)alertSheet;	// IMP=0x000791bc
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x000793e4
- (BOOL)allowMenuButtonDismissal;	// IMP=0x000793dc
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00079ef8
- (id)createCenteredLabel:(BOOL)fp8;	// IMP=0x00078a38
- (id)init;	// IMP=0x00078978
- (void)updateInformation:(BOOL)fp8;	// IMP=0x00078d90
- (void)viewHandleTouchPause:(id)fp8 isDown:(BOOL)fp12;	// IMP=0x0007957c
- (double)viewTouchPauseThreshold:(id)fp8;	// IMP=0x00079684
- (void)willActivate;	// IMP=0x000792a4
- (void)willDeactivate:(BOOL)fp8;	// IMP=0x000792e4

@end

