/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIAlertSheet.h"

@interface SBNowPlayingAlertSheet : UIAlertSheet
{
    unsigned int _layoutAsLocked:1;	// 96 = 0x60
}

- (void)_positionControlButton:(int)fp8 withFloor:(float)fp12;	// IMP=0x00079954
- (void)layout;	// IMP=0x00079ae4
- (void)setLayoutAsLocked:(BOOL)fp8;	// IMP=0x00079ee0

@end

