/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SBPlatformController : NSObject
{
    NSString *_currentConfigurationName;	// 4 = 0x4
    NSMutableDictionary *_currentConfiguration;	// 8 = 0x8
    NSMutableDictionary *_currentCapabilities;	// 12 = 0xc
    void *_shmem;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00077cf4
- (id)allowedDisplayIdentifiers;	// IMP=0x00077fc8
- (void)dealloc;	// IMP=0x00077dc4
- (id)displayOrder;	// IMP=0x00077f10
- (BOOL)hasCapability:(id)fp8;	// IMP=0x00077ee4
- (id)infoForCapability:(id)fp8;	// IMP=0x00077e84
- (id)init;	// IMP=0x00077d44
- (BOOL)matchesPlatforms:(id)fp8;	// IMP=0x00077f40
- (id)platformDisplayName;	// IMP=0x000781ec
- (id)platformName;	// IMP=0x00077f08
- (void)setInfo:(id)fp8 forCapability:(id)fp12;	// IMP=0x00077ea4
- (id)systemVersion;	// IMP=0x00077e24

@end

