/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert
{
    int _count;	// 48 = 0x30
    id _delegate;	// 52 = 0x34
    SBPowerDownView *_powerDownView;	// 56 = 0x38
    BOOL _isFront;	// 60 = 0x3c
}

+ (id)sharedInstance;	// IMP=0x00044e94
- (void)activate;	// IMP=0x00045058
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0004510c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00045128
- (float)autoLockTime;	// IMP=0x00044f38
- (void)cancel;	// IMP=0x00045158
- (BOOL)deactivate;	// IMP=0x000450c4
- (void)dealloc;	// IMP=0x00044ee4
- (BOOL)isOrderedFront;	// IMP=0x00044f44
- (void)orderFront;	// IMP=0x00044f4c
- (void)orderOut;	// IMP=0x00044f5c
- (void)powerDown;	// IMP=0x00045134
- (id)powerDownView;	// IMP=0x00044f7c
- (void)setDelegate:(id)fp8;	// IMP=0x0004512c

@end

