/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class NSTimer, SBPowerDownController, TPBottomButtonBar, TPTopLockBar, UIView;

@interface SBPowerDownView : SBAlertDisplay
{
    UIView *_dimView;	// 36 = 0x24
    TPTopLockBar *_lockView;	// 40 = 0x28
    TPBottomButtonBar *_cancelView;	// 44 = 0x2c
    SBPowerDownController *_powerDownController;	// 48 = 0x30
    NSTimer *_autoDismissTimer;	// 52 = 0x34
}

- (void)animateDark;	// IMP=0x00045c64
- (void)animateIn;	// IMP=0x00045848
- (void)animateOut;	// IMP=0x00045a7c
- (void)cancel:(id)fp8;	// IMP=0x0004570c
- (void)cancelAutoDismissTimer;	// IMP=0x00045648
- (void)dealloc;	// IMP=0x000455cc
- (void)finishedAnimatingIn;	// IMP=0x000457d4
- (void)finishedAnimatingOut;	// IMP=0x0004580c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0004517c
- (void)lockBarStartedTracking:(id)fp8;	// IMP=0x00045774
- (void)lockBarStoppedTracking:(id)fp8;	// IMP=0x00045790
- (void)lockBarUnlocked:(id)fp8;	// IMP=0x00045740
- (void)notifyDelegateOfPowerDown;	// IMP=0x00045828
- (void)powerDown:(id)fp8;	// IMP=0x000457ac
- (void)resetAutoDismissTimer;	// IMP=0x00045688
- (void)setPowerDownController:(id)fp8;	// IMP=0x000457cc

@end

