/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBRingerHUDController : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00048474
- (void)activate:(int)fp8;	// IMP=0x00048500
- (void)dealloc;	// IMP=0x000484c4

@end

