/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSArray, UITable;

@interface SBSIMToolkitListDisplay : SBSlidingAlertDisplay
{
    UITable *_table;	// 72 = 0x48
    NSArray *_items;	// 76 = 0x4c
}

+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00055034
- (void)_selectListItem:(unsigned long)fp8;	// IMP=0x00054254
- (id)_simToolkitListItems;	// IMP=0x0005419c
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00054648
- (void)dealloc;	// IMP=0x0005413c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00054300
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00054800
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x00054884
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x000545ec
- (BOOL)showsDesktopImage;	// IMP=0x000545e4
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x000548b0
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x00054ab8

@end

