/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitTextAlertDisplay.h"

@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0005522c
- (id)_activeCalls;	// IMP=0x00054b90
- (id)alertText;	// IMP=0x00054edc
- (void)dial:(id)fp8;	// IMP=0x00054bb4
- (void)dismiss:(id)fp8;	// IMP=0x00054b3c

@end

