/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertInputView.h"

@interface SBSIMToolkitGetInputDisplay : SBAlertInputView
{
}

- (void)alertDisplayWillBecomeVisible;	// IMP=0x00053cbc
- (void)displayDidTimeout;	// IMP=0x00053f4c
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00053c38
- (void)sbAlertInputViewCancelClicked:(id)fp8;	// IMP=0x00054038
- (void)sbAlertInputViewSendClicked:(id)fp8;	// IMP=0x00053fa0

@end

