/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMLockEntryAlertDisplay.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertDisplay : SBSIMLockEntryAlertDisplay
{
    int _state;	// 72 = 0x48
    NSString *_enteredPUKCode;	// 76 = 0x4c
    NSString *_newPIN;	// 80 = 0x50
}

- (void)_attemptPUKUnlock;	// IMP=0x00069ef4
- (id)_pukAttemptsRemainingLabel;	// IMP=0x00069a58
- (void)dealloc;	// IMP=0x000699f8
- (id)label;	// IMP=0x00069e34
- (void)setupFailureState;	// IMP=0x00069d10
- (void)setupSuccess;	// IMP=0x00069b58
- (id)titleText;	// IMP=0x00069c34
- (void)unlock;	// IMP=0x00069f0c

@end

