/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIScroller;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay
{
    SBTextDisplayView *_contentView;	// 72 = 0x48
    UIScroller *_scroller;	// 76 = 0x4c
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00055808
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00052ff8
- (void)accept:(id)fp8;	// IMP=0x0005388c
- (void)adjustScrollerFrame;	// IMP=0x000532f8
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0005376c
- (id)alertText;	// IMP=0x00053724
- (void)dealloc;	// IMP=0x000531f8
- (void)dismiss;	// IMP=0x00053974
- (void)dismiss:(id)fp8;	// IMP=0x00053900
- (void)displayDidTimeout;	// IMP=0x000536d0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x00053434
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00053278
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x00053674
- (BOOL)showsDesktopImage;	// IMP=0x0005366c

@end

