/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBSIMToolkitAlert : SBAlert
{
    BOOL _needsResponse;	// 48 = 0x30
    NSTimer *_timeoutTimer;	// 52 = 0x34
}

+ (void)_idleScreenShown:(id)fp8;	// IMP=0x0005272c
+ (void)_restartMonitor;	// IMP=0x00052aec
+ (void)_startSTKMonitor;	// IMP=0x00052848
+ (void)_stopSTKMonitor;	// IMP=0x000527a4
+ (id)currentAlert;	// IMP=0x000523b8
+ (void)registerForAlerts;	// IMP=0x00052b20
+ (void)setCurrentAlert:(id)fp8;	// IMP=0x0005236c
+ (struct __CTServerConnection *)simToolkitServerConnection;	// IMP=0x000517f0
+ (void)test;	// IMP=0x000525e8
+ (void)userEventOccurred;	// IMP=0x00051810
+ (BOOL)wantsNextUserEvent;	// IMP=0x00051800
- (BOOL)_delayEnabled;	// IMP=0x00052c28
- (void)_playTone:(struct __CFString *)fp8 forDuration:(float)fp12;	// IMP=0x00051b28
- (void)_stopTone:(id)fp8;	// IMP=0x000519f8
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x000523ec
- (void)clearTimeoutTimer;	// IMP=0x00052be8
- (void)dealloc;	// IMP=0x00051ad8
- (void)displayDidTimeout;	// IMP=0x00052df4
- (BOOL)needsResponse;	// IMP=0x0005185c
- (void)restartTimeoutTimer:(float)fp8;	// IMP=0x00052c80
- (void)sendResponse:(struct __CFString *)fp8;	// IMP=0x0005197c
- (void)sendResponse:(struct __CFString *)fp8 withBool:(BOOL)fp12;	// IMP=0x000518f0
- (void)sendResponse:(struct __CFString *)fp8 withString:(id)fp12;	// IMP=0x00051864
- (BOOL)sendResponseUponDisplay;	// IMP=0x00051a80
- (void)setNeedsResponse:(BOOL)fp8;	// IMP=0x00051854
- (void)startTimeoutTimerIfNecessary;	// IMP=0x00052d10
- (struct __CFString *)toolkitAlertType;	// IMP=0x000523c8

@end

