/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBSIMLockAlertItem : SBAlertItem
{
    int _status;	// 12 = 0xc
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00066db4
- (id)alertText;	// IMP=0x00066bac
- (id)alertTitle;	// IMP=0x00066a3c
- (BOOL)canUnlock;	// IMP=0x00066a24
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;	// IMP=0x00066e6c
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x00066cec
- (void)dismiss;	// IMP=0x00066d2c
- (id)lockLabel;	// IMP=0x00067098
- (void)performUnlockAction;	// IMP=0x00066e0c
- (int)status;	// IMP=0x00066ce4
- (void)unlock;	// IMP=0x00066d6c

@end

