/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBDeviceLockKeypad, SBEmergencyCallView, TPLCDView, UIImageView, UIPasscodeField, UIView;

@interface SBSlidingAlertDisplay : SBAlertDisplay
{
    UIImageView *_backgroundView;	// 36 = 0x24
    UIView *_topBar;	// 40 = 0x28
    UIView *_bottomBar;	// 44 = 0x2c
    TPLCDView *_deviceLockStatusView;	// 48 = 0x30
    SBDeviceLockKeypad *_deviceLockKeypad;	// 52 = 0x34
    UIImageView *_deviceLockEntryBackground;	// 56 = 0x38
    UIPasscodeField *_deviceLockEntryField;	// 60 = 0x3c
    SBEmergencyCallView *_emergencyCallView;	// 64 = 0x40
    BOOL _playKeyboardClicks;	// 68 = 0x44
    unsigned int _animatingEmergencyCall:1;	// 69 = 0x45
    unsigned int _animatingIn:1;	// 69 = 0x45
    unsigned int _animatingOut:1;	// 69 = 0x45
    unsigned int _shouldFenceAnimations:1;	// 69 = 0x45
    unsigned int _showingDeviceLock:1;	// 69 = 0x45
    unsigned int _attemptingUnlock:1;	// 69 = 0x45
    unsigned int _showingDeviceUnlockFailure:1;	// 69 = 0x45
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x0004de34
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x0004ddc0
+ (void)setDisplayPropertiesForActivationOfAlert:(id)fp8;	// IMP=0x0004de3c
- (void)_animateToHidingDeviceLockFinished;	// IMP=0x0004fd18
- (void)_animateToHidingOrShowingDeviceLockFinished;	// IMP=0x0004fc80
- (void)_animateToShowingDeviceLockFinished;	// IMP=0x0004fcd4
- (void)_animateView:(id)fp8 direction:(int)fp12;	// IMP=0x000503d4
- (void)_clearUnlockFailedIndicator;	// IMP=0x0004e188
- (void)_enableEntry;	// IMP=0x0004ffc4
- (void)_entryFinishedWithPassword:(id)fp8;	// IMP=0x000500ec
- (struct CGRect)_entryFrame;	// IMP=0x0004f734
- (void)_fadeOutCompleted:(id)fp8;	// IMP=0x0004ea10
- (void)_resetStatusTextView;	// IMP=0x0004e0cc
- (void)_setTopBarImage:(id)fp8 shadowColor:(struct CGColor *)fp12;	// IMP=0x0004df6c
- (void)_showUnlockFailedIndicator;	// IMP=0x0004e1e8
- (float)_startingKeypadXOrigin;	// IMP=0x0004f7d4
- (void)alertDisplayWillBecomeVisible;	// IMP=0x0004f574
- (void)animateDisplayIn:(float)fp8 middleDelay:(float)fp12 animateStatusBar:(BOOL)fp16;	// IMP=0x0004f2a0
- (void)animateFromEmergencyCallWithDuration:(float)fp8;	// IMP=0x0005082c
- (void)animateToEmergencyCall;	// IMP=0x00050458
- (void)animateToShowingDeviceLock:(BOOL)fp8;	// IMP=0x0004f88c
- (void)beginAnimatingDisplayIn:(BOOL)fp8;	// IMP=0x0004eff4
- (id)bottomBar;	// IMP=0x00050b54
- (void)dealloc;	// IMP=0x0004e438
- (void)deviceUnlockCanceled;	// IMP=0x0004ff84
- (void)deviceUnlockFailed;	// IMP=0x0004fd90
- (void)deviceUnlockSucceeded;	// IMP=0x0004fd5c
- (void)dismiss;	// IMP=0x0004eb2c
- (float)durationForOthersActivation;	// IMP=0x0004eb24
- (void)emergencyCallWasDisplayed;	// IMP=0x00050760
- (void)emergencyCallWasRemoved;	// IMP=0x00050a74
- (void)finishedAnimatingIn;	// IMP=0x0004e934
- (void)getFrameForTopButton:(struct CGRect *)fp8 bottomButton:(struct CGRect *)fp12;	// IMP=0x0004e5f8
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0004e298
- (BOOL)isAnimatingOut;	// IMP=0x0004ea00
- (BOOL)isDisplayingErrorStatus;	// IMP=0x0005008c
- (BOOL)isReadyToBeRemovedFromView;	// IMP=0x0004eb10
- (BOOL)isShowingDeviceLock;	// IMP=0x0004f724
- (id)lockBar;	// IMP=0x0004e4e0
- (struct CGRect)middleFrame;	// IMP=0x0004e538
- (void)passcodeFieldDidAcceptEntry:(id)fp8;	// IMP=0x000503d0
- (void)performAnimateDisplayIn;	// IMP=0x0004f208
- (void)phonePad:(id)fp8 keyDown:(BOOL)fp12;	// IMP=0x00050140
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;	// IMP=0x00050170
- (void)removeBlockedStatus;	// IMP=0x00050058
- (void)setMiddleContentAlpha:(float)fp8;	// IMP=0x0004eaf0
- (void)setShouldFenceAnimations:(BOOL)fp8;	// IMP=0x0004f70c
- (void)setShowingDeviceLock:(BOOL)fp8;	// IMP=0x0004f868
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;	// IMP=0x00050b64
- (BOOL)shouldAnimateIconsIn;	// IMP=0x0004e9b0
- (BOOL)shouldAnimateIconsOut;	// IMP=0x0004e9f8
- (BOOL)shouldShowBlockedRedStatus;	// IMP=0x00050014
- (void)showBlockedStatus;	// IMP=0x0005001c
- (BOOL)showsDesktopImage;	// IMP=0x0004e798
- (id)topBar;	// IMP=0x00050b5c
- (void)updateDesktopImage:(id)fp8;	// IMP=0x0004e7a0

@end

