/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSoundPreferences : NSObject
{
}

+ (id)calendarAlarmPath;	// IMP=0x0004cf20
+ (BOOL)playLockSound;	// IMP=0x0004cff4
+ (id)ringtonePath;	// IMP=0x0004cf70
+ (BOOL)shouldVibrateForCurrentRingerState;	// IMP=0x0004d244
+ (void)userDefaultsDidChanged:(id)fp8;	// IMP=0x0004ce40
+ (id)vibratePattern;	// IMP=0x0004d058
+ (BOOL)vibrateWhenRinging;	// IMP=0x0004d17c
+ (BOOL)vibrateWhenSilent;	// IMP=0x0004d1e0

@end

