/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString;

@interface SBStatusBarNoServiceView : SBStatusBarContentView
{
    NSString *_errorString;	// 36 = 0x24
}

+ (id)displayStringForRegistrationStatus:(int)fp8;	// IMP=0x0005c638
+ (id)displayStringForSIMStatus:(id)fp8;	// IMP=0x0005c4d4
- (void)dealloc;	// IMP=0x0005c7b0
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0005c804
- (id)initWithErrorString:(id)fp8;	// IMP=0x0005c6d8
- (struct __GSFont *)textFont;	// IMP=0x0005c8a4

@end

