/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString, SBStatusBar, SBStatusBarContentsView, UIWindow;

@interface SBStatusBarController : NSObject
{
    UIWindow *_slidingStatusBarWindow;	// 4 = 0x4
    int _slidingStatusBarAnimation;	// 8 = 0x8
    UIWindow *_animatingCallStatusBarWindow;	// 12 = 0xc
    UIWindow *_leftBottomCorner;	// 16 = 0x10
    UIWindow *_rightBottomCorner;	// 20 = 0x14
    SBStatusBar *_statusBarView;	// 24 = 0x18
    SBStatusBarContentsView *_statusBarContentsView;	// 28 = 0x1c
    SBStatusBar *_transitioningStatusBarView;	// 32 = 0x20
    SBStatusBar *_animatingCallStatusBar;	// 36 = 0x24
    SBStatusBarContentsView *_transitioningStatusBarContentsView;	// 40 = 0x28
    unsigned int _isLocked:1;	// 44 = 0x2c
    unsigned int _lockIsChanging:1;	// 44 = 0x2c
    unsigned int _dimmed:1;	// 44 = 0x2c
    unsigned int _showDimmerOverlay:1;	// 44 = 0x2c
    unsigned int _animating:1;	// 44 = 0x2c
    unsigned int _isInCall:1;	// 44 = 0x2c
    unsigned int _airplaneMode:1;	// 44 = 0x2c
    unsigned int _showsProgress:1;	// 44 = 0x2c
    unsigned int _cloakStatusBar:1;	// 45 = 0x2d
    unsigned int _showAirport:1;	// 45 = 0x2d
    unsigned int _animateDefaultStatusBarDown:1;	// 45 = 0x2d
    unsigned int _animateDefaultStatusBarUp:1;	// 45 = 0x2d
    NSMutableArray *_statusBarIndicatorNames;	// 48 = 0x30
    int _mode;	// 52 = 0x34
    int _orientation;	// 56 = 0x38
    int _animatingCallStatusBarOrientation;	// 60 = 0x3c
    NSString *_customText;	// 64 = 0x40
    int _airPortSignalStrength;	// 68 = 0x44
    int _queuedStatusBarMode;	// 72 = 0x48
    int _queuedStatusBarOrientation;	// 76 = 0x4c
    float _duration;	// 80 = 0x50
    BOOL _telephonyControllerCheckedIn;	// 84 = 0x54
    BOOL _bluetoothControllerCheckedIn;	// 85 = 0x55
}

+ (BOOL)isLikeAFullScreenStatusBar:(int)fp8;	// IMP=0x0002d944
+ (id)sharedStatusBarController;	// IMP=0x0002d45c
+ (id)statusBarImageNamed:(id)fp8 forMode:(int)fp12;	// IMP=0x0002ea58
- (void)_SIMOrServiceStatusChanged;	// IMP=0x0002df2c
- (id)_SIMStatus;	// IMP=0x0002debc
- (void)_SIMStatusChanged:(id)fp8;	// IMP=0x0002dfa4
- (void)_finishStatusBarAnimation;	// IMP=0x0002e604
- (BOOL)_isServiceAvailable;	// IMP=0x0002de20
- (void)_serviceStatusChanged:(id)fp8;	// IMP=0x0002dfc0
- (void)_setStatusBarSize:(BOOL)fp8;	// IMP=0x0002f8dc
- (void)_setTransitionalStatusBarSize:(BOOL)fp8;	// IMP=0x0002f7c0
- (void)addStatusBarItem:(id)fp8;	// IMP=0x0002d670
- (int)airPortStrength;	// IMP=0x0002e2c4
- (BOOL)airplaneModeIsEnabled;	// IMP=0x0002e0bc
- (void)animateDefaultStatusBarDown;	// IMP=0x0002dd94
- (void)animateDefaultStatusBarUp:(int)fp8;	// IMP=0x0002ddb4
- (float)animationDuration;	// IMP=0x0002ea50
- (BOOL)bluetoothControllerCheckedIn;	// IMP=0x0002ede4
- (void)checkInController:(int)fp8;	// IMP=0x0002ed7c
- (BOOL)cloakStatusBar;	// IMP=0x0002e33c
- (id)customText;	// IMP=0x0002e15c
- (void)dealloc;	// IMP=0x0002d4ac
- (BOOL)dimmed;	// IMP=0x0002d8c0
- (void)endCallStatusBarAnimationFinished;	// IMP=0x0002dc08
- (void)finishSwitching;	// IMP=0x0002e3b0
- (id)init;	// IMP=0x000305cc
- (BOOL)isAnimatingStatusBarDown;	// IMP=0x0002dda4
- (BOOL)isAnimatingStatusBarUp;	// IMP=0x0002de10
- (BOOL)isInCall;	// IMP=0x0002dd84
- (BOOL)isLockChanging;	// IMP=0x0002d7d0
- (BOOL)isLocked;	// IMP=0x0002d7c4
- (void)lockCurrentStatusBarForAnimation;	// IMP=0x0002e77c
- (void)loopCarrierNameIfNecessary;	// IMP=0x0002edec
- (void)orderStatusBarFront;	// IMP=0x0002e530
- (void)preheatStatusBarForMode:(int)fp8 orientation:(int)fp12;	// IMP=0x00030aa8
- (void)releaseLockedStatusBarForAnimationForDisplay:(id)fp8;	// IMP=0x0002e824
- (void)removeStatusBarItem:(id)fp8;	// IMP=0x0002e0cc
- (void)resizeStatusBar:(float)fp8 grow:(BOOL)fp12;	// IMP=0x0002fd64
- (void)restoreLevels;	// IMP=0x0002e4b8
- (void)setAirPortStrength:(int)fp8;	// IMP=0x0002e1cc
- (void)setAirplaneModeIsEnabled:(BOOL)fp8;	// IMP=0x0002dfdc
- (void)setCloakStatusBar:(BOOL)fp8;	// IMP=0x0002e2e4
- (void)setCustomText:(id)fp8;	// IMP=0x0002e164
- (void)setDimmed:(BOOL)fp8;	// IMP=0x0002d7e0
- (void)setIsInCall:(BOOL)fp8;	// IMP=0x0002dc68
- (void)setIsLocked:(BOOL)fp8;	// IMP=0x0002d75c
- (void)setShowDimmerOverlay:(BOOL)fp8;	// IMP=0x0002d8e0
- (void)setShowsAirPort:(BOOL)fp8;	// IMP=0x0002e230
- (void)setStatusBarMode:(int)fp8 orientation:(int)fp12 duration:(float)fp16 fenceID:(int)fp20 animation:(int)fp24;	// IMP=0x0002ee0c
- (void)setupWindowForSlidingStatusBar:(id)fp8 overStatusBar:(id)fp12;	// IMP=0x0002da3c
- (BOOL)showDimmerOverlay;	// IMP=0x0002d8d0
- (BOOL)showsAirPort;	// IMP=0x0002e29c
- (BOOL)showsProgress;	// IMP=0x0002e378
- (void)signalFormatChanged;	// IMP=0x0002ed4c
- (void)significantTimeChange;	// IMP=0x0002ecfc
- (void)statusBarDidFinishAnimatingDown;	// IMP=0x0002e4a8
- (void)statusBarDidFinishAnimatingUp;	// IMP=0x0002e520
- (id)statusBarIndicatorNames;	// IMP=0x0002e154
- (int)statusBarMode;	// IMP=0x0002ea40
- (int)statusBarOrientation;	// IMP=0x0002ea48
- (id)statusBarView;	// IMP=0x0002d660
- (id)statusBarWindow;	// IMP=0x0002d640
- (void)switchBackstopFrom:(int)fp8 to:(int)fp12 fromOrientation:(int)fp16 toOrientation:(int)fp20 duration:(float)fp24 fenceID:(int)fp28 animation:(int)fp32;	// IMP=0x00030adc
- (void)tearDownWindowForSlidingStatusBar:(id)fp8 overStatusBar:(id)fp12;	// IMP=0x0002d96c
- (BOOL)telephonyControllerCheckedIn;	// IMP=0x0002eddc
- (id)transitioningStatusBarView;	// IMP=0x0002d668
- (void)updateClockFormat;	// IMP=0x0002ed2c
- (void)updateProgressVisibility;	// IMP=0x0002e348

@end

