/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class UIProgressIndicator;

@interface SBStatusBarProgressView : SBStatusBarContentView
{
    UIProgressIndicator *_progressIndicator;	// 36 = 0x24
    BOOL _wasLastUsingASlowConnection;	// 40 = 0x28
}

- (void)dataConnectionTypeChanged;	// IMP=0x00073d74
- (void)dealloc;	// IMP=0x00073d24
- (id)init;	// IMP=0x00073cac
- (void)progressChanged;	// IMP=0x00073f58
- (void)start;	// IMP=0x00073e60
- (void)stop;	// IMP=0x00073f04

@end

