/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class SBStatusBarOperatorNameView, UIImage;

@interface SBStatusBarCarrierView : SBStatusBarContentView
{
    UIImage *_operatorIcon;	// 36 = 0x24
    SBStatusBarOperatorNameView *_operatorNameView;	// 40 = 0x28
    BOOL _operatorNameIsLooping;	// 44 = 0x2c
}

- (BOOL)_operatorName:(id)fp8 isEqualToName:(id)fp12;	// IMP=0x0003dfa0
- (void)clearLastOperatorNameLooped;	// IMP=0x0003d664
- (void)dealloc;	// IMP=0x0003d448
- (struct CGSize)defaultSize;	// IMP=0x0003df10
- (void)finishedLoopingOperatorName:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003d8d8
- (id)init;	// IMP=0x0003e168
- (void)loopIfNecessary;	// IMP=0x0003da20
- (void)loopOperatorNameToBeginning:(id)fp8 didFinish:(id)fp12;	// IMP=0x0003d6c0
- (void)loopOperatorNameToEnd;	// IMP=0x0003d79c
- (id)operatorIconForName:(id)fp8;	// IMP=0x0003dd98
- (void)operatorNameChanged;	// IMP=0x0003df48
- (void)setOperatorName:(id)fp8;	// IMP=0x0003da9c
- (void)start;	// IMP=0x0003d4a8
- (void)startOperatorNameLooping:(id)fp8;	// IMP=0x0003d9b4
- (void)stop;	// IMP=0x0003d5d0

@end

