/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class UIView;

@interface SBStatusWindow : UIWindow
{
    int _orientation;	// 72 = 0x48
    UIView *_holderView;	// 76 = 0x4c
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x0001aa74
- (id)holderView;	// IMP=0x0001abac
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x0001aaa0
- (BOOL)isOpaque;	// IMP=0x0001aa98
- (int)orientation;	// IMP=0x0001ab9c
- (void)setOrientation:(int)fp8;	// IMP=0x0001aba4

@end

