/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarSignalView : SBStatusBarContentView
{
    int _dBm;	// 36 = 0x24
    int _signalStrength;	// 40 = 0x28
}

- (int)barsForRawDBM:(float)fp8;	// IMP=0x0003f314
- (void)dealloc;	// IMP=0x0003f1d4
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x0003f5b8
- (id)init;	// IMP=0x0003f15c
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x0003f7d8
- (void)setSignalStrength:(int)fp8;	// IMP=0x0003f488
- (void)start;	// IMP=0x0003f224
- (void)stop;	// IMP=0x0003f2c4

@end

