/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSyncController : NSObject
{
    int _syncState;	// 4 = 0x4
    int _restoreState;	// 8 = 0x8
    int _resetState;	// 12 = 0xc
    int _sofwareUpdateState;	// 16 = 0x10
    struct __CFMachPort *_backupAgentCFPort;	// 20 = 0x14
}

+ (id)sharedInstance;	// IMP=0x00071e10
- (void)_delayedTurnOffRadio;	// IMP=0x000728b4
- (void)_invalidateBackupAgentCFPort;	// IMP=0x00072b08
- (void)_notifyAppsSyncWillBegin;	// IMP=0x000722bc
- (void)_notifyRestoreCanProceed;	// IMP=0x000724cc
- (void)_rebootNow;	// IMP=0x000726e4
- (BOOL)_setupBackupAgentPort;	// IMP=0x00072b78
- (void)beginResetting;	// IMP=0x0007292c
- (void)beginRestoring;	// IMP=0x000724fc
- (void)beginSyncing;	// IMP=0x000723a8
- (void)cancelRestoring;	// IMP=0x000726d8
- (void)cancelSyncing;	// IMP=0x0007225c
- (void)dealloc;	// IMP=0x00071e60
- (void)didEndResetting;	// IMP=0x000729c0
- (void)didEndRestoring:(int)fp8;	// IMP=0x00072714
- (void)didEndSyncing;	// IMP=0x000720dc
- (void)didShowSyncPanel;	// IMP=0x000722ec
- (void)finishEndRestoring;	// IMP=0x000726f8
- (void)finishedTerminatingApplications;	// IMP=0x00072610
- (void)frontLockedWhenPossible;	// IMP=0x00072308
- (void)iTunesSyncHasCompleted:(int)fp8;	// IMP=0x0007246c
- (void)iTunesSyncRequestedStart;	// IMP=0x00072448
- (BOOL)isInUse;	// IMP=0x00072cc4
- (BOOL)isResetting;	// IMP=0x00072894
- (BOOL)isRestoring;	// IMP=0x000724ac
- (BOOL)isSoftwareUpdating;	// IMP=0x00072c1c
- (BOOL)isSyncing;	// IMP=0x000720a8
- (int)resetState;	// IMP=0x000728ac
- (int)restoreState;	// IMP=0x000724c4
- (void)resumeSyncing;	// IMP=0x000721b4
- (void)setSoftwareUpdateState:(int)fp8;	// IMP=0x00072c14
- (void)showPreSoftwareUpdateScreen;	// IMP=0x00072d4c
- (void)startObserving;	// IMP=0x00071eb0
- (void)stopObserving;	// IMP=0x00071fd8
- (void)suspendSyncing;	// IMP=0x00072160
- (int)syncState;	// IMP=0x000720d4

@end

