/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBTelephonyManager : NSObject
{
    NSString *_operatorName;	// 4 = 0x4
}

+ (id)sharedTelephonyManager;	// IMP=0x00027ef4
- (BOOL)EDGEIsAvailable;	// IMP=0x0002a340
- (BOOL)EDGEIsOn;	// IMP=0x0002a358
- (id)SIMStatus;	// IMP=0x0002aea8
- (void)_cancelFakeService;	// IMP=0x0002a94c
- (void)_delayedAudioResume;	// IMP=0x00028c28
- (id)_fetchOperatorName;	// IMP=0x0002ab20
- (void)_headphoneChanged:(id)fp8;	// IMP=0x0002a720
- (void)_mainThreadDaemonRestart:(struct __CFDictionary *)fp8;	// IMP=0x00028b4c
- (void)_reallySetOperatorName:(id)fp8;	// IMP=0x0002ab74
- (void)_resetCTMMode;	// IMP=0x0002a6e4
- (struct __CTServerConnection *)_serverConnection;	// IMP=0x00027f48
- (void)_setRegistrationStatus:(int)fp8;	// IMP=0x0002a874
- (void)_startFakeServiceIfNecessary;	// IMP=0x0002a990
- (void)_stopFakeService;	// IMP=0x0002aa20
- (void)_updateRegistrationNow;	// IMP=0x0002a910
- (void)_updateState;	// IMP=0x000281dc
- (void)_whackGain:(id)fp8;	// IMP=0x00028398
- (BOOL)activeCallExists;	// IMP=0x000298c4
- (id)allMissedCallsAfterRowID:(long long)fp8;	// IMP=0x00029768
- (id)allUnreadSMSAfterRowID:(long long)fp8;	// IMP=0x000297a0
- (void)answerIncomingCall;	// IMP=0x00029a10
- (void)answerIncomingCallEndingOthers;	// IMP=0x00029aa0
- (int)callCount;	// IMP=0x000298b4
- (void)checkForRegistrationSoon;	// IMP=0x0002ad9c
- (void)configureForTTY:(BOOL)fp8;	// IMP=0x0002a494
- (void)copyICCID:(id *)fp8 IMEI:(id *)fp12;	// IMP=0x0002a408
- (int)dataConnectionType;	// IMP=0x0002a330
- (void)disconnectAllCalls;	// IMP=0x00029bbc
- (void)disconnectCall;	// IMP=0x00029be4
- (void)disconnectCallAndActivateHeld;	// IMP=0x00029cec
- (void)disconnectIncomingCall;	// IMP=0x000299ec
- (id)displayForOutgoingCallURL:(id)fp8;	// IMP=0x00028560
- (void)dumpBasebandState:(id)fp8;	// IMP=0x00029d70
- (long long)getRowIDOfLastCallInsert;	// IMP=0x00029758
- (long long)getRowIDOfLastSMSInsert;	// IMP=0x00029790
- (BOOL)heldCallExists;	// IMP=0x000298dc
- (BOOL)inCall;	// IMP=0x000299ac
- (double)inCallDuration;	// IMP=0x0002803c
- (BOOL)inCallUsingReceiver;	// IMP=0x00029924
- (BOOL)incomingCallExists;	// IMP=0x000298f4
- (id)init;	// IMP=0x0002b304
- (BOOL)isUsingDataConnection;	// IMP=0x0002a3d0
- (BOOL)isUsingWiFiConnection;	// IMP=0x0002a3ec
- (void)markMessageAsRead:(struct __CTSMSMessage *)fp8;	// IMP=0x000297c8
- (id)operatorName;	// IMP=0x0002ac94
- (BOOL)outgoingCallExists;	// IMP=0x0002990c
- (void)powerOffRadio;	// IMP=0x00029de4
- (int)registrationStatus;	// IMP=0x0002ad8c
- (void)setOperatorName:(id)fp8;	// IMP=0x0002ac18
- (BOOL)shouldPromptForTTY;	// IMP=0x0002a4fc
- (void)swapCalls;	// IMP=0x00029b84
- (id)ttyTitle;	// IMP=0x0002a5d4
- (void)unmute;	// IMP=0x00029cfc
- (void)updateAirplaneMode;	// IMP=0x00028124
- (void)updateCalls;	// IMP=0x000294c4
- (void)updateLocale;	// IMP=0x0002829c
- (void)updateSMSBadges;	// IMP=0x000297fc
- (void)updateSpringBoard;	// IMP=0x0002b8a8
- (void)updateTTYIndicator;	// IMP=0x00027fb4
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20;	// IMP=0x00028414

@end

