/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;	// IMP=0x00062138
+ (id)createTopBarForInstance:(id)fp8;	// IMP=0x00062090
- (void)_chooseTTYMode:(id)fp8;	// IMP=0x000623e4
- (void)_chooseVoiceMode:(id)fp8;	// IMP=0x00062390
- (void)_ignore:(id)fp8;	// IMP=0x0006243c
- (void)_makeCall;	// IMP=0x00062248
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x00061e9c

@end

