/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSTimer;

@interface SBUSSDAlert : SBAlert
{
    unsigned int _receivedString:1;	// 48 = 0x30
    unsigned int _dismissOnActivate:1;	// 48 = 0x30
    NSTimer *_delayedDismissTimer;	// 52 = 0x34
}

+ (void)_daemonRestart:(id)fp8;	// IMP=0x00059ff0
+ (void)_newSIM:(id)fp8;	// IMP=0x0005a0b8
+ (id)errorStringForCode:(unsigned int)fp8;	// IMP=0x00059f64
+ (void)registerForAlerts;	// IMP=0x00059d40
+ (void)registerForSettingsAlerts;	// IMP=0x00059c8c
+ (void)test;	// IMP=0x00059ed4
- (void)USSDStringAvailable:(id)fp8 allowsResponse:(BOOL)fp12;	// IMP=0x0005a120
- (void)_delayedDismiss;	// IMP=0x0005a24c
- (BOOL)activate;	// IMP=0x0005a2b0
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;	// IMP=0x0005a0c8
- (BOOL)allowsResponse;	// IMP=0x0005a1f0
- (BOOL)deactivate;	// IMP=0x0005a3d0
- (void)dealloc;	// IMP=0x00059c08
- (BOOL)receivedString;	// IMP=0x0005a228
- (void)setDismissOnActivate:(BOOL)fp8;	// IMP=0x0005a234

@end

