/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBTextDisplayView, TPBottomButtonBar, UIProgressIndicator, UIScroller, UITextField, UITransitionView, UIView;

@interface SBUSSDAlertDisplay : SBAlertDisplay
{
    TPBottomButtonBar *_responseBar;	// 36 = 0x24
    UIView *_notifyView;	// 40 = 0x28
    UIView *_replyView;	// 44 = 0x2c
    UITransitionView *_transitionView;	// 48 = 0x30
    UIScroller *_scroller;	// 52 = 0x34
    UIView *_contentView;	// 56 = 0x38
    SBTextDisplayView *_charsRemainingView;	// 60 = 0x3c
    UIProgressIndicator *_progressIndicator;	// 64 = 0x40
    UITextField *_responseField;	// 68 = 0x44
    BOOL _allowsResponse;	// 72 = 0x48
}

- (void)_cancelClicked;	// IMP=0x0003284c
- (id)_notifyView;	// IMP=0x0003233c
- (void)_okayClicked;	// IMP=0x000327dc
- (void)_replyClicked;	// IMP=0x00032ce4
- (id)_replyView;	// IMP=0x000323dc
- (void)_setupResponseBar;	// IMP=0x0003386c
- (void)_textChanged:(id)fp8;	// IMP=0x000327c0
- (void)_updateCharsRemaining;	// IMP=0x00032690
- (void)alertDisplayBecameVisible;	// IMP=0x00032588
- (void)alertDisplayWillBecomeVisible;	// IMP=0x00033c20
- (void)alertStringAvailable:(id)fp8;	// IMP=0x000325a8
- (BOOL)allowsResponse;	// IMP=0x0003262c
- (void)dealloc;	// IMP=0x000324d4
- (void)displayString:(id)fp8 centerVertically:(BOOL)fp12;	// IMP=0x00032f8c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x000321b0
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;	// IMP=0x00032874
- (void)setAllowsResponse:(BOOL)fp8;	// IMP=0x00033308
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;	// IMP=0x00032634

@end

