/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDismissOnlyAlertItem.h"

@interface SBVoiceMailAlertItem : SBDismissOnlyAlertItem
{
    BOOL _isForVisualVoicemail;	// 29 = 0x1d
    unsigned int _recordUID;	// 32 = 0x20
}

+ (id)currentInstance;	// IMP=0x00071204
+ (BOOL)hasCurrentInstance;	// IMP=0x000712c8
- (void)didDeactivate:(BOOL)fp8;	// IMP=0x000712f4
- (BOOL)isForVisualVoicemail;	// IMP=0x000712e0
- (id)lockLabel;	// IMP=0x000714c0
- (void)performUnlockAction;	// IMP=0x0007132c
- (void)setIsVisualVoicemail:(BOOL)fp8 recordUID:(unsigned int)fp12;	// IMP=0x000712e8
- (BOOL)willShowInAwayItems;	// IMP=0x00071324

@end

