/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplication.h"

@interface SBWidgetApplication : SBApplication
{
}

- (id)arguments;	// IMP=0x00021c44
- (id)bundleForLaunching;	// IMP=0x00021bdc
- (BOOL)isWidget;	// IMP=0x00021c3c
- (id)pathForDefaultImage:(char *)fp8;	// IMP=0x00021a74
- (id)pathForIcon;	// IMP=0x00021bb4

@end

